### PR TITLE
Allow spiders to also return/yield ItemLoader.

### PR DESCRIPTION
**Pull request by vincent-ferotin**
Behind, Scrapy will convert ItemLoader to Item by calling
:meth:`ItemLoader.load_item`.

### CODE REVIEW

**Comment by whalebot-helmsman** [comment]
@vincent-ferotin Problem with unit-tests was fixed in master. Can you merge master to this PR?

**Comment by vincent-ferotin** [comment]
@whalebot-helmsman Here it is, I hope so? (not enough familiar/confident with git/GitHub to be sure, please let tell me if it is not ok for you ^^;)

**Comment by whalebot-helmsman** [comment]
Thanks, @vincent-ferotin mentioned problems with twisted is gone. I don't know the reason why other tests are in failed state.

**Comment by kmike** [comment]
Hi @vincent-ferotin! I can see how this feature can save some typing, and API improvements are good to have. However, currently I'm -0 to add such feature because: 

* there was an idea to move ItemLoaders out of Scrapy;
* it complicates API of a spider; custom middlewares would need to be modified in order to support a new possible output type (?).

The implementation also needs work: 

* if I'm not mistaken, currently it can lead to subtle bugs (see https://github.com/scrapy/scrapy/issues/616)
* there are no tests;
* documentation is not updated (you can probably check https://github.com/scrapy/scrapy/pull/1081 for suggestions of doc locations to be updated).

**Comment by Gallaecio** [comment]
Closing as, even if implemented, https://github.com/scrapy/itemadapter would be the right place now.

**Pull request closed without merging**
