### PR TITLE
Fix warning: Expected type 'bool', got 'int' instead

### PR DESCRIPTION
**Pull request by azenkwed**
Minor fix: **twisted.internet.defer.DeferredList**  parameter  **consumeErrors** expects _boolean_, got _integer_ instead.

### CODE REVIEW

**Comment by elacuesta** [comment]
Looks correct according to [the docs](https://twistedmatrix.com/documents/current/api/twisted.internet.defer.DeferredList.html#__init__). Could you please also update [this line](https://github.com/scrapy/scrapy/blob/2.4.1/scrapy/utils/defer.py#L108)?
When does this warning appear? I couldn't find any occurrences in the tests.

**Comment by Gallaecio** [comment]
Looks like it’s safe to change, as the lowest version of Twisted that we support [also has the parameters as booleans in the documentation](https://twistedmatrix.com/documents/17.9.0/api/twisted.internet.defer.DeferredList.html#__init__).

The old syntax [can be seen in the documentation of Twisted 10](https://twistedmatrix.com/documents/10.0.0/api/twisted.internet.defer.DeferredList.html#__init__), for example.

**Comment by azenkwed** [comment]
> Looks correct according to [the docs](https://twistedmatrix.com/documents/20.3.0/api/twisted.internet.defer.DeferredList.html#__init__). Could you please also update [this line](https://github.com/scrapy/scrapy/blob/2.4.1/scrapy/utils/defer.py#L108)?
> When does this warning appear? I couldn't find any occurrences in the tests.

I will update [this line](https://github.com/scrapy/scrapy/blob/2.4.1/scrapy/utils/defer.py#L108). 
**fireOnOneErrback** should also be updated, as it also expect a boolean, according to the doc.
If the documentation suggest using a boolean, then I advise the update since this update doesn't break the code.

**Review by Gallaecio — APPROVED** [review]

**Review by elacuesta — APPROVED** [review]

**Comment by elacuesta** [comment]
Thanks @azenkwed!

**Pull request merged**
