### PR TITLE
[MRG+1] Fix for #3034, CSV export unnecessary blank lines problem on Windows

### LINKED ISSUE #3034: Line-ends (unnecessary blank lines) problem in CSV export on Windows
CSV export on Windows create unnecessary blank lines after each line.

You can fix the problem just by adding 
newline='' 
as parameter to io.TextIOWrapper in the __init__ method of the CsvItemExporter class in scrapy.exporters

Details are over here:
https://stackoverflow.com/questions/39477662/scrapy-csv-file-has-uniform-empty-rows/43394566#43394566

### PR DESCRIPTION
**Pull request by ReLLL**
Fixed the issue I've mentioned there, this is the pull request to merge, (added one line), hope all is fine. 
https://github.com/scrapy/scrapy/issues/3034

Closes #3034

### CODE REVIEW

**Comment by cathalgarvey** [comment]
Hi @ReLLL, I'm not familiar with the CSV-on-Windows issue, but are we sure that this change will not affect output behaviour/quality on other platforms? If that's a sure then, then the change looks easy to merge, and I'm willing to give it a +1.

**Comment by stranac** [comment]
@cathalgarvey There is no reason this should create a problem on any platforms, passing `newline=''` is the correct thing to do here, as documented in https://docs.python.org/3/library/csv.html#csv.reader

**Comment by cathalgarvey** [comment]
Well, in that case consider me MRG+1 for this PR. :)

**Comment by kmike** [comment]
Hey,

Is it possible to have a test case for this fix?

**Comment by dangra** [comment]
In #3315 I am trying to setup AppVeyor to run tests suite under Windows environment, the bad news is that the testsuite is far from passing due to filepaths, newlines and temporal files issues; but the good news is that this PR fixes tests for CSV exporters related to newline under Windows.

**Comment by dangra** [comment]
Thanks @ReLLL! If you feel like Scrapy support for Windows is important I'd like to encourage you to help with #3315

**Comment by lilianaziolek** [comment]
@dangra I'm using version 1.5.1 but despite seeing this in your master it doesn't seem to be in the latest released version. Is there any ETA on when this change will be available in a released version without having to hack my local build or build from source? Or am I missing a version that contains this change already?
Thanks!

**Pull request merged**
