### PR TITLE
In-progress Python 3 port

### PR DESCRIPTION
**Pull request by kmike**

### CODE REVIEW

**Comment by nyov** [comment]
A question about response body encoding:
It seems likely we'll often need `response.encoding` now to transcode between bytes and string.
Would you think it makes sense to enforce `Response` always having a `response.encoding` attribute (adding property `encoding` also to base `Response` class; probably just guessing utf-8 there) so code can depend on it being there?

case: robotsparser requires string while body is bytes - the testcase defines no r.encoding.
Should the test be amended, the encoding guessed in `RobotsTxtMiddleware` or a fallback/default `encoding` property defined in base `Response`?

**Comment by kmike** [comment]
@nyov I think encoding should be guessed in RobotsTxtMiddleware.

**Comment by kmike** [comment]
I quite like an idea of adding `body_as_unicode()` method to Response, where it will try hard to decode anything useful (e.g. using UnicodeDammit or something similar). This will be backwards incompatible though, because users may rely on a presence of `body_as_unicode` method to check if a response is binary. The same may apply to `.encoding` attribute.

Regarding RobotsTxtMiddleware: I think encoding should be detected in middleware, but it is also a good idea to add an extra test for TextResponse in addition to Response.

**Comment by nyov** [comment]
I considered this some more. Maybe it's easier to just concede to treat `Response` as strictly binary only? Instance `TextResponse`s in the testcases where non-binary is expected?
As you say it wouldn't make much sense to have `body_as_unicode` for a truly binary response (unless you meant to make it behave like GNU `strings` and just throw out anything non-printable there).

A slightly different idea: In effect we only have `Response` and `TextResponse`. HTML and XML classes are only leftover farces and instancing Text, Html or Xml is an arbitrary decision with the same result. It would make more sense to have a `mime` property for checking that.
We could turn `Response` into `BinaryResponse`, and create a `Response` class with the logic to build either Text- or BinaryResponse instances (essentially a renamed `ResponseTypes` with it's `from_args` as default op).
I think that might be nice because the detection logic of `ResponseTypes` seems under-used and appreciated.

**Comment by kmike** [comment]
@dangra are we bold enough to merge this PR to master?  I'm in favor of it.

**Comment by kmike** [comment]
@nyov Response vs BytesResponse renames is kind of orthogonal to Python 3 porting. I think there is something in your ideas, and it worths its own ticket.

**Comment by dangra** [comment]
@kmike yes, we are!

**Pull request merged**
