### PR TITLE
Remove deprecated `sel` shortcut in scrapy shell

### PR DESCRIPTION
**Pull request by noviluni**
It was 6 years ago when this deprecation warning was added, before Scrapy 1.0 was released.

Could we remove it when releasing the new Scrapy 2.0 version?

### CODE REVIEW

**Comment by noviluni** [comment]
There are some other deprecation warnings that could be removed in the new version. Let me know what you think about it and I will create another PR with the other deprecations.

**Comment by elacuesta** [comment]
Looks good to me, thanks :+1: 
For reference, the shortcut was deprecated in #690.
I'll approve once the Flake8 issues are solved

**Comment by kmike** [comment]
6 years passed 😱 This looks good, +1 to merge after fixing flake8 error.

**Comment by noviluni** [comment]
Thank you @Gallaecio for fixing the flake8 errors :sweat_smile: 

I opened a new issue with some old deprecation warnings to see if you have any inconvenience in adressing them: https://github.com/scrapy/scrapy/issues/4356

**Pull request merged**
