### PR TITLE
fix retry's with another proxy_authorization

### PR DESCRIPTION
**Pull request by ljm9104**
If one request is failed and the request uses ip proxy, in the fllowing times retry, if this times uses another ip  authorization, the request has already made request.headers.['Proxy-Authorization'] and this time we still use the original Proxy-Authorization, so I think we shouldn't judge the request.headers.get('Proxy-Authorization')  isexist or not, we should overwrite request.headers.['Proxy-Authorization'] every times,  or we should judge every time if it is isexsists and request.headers.['Proxy-Authorization'] is or not  the same with original. At last, I prefer the first  modify method.

`
# the downloadermiddlewares httpproxy
def process_request(self, request, spider):
    # ignore if proxy is already set
    if 'proxy' in request.meta:
        if request.meta['proxy'] is None:
            return
        # extract credentials if present
        creds, proxy_url = self._get_proxy(request.meta['proxy'], '')
        request.meta['proxy'] = proxy_url
        if creds and not request.headers.get('Proxy-Authorization'):
            request.headers['Proxy-Authorization'] = b'Basic ' + creds
        return
    elif not self.proxies:
        return
`

### CODE REVIEW

**Comment by Gallaecio** [comment]
Could you include a test for your change?

**Comment by ljm9104** [comment]
OK, I just add one demo project for test, I  add one proxy middleware in the demo project and some logging for recording the bug log, in order to test the bug, I have set the download_timeout to 0.1s, so it usually can't recieve one response,  just as you can see, in the log file, it retries for 10 times, but every time it uses the same `request.headers[b'Proxy-Authorization'] `.

**Comment by Gallaecio** [comment]
Sorry, that is not what I meant.

I mean for you to extend the automated tests of Scrapy to include one that verifies that your changes work (even though both you and I know they do), so that if someone accidentally breaks your changes in the future, your automated test detects it.

Please, see https://docs.scrapy.org/en/master/contributing.html#tests

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/5477#issuecomment-1194028505

**Pull request closed without merging**
