### PR TITLE
Cleanup of slot handling in Scraper.

### PR DESCRIPTION
**Pull request by wRAR**
This is minor cleanup of, I suppose, remains of multiple slots per Scraper, similar to parts of #5090, but I think there is nothing else to clean up/deprecate here.

### CODE REVIEW

**Comment by elacuesta** [comment]
Nice 🚀 
What do you think about storing the spider received in `open_spider` as an attribute to avoid passing it to underscored methods like `_check_if_closing`, `_scrape`, `_scrape_next`, etc?

**Comment by wRAR** [comment]
Good question, I guess I need to check the code that calls open/close_spider.

**Review by Gallaecio — APPROVED** [review]

**Comment by Gallaecio** [comment]
I’m not merging already just in case you want to address https://github.com/scrapy/scrapy/pull/5095#issuecomment-816938093 as part of this pull request.

**Comment by Gallaecio** [comment]
> Do we know if anything outside Scrapy could call these methods?

I would assume so, however unlikely.

**Pull request merged**
