### PR TITLE
RFC2616 policy enhancements

### PR DESCRIPTION
**Pull request by jameysharp**
These commits address several limitations I encountered in using the HttpCache download middleware.

I think each commit can be merged independently of the others, so if you have issues with some of the patches, I hope you can merge any others that are OK.

### CODE REVIEW

**Comment by dangra** [comment]
> Problem is that Twisted's ResponseFailed doesn't seem to be available for Python3, that's why the Retry Middleware is listed there as well.

I think the key is in that phrase, can we except ResponseFailed import on py3 instead of whole file? leaving a proper note saying why ResponseFailed can't be imported on py3.

**Comment by jameysharp** [comment]
I'd also suggest providing a common definition of the list of exceptions
that indicate transport-layer errors. I'd prefer to reference a
centrally-defined tuple that deals with these Python version issues once,
rather than copy-pasting a list that's about to change from the retry
middleware. And it seems like a useful list to expose for application use,
anyway.

What module would make sense to put such a definition in?

I can rebase this pull request on that to address the py3.3 test failures
if someone writes such a commit.

**Comment by Curita** [comment]
@dangra Having read Python's docs on porting (https://docs.python.org/3/howto/pyporting.html), I think we could add a static py3 linter to partially ensure support on all files, regardless there were dependency issues for actually running them with python3. Since the twisted's imports aren't easily mocked I think we'll still need to blacklist files using them, but the linter should help a little with the regression problem.

For stating why the files are blacklisted, maybe we could add a note on that file, but I'm not sure how maintainable that would be. Twisted has a `twisted/python/dist3.py` file where they list supported py3 modules (thought I'm not sure if it's a full support since I haven't seen yet how they consider internal dependencies), maybe we could check there and construct the list of blacklisted files for twisted dependencies automatically.

@jameysharp I like the idea, maybe we could add that list to an existing utils file or a new one?

**Comment by dangra** [comment]
@jameysharp I don't mind if you add the file to py3-ignores.txt if that is blocking you from finishing this PR.

**Comment by kmike** [comment]
+1, this PR looks very good, but it lacks tests. Adding tests to py3-ignores.txt is fine if it is hard to get it working in Python 3 right away.

**Comment by dangra** [comment]
closing in favor of #1151

**Pull request closed without merging**
