### PR TITLE
new offsite downloader-middleware

### PR DESCRIPTION
**Pull request by stav**
filters offsite redirects

https://github.com/scrapy/scrapy/issues/15

### CODE REVIEW

**Comment by gwintrob** [comment]
@stav Are there any plans to merge this in? We had the issue from https://github.com/scrapy/scrapy/issues/15 and it looks like this is the right fix. Thanks for sharing it!

**Comment by stav** [comment]
@gwintrob No plans I've heard about; but, you can still use it in your projects, outside of Scrapy.

**Comment by nramirezuy** [comment]
I don't like how it duplicates code, but at the same time I don't know where to put the intersecting code. :smile:

**Comment by stav** [comment]
Code now available in [its own branch](https://github.com/stav/scrapy/blob/209e565ebc9cfc177f506b941a51b9a425af3df6/scrapy/contrib/downloadermiddleware/offsite.py).

**Pull request closed without merging**
