### PR TITLE
[MRG+1] Py3: port test crawl

### PR DESCRIPTION
**Pull request by lopuhin**
Based on #1680, here are all changes in this branch https://github.com/lopuhin/scrapy/compare/7ffcc58...py3-test-crawl?expand=1

No "interesting" changes, only fixing bytes in tests - just hard to debug failures due to high-level nature of tests.

### CODE REVIEW

**Comment by kmike** [comment]
Could you please rebase it on master?

**Comment by lopuhin** [comment]
Hm, it seems that the build failed because ``bench`` command in tests took too long, and the port was not closed, that caused all of test_crawl to fail.

**Comment by kmike** [comment]
I've saved log to a gist (https://gist.github.com/kmike/282dc84facc492dff885) and restarted Python 3.3 build, let's see how it goes. But it may be a real problem; I haven't seen this issue before.

**Comment by redapple** [comment]
@kmike @lopuhin ,
I also had to rerun Python 3.3 build for https://travis-ci.org/scrapy/scrapy/builds/103806098
It passed that 2nd time.

**Comment by kmike** [comment]
Opened https://github.com/scrapy/scrapy/issues/1707 to track it.

**Comment by kmike** [comment]
It looks like one more rebase is needed.

**Comment by dangra** [comment]
and once again rebase please :(

**Comment by lopuhin** [comment]
@dangra done)

**Pull request merged**
