### PR TITLE
Update httpcache.py

### PR DESCRIPTION
**Pull request by Kromitvs**
Sometimes (for instance, in sites finishing in '/', without 'html' at the end) the body is necessary to correctly identify a Response type as txt. Without passing this parameter, the body can never be used for that.

To do:

- [x] `scrapy/extensions/httpcache.py:242`
- [x] `scrapy/extensions/httpcache.py:302`
- [x] `scrapy/core/downloader/handlers/ftp.py:105`
- [x] `scrapy/core/downloader/webclient.py:113`

### CODE REVIEW

**Comment by Kromitvs** [comment]
Update httpcache.py

This is how it's already done when httpcache is not called: https://github.com/scrapy/scrapy/blob/c292957cb19085137146bde72fe82639591c5e1c/scrapy/core/downloader/handlers/http11.py#L436

**Review by elacuesta — APPROVED** [review]
It'd be great if this could be tested somehow, but it seems like a fairly harmless change so I'm approving anyway.

**Comment by Gallaecio** [comment]
@Kromitvs Do you think you can add a test for this?

**Comment by Kromitvs** [comment]
line 242 seems to have the same issue `respcls = responsetypes.from_args(headers=headers, url=url)`

There are a few more places were the call doesn't include the body, like  `scrapy/core/downloader/webclient.py:112`. I don't know the code base that well to be sure.

I tested by scrapping the same site with and without cache. Are there other HttpCache tests I could get some inspiration from?

**Comment by Gallaecio** [comment]
HTTP cache tests are at https://github.com/scrapy/scrapy/blob/master/tests/test_downloadermiddleware_httpcache.py

If you find nothing there that helps figure out a way to test this, or if you are short on time, let me know; maybe I can have a stab at it.

**Comment by Kromitvs** [comment]
Hi, sorry to say, but it seems I can't find the time for now. Maybe I can help some other way or at some other time?

**Review by kmike — APPROVED** [review]
The PR looks good!

**Pull request merged**
