### PR TITLE
Update documentation for logging manually

### LINKED ISSUE #2149: logging level won't working
Using the code in the doc:

```
 logging.basicConfig(
     filename='/home/jason/scrapyd/logs/scrapy.log',
     format='%(levelname)s: %(message)s',
     level=logging.ERROR
 )
```

But in the file `scrapy.log`, I can still see `INFO` `DEBUG` etc

```
ERROR: this is an error
INFO: please
ERROR: this is an error
DEBUG: Scraped from <200 http://www.xxxx.com>
```

I did not specify any log level in my settings.py, Which part could be wrong?
Thanks

### PR DESCRIPTION
**Pull request by thernstig**
Usage of basicConfig() together with crawlerRunner is not recommended.
Update documentation to highlight this fact.

Closes #2149, #2352 and #3146

### CODE REVIEW

**Comment by thernstig** [comment]
Where are the maintainers at?

**Comment by thernstig** [comment]
@firegolem @Gallaecio are you active? There are 277 pull requests for this repo but noone looking at them.

**Comment by Gallaecio** [comment]
@thernstig This request is currently broken (conflicts with other changes merged into master since you created it). If you have time to fix the conflicts, I’ll be glad to review the changes. Thanks!

**Comment by thernstig** [comment]
Moved to #3960

**Pull request closed without merging**
