### PR TITLE
remove unnecessary CrawlSpider.from_crawler()

### PR DESCRIPTION
**Pull request by nyov**
Am I missing some reason for having this `CrawlSpider.from_crawler()` method here?
`Spider.from_crawler()` is attaching `crawler.settings` to the spider class, so I believe we can just use that here.

### CODE REVIEW

**Comment by kmike** [comment]
@nyov Spider.from_crawler attaches settings after `__init__` is called.

**Comment by nyov** [comment]
Ah. Not this again. Knew there was something :(
Thanks.

**Comment by kmike** [comment]
Yeah, this is a common gotcha; we don't have an easy way to access settings from `Spider.__init__`. Also, AFAIK it is not documented how to access settings in `Spider.__init__` (this is similar to https://github.com/scrapy/scrapy/issues/1789). From http://doc.scrapy.org/en/latest/topics/spiders.html#scrapy-spider one may get an idea that Spider.settings is always set (we don't document that it is not set in `__init__`), and that `from_crawler` method is not important (docs say *You probably won’t need to override this directly*). See also: https://github.com/scrapy/scrapy/issues/1697. It is totally not your fault.

**Comment by nyov** [comment]
@kmike: Actually can you say why that is? What's the reason for not passing `crawler` as optional kwarg to spider on instancing?

**Comment by nyov** [comment]
I mean this is a common theme to say
```py
@classmethod
def from_crawler(cls, crawler, *args, **kwargs):
    return  cls(settings=crawler.settings, *args, **kwargs)
```
in pipelines or such. I should have remembered why that was ;)

But I'm unsure why `Spider` couldn't do that by default (passing `crawler` which has `crawler.settings`)

**Comment by kmike** [comment]
I don't know, but likely that's because kwargs are used to pass spider arguments which can be set e.g. from command line; instantiated Crawler object is not such argument. User spiders may be written without **kwargs, so they may not handle extra arguments. It may be too late to change Spider API; I'm not sure. 

But we may have a second chance designing Spider API: existing Spider API is not compatible with asyncio (see https://github.com/scrapy/scrapy/issues/1144#issuecomment-141843616), so if we want to support Python 3.5 and `async def` callbacks we'll need another Spider base class (or entirely different API).

**Comment by nyov** [comment]
Okay this helped me. Thank you!
And interesting note about pep 492.

**Pull request closed without merging**
