### PR TITLE
  Added --overwrite-output (-O) option

### LINKED ISSUE #547: Add a command-line option for overwriting exported file
What do you think about adding an option to overwrite/recreate exported file?
Something like 

```
$ scrapy crawl myspider -o data.jl --overwrite
```

or 

```
$ scrapy crawl myspider -O data.jl
```

This is useful during development where old data is not needed. I usually run 

```
$ rm data.jl; scrapy crawl myspider -o data.jl
```

multiple times. This is not DRY: if I want to change file name for the next iteration and preserve existing file then I must be careful and update both names (of course, the command comes from shell autocompletion).

### PR DESCRIPTION
**Pull request by yhager**
How about this for #547? This is my first time writing code for scrapy, so please scrutinize.

Fixes #547

### CODE REVIEW

**Comment by kmike** [comment]
In the overview page (even after https://github.com/scrapy/scrapy/pull/1023) there is a gotcha: `-o scraped_data.json` will produce invaid JSON if called second time. We won't have to document this wart in the tutorial if this issue is fixed. So this feature is nice to have in Scrapy 1.0. 

This PR looks like a good start. I think after addressing @nramirezuy's comments and rebasing on master it can be merged.

//cc @pablohoffman @Curita @dangra

**Comment by abenassi** [comment]
Hi people, what's the status of this PR? I'm very interested in having this feature :-)

**Comment by kmike** [comment]
@abenassi yeah, that's a really nice feature. The PR needs a rebase. Another problem is that it changes IFeedStorage interface in a backwards-incompatible way; it'd be better to find a way to avoid doing that. There is also https://github.com/scrapy/scrapy/pull/1605, maybe it makes sense to finish it first. Help is appreciated - code review, suggestions, pull requests, rebasing existing pull requests :)

**Comment by abenassi** [comment]
sure @kmike I'd be interested in taking a look at Scrapy code to contribute! Although I'm new at it and I'll have to dive some time to understand how is the discussion going

**Comment by Gallaecio** [comment]
It’s been a while, and rebasing may prove not that different from writing it from scratch once #3858 is merged. Shall we close?

**Comment by yhager** [comment]
I'm sorry but I am not using scrapy anymore, so don't have time/interest in rewriting this. Please someone else take over this, or you can close it as far as I'm concerned. Thanks!

**Comment by Gallaecio** [comment]
I’ll continue the work myself once #3858 is merged.

**Pull request closed without merging**
