### PR TITLE
Code example in tutorial omits return

### PR DESCRIPTION
**Pull request by MalikRumi**
https://doc.scrapy.org/en/latest/intro/tutorial.html#extracting-data-in-our-spider

Following this script verbatim results in a NoneType error. The lack of a return on start_requests (which was present in the earlier version of this script in the first part of the tutorial) means the response.css variable is empty, thus, a NoneType error. Somewhere along the line I guess that part got dropped accidentally. It should read:

    import scrapy

    class QuotesSpider(scrapy.Spider):
        name = "quotes"

        def start_requests(self):
            urls = [
                'http://quotes.toscrape.com/page/1/',
                'http://quotes.toscrape.com/page/2/',
            ]
        
            for url in urls:
                yield scrapy.Request(url=url, callback=self.parse)
        
        def parse(self, response):
            for quote in response.css('div.quote'):
                yield {
                    'text': quote.css('span.text::text').extract_first(),
                    'author': quote.css('small.author::text').extract_first(),
                    'tags': quote.css('div.tags a.tag::text').extract(),
                }

### CODE REVIEW

**Comment by kmike** [comment]
Hey @MalikRumi,

Something went wrong with your PR - could you please check it? There are no your commits in the pull request; you're only proposing to merge master to 1.3 which we won't do. 

The example you linked to doesn't use start_requests, and it looks correct. Could you please clarify what's the problem?

**Comment by MalikRumi** [comment]
There are three versions of the 'quotes' spider in the tutorial. The first
one has these lines:

  for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

The second does not, and has this language in the text:

*The parse() <https://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.parse>
method will be called to handle each
of the requests for those URLs, even though we haven’t explicitly told Scrapy
to do so. This happens because parse()
<https://doc.scrapy.org/en/latest/topics/spiders.html#scrapy.spiders.Spider.parse>
is Scrapy’s
default callback method, which is called for requests without an explicitly
assigned callback.*

The third version has parse() with a yield that produces a dict, but
no return or yield from starts_requests, which is missing altogether
from both this and the second one.

I get that parse() is supposed to be the default, and should run
without a callback, but it does not, or at least, did not for me:

Unhandled error in Deferred:
2017-02-27 01:27:20 [twisted] CRITICAL: Unhandled error in Deferred:


Traceback (most recent call last):
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/scrapy/commands/crawl.py",
line 57, in run
    self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/scrapy/crawler.py",
line 163, in crawl

    return self._crawl(crawler, *args, **kwargs)

  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/scrapy/crawler.py",
line 167, in _crawl
    d = crawler.crawl(*args, **kwargs)
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/twisted/internet/defer.py",
line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/twisted/internet/defer.py",
line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/scrapy/crawler.py",
line 73, in crawl
    start_requests = iter(self.spider.start_requests())
builtins.TypeError: 'NoneType' object is not iterable
2017-02-27 01:27:20 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/twisted/internet/defer.py",
line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/home/malikarumi/Projects/aishah/lib/python3.5/site-packages/scrapy/crawler.py",
line 73, in crawl
    start_requests = iter(self.spider.start_requests())
TypeError: 'NoneType' object is not iterable

When I put the callback line back into the third version explicitly:

 for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

This code ran as expected without errors.

**Comment by kmike** [comment]
Sorry, I can't reproduce this. I just created a project and copy-pasted last two example spiders, they work for me. Are you sure the spiders you've tried are exactly the same as in the tutorial? 

That's fine not to have start_requests defined - this is what start_urls shortcut for.

**Comment by redapple** [comment]
I also cannot reproduce this:

```
$ cat t.py 
import scrapy


class QuotesSpider(scrapy.Spider):
    name = "quotes"
    start_urls = [
        'http://quotes.toscrape.com/page/1/',
        'http://quotes.toscrape.com/page/2/',
    ]

    def parse(self, response):
        for quote in response.css('div.quote'):
            yield {
                'text': quote.css('span.text::text').extract_first(),
                'author': quote.css('small.author::text').extract_first(),
                'tags': quote.css('div.tags a.tag::text').extract(),
            }

$ scrapy runspider t.py
2017-02-28 12:00:46 [scrapy.utils.log] INFO: Scrapy 1.3.2 started (bot: scrapybot)
2017-02-28 12:00:46 [scrapy.utils.log] INFO: Overridden settings: {}
2017-02-28 12:00:46 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-02-28 12:00:46 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-02-28 12:00:46 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-02-28 12:00:46 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-02-28 12:00:46 [scrapy.core.engine] INFO: Spider opened
2017-02-28 12:00:46 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-02-28 12:00:46 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-02-28 12:00:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://quotes.toscrape.com/page/2/> (referer: None)
2017-02-28 12:00:46 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://quotes.toscrape.com/page/1/> (referer: None)
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u"\u201cThis life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.\u201d", 'tags': [u'friends', u'heartbreak', u'inspirational', u'life', u'love', u'sisters'], 'author': u'Marilyn Monroe'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u'\u201cIt takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.\u201d', 'tags': [u'courage', u'friends'], 'author': u'J.K. Rowling'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u"\u201cIf you can't explain it to a six year old, you don't understand it yourself.\u201d", 'tags': [u'simplicity', u'understand'], 'author': u'Albert Einstein'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u"\u201cYou may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect\u2014you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break\u2014her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.\u201d", 'tags': [u'love'], 'author': u'Bob Marley'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u'\u201cI like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.\u201d', 'tags': [u'fantasy'], 'author': u'Dr. Seuss'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cThe world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\u201d', 'tags': [u'change', u'deep-thoughts', u'thinking', u'world'], 'author': u'Albert Einstein'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cIt is our choices, Harry, that show what we truly are, far more than our abilities.\u201d', 'tags': [u'abilities', u'choices'], 'author': u'J.K. Rowling'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cThere are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.\u201d', 'tags': [u'inspirational', u'life', u'live', u'miracle', u'miracles'], 'author': u'Albert Einstein'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u'\u201cI may not have gone where I intended to go, but I think I have ended up where I needed to be.\u201d', 'tags': [u'life', u'navigation'], 'author': u'Douglas Adams'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u"\u201cThe opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.\u201d", 'tags': [u'activism', u'apathy', u'hate', u'indifference', u'inspirational', u'love', u'opposite', u'philosophy'], 'author': u'Elie Wiesel'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u'\u201cIt is not a lack of love, but a lack of friendship that makes unhappy marriages.\u201d', 'tags': [u'friendship', u'lack-of-friendship', u'lack-of-love', u'love', u'marriage', u'unhappy-marriage'], 'author': u'Friedrich Nietzsche'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cThe person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.\u201d', 'tags': [u'aliteracy', u'books', u'classic', u'humor'], 'author': u'Jane Austen'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u"\u201cImperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\u201d", 'tags': [u'be-yourself', u'inspirational'], 'author': u'Marilyn Monroe'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cTry not to become a man of success. Rather become a man of value.\u201d', 'tags': [u'adulthood', u'success', u'value'], 'author': u'Albert Einstein'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cIt is better to be hated for what you are than to be loved for what you are not.\u201d', 'tags': [u'life', u'love'], 'author': u'Andr\xe9 Gide'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u"\u201cI have not failed. I've just found 10,000 ways that won't work.\u201d", 'tags': [u'edison', u'failure', u'inspirational', u'paraphrased'], 'author': u'Thomas A. Edison'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u'\u201cGood friends, good books, and a sleepy conscience: this is the ideal life.\u201d', 'tags': [u'books', u'contentment', u'friends', u'friendship', u'life'], 'author': u'Mark Twain'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/2/>
{'text': u'\u201cLife is what happens to us while we are making other plans.\u201d', 'tags': [u'fate', u'life', u'misattributed-john-lennon', u'planning', u'plans'], 'author': u'Allen Saunders'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u"\u201cA woman is like a tea bag; you never know how strong it is until it's in hot water.\u201d", 'tags': [u'misattributed-eleanor-roosevelt'], 'author': u'Eleanor Roosevelt'}
2017-02-28 12:00:46 [scrapy.core.scraper] DEBUG: Scraped from <200 http://quotes.toscrape.com/page/1/>
{'text': u'\u201cA day without sunshine is like, you know, night.\u201d', 'tags': [u'humor', u'obvious', u'simile'], 'author': u'Steve Martin'}
2017-02-28 12:00:46 [scrapy.core.engine] INFO: Closing spider (finished)
2017-02-28 12:00:46 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 448,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 5607,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 2,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 2, 28, 11, 0, 46, 743834),
 'item_scraped_count': 20,
 'log_count/DEBUG': 23,
 'log_count/INFO': 7,
 'response_received_count': 2,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'start_time': datetime.datetime(2017, 2, 28, 11, 0, 46, 260111)}
2017-02-28 12:00:46 [scrapy.core.engine] INFO: Spider closed (finished)
```

[As @kmike commented earlier](https://github.com/scrapy/scrapy/pull/2598#issuecomment-282684243), there's something weird about this PR that is triggerring Travis CI builds for nothing (duplicate builds for the master branch).
So I'm closing this PR as it is.

@MalikRumi , if you can re-check the tutorial and clarify what is the issue you are facing, please open a new issue. We may be missing something here.

**Comment by MalikRumi** [comment]
Ok, sorry to be late getting back to you all. Yes, I will try again and see
what might be different or causing an issue for me and report back. BTW, I
am on Ubuntu 16.04, Python 3.5.2 and Scrapy 1.2.1 And I am not the only one
having similar issues.

http://stackoverflow.com/questions/42059084/scrapy-code-throws-typeerror-nonetype-object-is-not-iterable

**Comment by kmike** [comment]
@MalikRumi there is an accepted answer for stackoverflow question; code in the question was not correct, it is not the same as in the tutorial.

**Comment by MalikRumi** [comment]
I've rerun this. It works as advertised. I have no idea what happened the
first time because over wrote it when I re-wrote it. Sorry to bother you.

**Comment by kmike** [comment]
@MalikRumi don't worry, and good luck with your scraping journey!

**Pull request closed without merging**
