### PR TITLE
Add overview to release notes and other edits

### PR DESCRIPTION
**Pull request by stummjr**
Hey, @eliasdorneles and me went through the release notes and did some editing.

Does it look good?

### CODE REVIEW

**Comment by eliasdorneles** [comment]
:+1:

**Comment by redapple** [comment]
Looks pretty good! well done @eliasdorneles and @stummjr 

I'm not sure `Extracted CrawlerRunner._crawl method` is worth mentioning now that I read it with everything.

**Comment by eliasdorneles** [comment]
Yeah, we weren't sure either, because it's meant to be a "private" method, so we just cut the details and mentioned it briefly.

**Comment by redapple** [comment]
makes sense

**Pull request merged**
