### PR TITLE
[WIP] Test against Twisted 16.7.0rc1

### PR DESCRIPTION
**Pull request by redapple**
Issues found:

- #2461 (patched with https://github.com/redapple/scrapy/commit/bccf38d5cac0898dc2e63407c9ea6e646c3cf4ed)

### CODE REVIEW

**Comment by redapple** [comment]
Alright, so the trouble seems to _only_ be around name resolution.

When skipping the install of Scrapy's custom caching name resolver (https://github.com/scrapy/scrapy/pull/2480/commits/dcea9b78b93dec7783a937177b3e83dab50d0040), and therefore using Twisted's [new `HostnameEndpoint`](https://github.com/twisted/twisted/pull/624)-based name resolution, all  tests pass, except for a DNS retry test (`CrawlTestCase.test_retry_dns_error`, which mocks `socket.gethostbyname`, not used in the new default Twisted name resolution)

**Comment by glyph** [comment]
I'm assuming that scrapy has a caching resolver for performance reasons?  I suspect that Twisted should add something similar to the core.

Twisted trunk should now have a thing which un-breaks scrapy if it installs its own resolver, though; fixed here: https://github.com/twisted/twisted/commit/88a71947b41af21065f7fdfa56a3ffe22a7f5c57

**Comment by redapple** [comment]
Twisted 16.7 RC1 was abandoned

**Comment by glyph** [comment]
Is there a new PR for 17.1 (which is now available in prerelease)?

**Comment by redapple** [comment]
@glyph , yes there is: https://github.com/scrapy/scrapy/pull/2521

**Pull request closed without merging**
