### PR TITLE
Contribute to master branch

### PR DESCRIPTION
**Pull request by dangra**
ref #975 

:cake:

### CODE REVIEW

**Comment by nramirezuy** [comment]
can you add test plz :goat:

**Comment by dangra** [comment]
@nramirezuy good one :dancers:

**Comment by kmike** [comment]
I think this link should be added to http://doc.scrapy.org/en/master/contributing.html as well.

**Comment by kmike** [comment]
yeah, and it misses docs and tests

**Comment by nramirezuy** [comment]
@kmike you comment is missing an icon :sheep:

**Comment by kmike** [comment]
:cow2: :cow2: :cow2: 

My first comment was serious, by the way.

**Comment by dangra** [comment]
please :goat:'s in the room, send your feedback about  https://github.com/scrapy/scrapy/commit/f0bdc14522aac0b7e52a1409847e7d57530d56ba

**Comment by kmike** [comment]
Looks :goat: to me.

**Comment by dangra** [comment]
> Looks :goat: to me.

:laughing:

**Comment by rocioar** [comment]
:camel: :camel: :camel: :camel: 

I just wanted to participate in the important discussion.

**Comment by barraponto** [comment]
shouldn't it be http://doc.scrapy.org/en/latest/contributing.html :snail: ?

**Comment by kmike** [comment]
@barraponto no, the point of this PR was to change "latest" to "master" :) In RTFD "latest" points to docs for the latest Scrapy released version, "master" points to docs for the latest commit in master branch. When contributing, users should use latest master; instructions in latest stable release could be already  outdated (this is what happened in https://github.com/scrapy/scrapy/issues/975).

Here is some food for your pet snail: :leaves:.

**Comment by barraponto** [comment]
thanks for the explanation! have some :cake:

**Pull request merged**
