### PR TITLE
Use pprint.pformat on versions log message

### PR DESCRIPTION
**Pull request by grammy-jiang**
This commit use pprint.pformat on overridden settings to keep consistent
with scrapy.middleware, for example:
Original:
```
2019-12-01 11:35:40 [scrapy.utils.log] INFO: Versions: lxml 4.3.4.0, libxml2 2.9.9, cssselect 1.0.3, parsel 1.5.1, w3lib 1.20.0, Twisted 19.2.1, Python 3.7.5 (default, Oct 17 2019, 12:16:48) - [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1c  28 May 2019), cryptography 2.7, Platform Linux-5.3.7-301.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
```
Now:
```
2019-12-01 11:04:22 [scrapy.utils.log] INFO: Versions:
{'Platform': 'Linux-5.3.7-301.fc31.x86_64-x86_64-with-fedora-31-Thirty_One',
 'Python': '3.7.5 (default, Oct 17 2019, 12:16:48) - [GCC 9.2.1 20190827 (Red '
           'Hat 9.2.1-1)]',
 'Twisted': '19.2.1',
 'cryptography': '2.7',
 'cssselect': '1.0.3',
 'libxml2': '2.9.9',
 'lxml': '4.3.4.0',
 'parsel': '1.5.1',
 'pyOpenSSL': '19.0.0 (OpenSSL 1.1.1c  28 May 2019)',
 'w3lib': '1.20.0'}
```

### CODE REVIEW

**Comment by wRAR** [comment]
As seen in the provided example, this changes the order of components.

`scrapy_components_versions()` returns a list of tuples while the code creates a dict. Can you please fix this, maybe OrderedDict will help?

**Comment by grammy-jiang** [comment]
> As seen in the provided example, this changes the order of components.
> 
> `scrapy_components_versions()` returns a list of tuples while the code creates a dict. Can you please fix this, maybe OrderedDict will help?

The order is changed by the pprint module, and disable the sorted function inside pprint is only available in Python 3.8.

And with the help of OrderedDict, the output is like this:
```
2019-12-03 09:13:05 [scrapy.utils.log] INFO: Versions:
OrderedDict([('lxml', '4.4.2.0'),
             ('libxml2', '2.9.9'),
             ('cssselect', '1.1.0'),
             ('parsel', '1.5.2'),
             ('w3lib', '1.21.0'),
             ('Twisted', '19.10.0'),
             ('Python', '3.7.5 (default, Nov 27 2019, 16:53:22) - [GCC 7.4.0]'),
             ('pyOpenSSL', '18.0.0 (OpenSSL 1.1.0i  14 Aug 2018)'),
             ('cryptography', '2.3.1'),
             ('Platform',
              'Linux-5.0.0-36-generic-x86_64-with-debian-buster-sid')])
```
Emmm, which looks strange.

**Comment by Gallaecio** [comment]
We could write a private function just to print the desired output format from this input data.

It think it’s either that or wait until we drop support for CPython 3.5.

**Comment by grammy-jiang** [comment]
Consider nobody raises an issue with this output format, I think we should not do too much work just for this.

**Comment by wRAR** [comment]
3.7 is almost EOL so we can now use `sort_dicts=False`.

**Pull request closed without merging**
