### PR TITLE
[WIP] Conda recipe

### PR DESCRIPTION
**Pull request by darkrho**
This PR adds a default [Conda Recipe](http://conda.pydata.org/docs/build.html) to build Scrapy using the command `conda build` provided by the [Conda](http://conda.pydata.org/docs/) package management system, which is available by installing either [Miniconda](http://conda.pydata.org/miniconda.html) or [Anaconda](https://store.continuum.io/cshop/anaconda/).

This recipe is a very simple one without much tweaks, but I don't think it's ready for merge because we need to address the following major issues:

1. we need to read the version automatically from `scrapy/VERSION` file;
2. [parsel](https://github.com/scrapy/parsel) and  [PyDispatcher](http://pydispatcher.sourceforge.net) are not available through conda;
3. [service_identity](https://github.com/pyca/service_identity) and its dependencies (`pyasn1`, `pyasn1-modules`, `characteristic`) is not available through conda.

The point 1. can be solved by automatically generating the `meta.yaml` specification file, it would help also to update automatically the build, install and tests dependencies from the files `setup.py` and `requirements-tests.txt`.

The point 2. can be solved by adding a conda recipe to the `parsel` project and providing one for `pydispatcher`.

The point 3. is more tricky because these are many packages. Perhaps it will be better to make a PR to [conda-recipes](https://github.com/conda/conda-recipes) and expect it gets merged soon enough so that these packages are officially available through conda. However, we could also provide third-party recipes and publish the packages in the channel provided by Scrapinghub for this matter. In this way we have better control about the versions published. I'm not sure how necessary is this for `service_identity`'s related dependencies, though.

I appreciate any comment.

PD: I uploaded test packages built with this recipe to my channel https://anaconda.org/rolando/scrapy and can be installed by running `conda install -c rolando scrapy==1.1.0dev1` (only platforms `linux-64` and `osx-64` are available for now).

### CODE REVIEW

**Comment by dangra** [comment]
By the amount of [pending PRs in conda-recipes](https://github.com/conda/conda-recipes/pulls) my opinion is that we should packages all missing dependencies and publish them on scrapinghub channel.

But instead of adding a recipe to each repository plus creating another one for external dependencies, just take the conda-recipes approach and create a single repository to track all the conda packages we publish to Scrapinghub channel.

It means this PR is not for Scrapy repo but for another new repo (if you agree I can create it), also, we biuld conda packages from published versions on PyPi and that includes Scrapy itself.

I like this approach because it resolve all your points in a single manner and when our recipes are mature enough we propose them to be merged into conda-recipes.

what do you think?

**Comment by darkrho** [comment]
@dangra sounds good to me. Please go ahead and create the repository.

**Comment by dangra** [comment]
@darkrho https://github.com/scrapinghub/scrapinghub-conda-recipes

**Comment by dangra** [comment]
moved to scrapinghub/scrapinghub-conda-recipes#1

**Pull request closed without merging**
