### PR TITLE
Closes #6343. Make certain args of ScrapyAgent and TunnelingAgent required

### LINKED ISSUE #6343: Make certain args of `ScrapyAgent` and `TunnelingAgent` required
`scrapy.core.downloader.handlers.http11.ScrapyAgent` and `scrapy.core.downloader.handlers.http11.TunnelingAgent` take some args (`contextFactory` in both and `crawler` in `ScrapyAgent`) that are currently declared optional but in fact need to be passed as the code assumes they aren't None. So ideally they should be declared as required (but that requires reordering args and/or making all args of those constructors keyword-only so there is no clear and simple fix).

### PR DESCRIPTION
**Pull request by kumar-sanchay**
Fixes #6343

### CODE REVIEW

**Comment by wRAR** [comment]
The asserts are no longer needed.

**Comment by kumar-sanchay** [comment]
> The asserts are no longer needed.

Ok, i was thinking what if we pass None to those keyword arguments??

**Comment by kumar-sanchay** [comment]
> The asserts are no longer needed.

Done

**Comment by wRAR** [comment]
The asserts were there for typing purposes, to show that the args can't be None normally. If None is passed there will be a normal TypeError or something like that.

**Comment by kumar-sanchay** [comment]
@Gallaecio @wRAR let me know if anything got missed here :)

**Comment by wRAR** [comment]
As I said in the issue this is technically backwards-incompatible but only breaks the code that calls the constructors with all these args without using their names, which is unlikely (I took a quick look at the GH code search and didn't find such code).

**Review by wRAR — APPROVED** [review]

**Comment by Gallaecio** [comment]
Thanks!

**Pull request merged**
