### PR TITLE
Fix deprecated twisted import

### LINKED ISSUE #6450: Twisted 24.7.0rc1 deprecation: "twisted.web.http.HTTPClient was deprecated in Twisted 24.7.0rc1: Use twisted.web.client.Agent instead"
## Summary

Twisted 24.7.0rc1 deprecates twisted.web.http.HTTPClient. Use twisted.web.client.Agent instead.

## Motivation

To avoid deprecation warnings.

## Describe alternatives you've considered

N/A

## Additional context

N/A

### PR DESCRIPTION
**Pull request by LucasSD**
Fixes #6450

### CODE REVIEW

**Comment by wRAR** [comment]
Did you test this in at least some way?

**Comment by LucasSD** [comment]
> Did you test this in at least some way?

Hi, yes, lots of tests fail and I’m still working on it. I’ll let you know if I get it working 👍 

Please let me know if you have any specific requirements or suggestions

**Comment by wRAR** [comment]
> Hi, yes, lots of tests fail and I’m still working on it.

(I've meant locally, before submitting the PR)

> Please let me know if you have any specific requirements or suggestions

Nothing specific, just make sure your chanbges actually work before submitting them.

**Comment by LucasSD** [comment]
Yes I ran the tests locally but neglected to set this as a draft PR, which caused the confusion. Apologies, and thanks for changing that!

**Comment by LucasSD** [comment]
Closing as this requires significantly more work than I anticipated.

**Pull request closed without merging**
