### PR TITLE
don't run tests twice on Travis if a PR is made from a scrapy/scrapy branch

### PR DESCRIPTION
**Pull request by kmike**
Currently if a PR is open from a branch in main repo tests run twice.

If this PR is merged we'll have to add each new release branch to travis.yml. 
We can also add them all now? 1.0, 1.1, 1.2, etc.

### CODE REVIEW

**Comment by dangra** [comment]
+1 add them now including 2.0 :dragon_face:

**Comment by kmike** [comment]
@dangra better?

**Comment by dangra** [comment]
does it work? that's perfect

**Comment by dangra** [comment]
it does for this PR so I'm merging

**Comment by kmike** [comment]
> does it work?

I don't know :) Docs are here: http://docs.travis-ci.com/user/customizing-the-build/#Using-regular-expressions

**Pull request merged**
