### PR TITLE
Remove deprecated SgmlLinkExtractor and RegexLinkExtractor

### PR DESCRIPTION
**Pull request by ashellunts**
BaseSgmlLinkExtractor is also removed.

Issue #4356

### CODE REVIEW

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/blob/master/scrapy/linkextractors/regex.py#L7

**Comment by ashellunts** [comment]
@Gallaecio could you please advise how to proceed? Is RegexLinkExtractor still needed?
If yes, why is it subclass of class SgmlLinkExtractor? What methods from SgmlLinkExtractor should be available in RegexLinkExtractor?

**Comment by wRAR** [comment]
Yeah, this is strange, as `__init__` is not overridden you will have a deprecation warning about `SgmlLinkExtractor` when instantiating `RegexLinkExtractor`.

OTOH, I just tried this and found `scrapy.linkextractors.sgml` imports `sgmllib` which is py2-only so this code just doesn't work anymore.

**Comment by Gallaecio** [comment]
In that case, maybe we should remove `regex.py` as well? No one must be using it in Python 3 if this is the first time we hear about it.

**Comment by wRAR** [comment]
Yeah, I almost suggested that too. We are usually very careful when removing things, but this class should have shown a deprecation warning anyway.

**Comment by ashellunts** [comment]
Ok, thank you for answers. Will update PR.

**Comment by ashellunts** [comment]
Shall I relpace RegexLinkExtractor to just LinkExtractor in these docs?

```
./sep/sep-016.rst:       legs = [RegexLinkExtractor(), ParseRules(), CanonicalizeUrl(), ItemIdSetter()]
./sep/sep-018.rst:       middlewares = [RegexLinkExtractor(), CallbackRules(), CanonicalizeUrl(), 
```

**Comment by wRAR** [comment]
/sep/ is historical so it shouldn't be changed.

I see there are conflicts, can you please resolve them?

**Comment by ashellunts** [comment]
> /sep/ is historical so it shouldn't be changed.
> 
> I see there are conflicts, can you please resolve them?

Done.

**Comment by ashellunts** [comment]
[Build](https://travis-ci.org/github/scrapy/scrapy/builds/708759191) in travis is green. But github still shows it as "in progress". 🤔

**Comment by ashellunts** [comment]
Ok, link goes to last successful build in Travis. But build for latest commit is not yet started.

**Comment by ashellunts** [comment]
Looks like travis doesn't recognize force push.

**Comment by dangra** [comment]
Now it is :green_apple: (I've restarted one build to trigger the update on this PR)

**Comment by ashellunts** [comment]
Thank you @dangra.

**Comment by ashellunts** [comment]
🎉🎉🎉

**Comment by Gallaecio** [comment]
Thank you!

**Pull request merged**
