### PR TITLE
added setting DISABLE_TOPLEVELFORMATTER and logic

### PR DESCRIPTION
**Pull request by ror6ax**
Adresses #1309. 
First commit to this project, excuse me if I missed any styling conventions you guys use.

### CODE REVIEW

**Comment by redapple** [comment]
@ror6ax , thanks for reminding us of this!
In fact, there's an open PR for this issue, using `LOG_SHORT_NAMES`
https://github.com/scrapy/scrapy/pull/1731 (rebased from https://github.com/scrapy/scrapy/pull/1583)

If you don't mind, I'd suggest you contribute to that PR instead, which is missing tests and docs.
Would that work for you?

**Comment by ror6ax** [comment]
Sure, no problem. I'd like to stick around and contribute more to Scrapy. Can you recommend any particular issues that you need looked at?

**Comment by redapple** [comment]
@ror6ax , sorry for the late comment. Seems like I missed it.
There are a few about the switch to python logging that nobody looked into in detail: 
https://github.com/scrapy/scrapy/issues/1646
https://github.com/scrapy/scrapy/issues/1609

**Comment by kmike** [comment]
Hey @ror6ax,

Thanks for the PR! I think your fix was correct; you also noticed that settings are ordered alphabetically and put the option in a right place 👍 However, we've decided option name should be LOG_SHORT_NAMES; also, this feature needs docs and tests. So I'm closing this PR in favor of https://github.com/scrapy/scrapy/pull/1731.

**Pull request closed without merging**
