### PR TITLE
allow additon of objects instead of paths to settings

### PR DESCRIPTION
**Pull request by youzhonghui**
Make this available:

```python
class CustomHttpProxyMiddleware(object):
    ...

def main():
    settings = Settings({
        DOWNLOADER_MIDDLEWARES{
            CustomHttpProxyMiddleware: 400    #! Here
        }
    })
    crawler = CrawlerProcess(settings)
    crawler.crawl(spider)
    crawler.start()
```

### CODE REVIEW

**Comment by kmike** [comment]
+1 to this feature :+1: 

See also: https://github.com/scrapy/scrapy/pull/1032. I think it makes more sense to fix it in load_object - this way it'll become possible to set other settings to Python classes as well.

To merge a PR we also need some tests.

**Comment by dangra** [comment]
+1 and I also think load_object is the proper place for it.

**Comment by Curita** [comment]
+1 for changing it in load_object too

**Comment by jdemaeyer** [comment]
+1 prerequisite for #1272 (currently)

Makes sense to put into `load_object` when class objects are handed over. Can we also allow passing already-instantiated objects?

**Comment by jdemaeyer** [comment]
Implemented in `load_object()` as part of #1272

**Comment by kmike** [comment]
See also: https://github.com/scrapy/scrapy/issues/1325. How can we avoid it?

**Comment by jdemaeyer** [comment]
Hm, do I see it correctly that the error in #1325 comes from deep-copying an object that works with threads (in that case a database connection)? I would think that's "not really our problem". We could remind users to follow sane design and not start connections before they need them (i.e. opening connections belongs into `open_spider()`!)
On a side note, I know it doesn't solve the underlying problem, why does `_get_spider_loader()` receive a frozen copy of the settings? It's not like the (original) settings aren't updated afterwards.

**Comment by barraponto** [comment]
Isn't spider.custom_settings enough for this case?

**Comment by jdemaeyer** [comment]
@barraponto: It's not about from where we update `DOWNLOADER_MIDDLEWARES` (and similar), but about what what we can put in there. `Spider.custom_settings` allows us to set some middlewares paths (!) on a per-spider basis, but it doesn't allow us to pass a class/object instead of a string.

**Comment by barraponto** [comment]
@jdemaeyer oh. can we have a better issue title, then?

**Comment by nramirezuy** [comment]
@barraponto better now?

**Comment by jdemaeyer** [comment]
Also see [this commit](https://github.com/jdemaeyer/scrapy/commit/7fca7b59b87f9700a2ccb1cd7a2ade60497605f3)

**Comment by nramirezuy** [comment]
@jdemaeyer What are we supposed to look at? Passing instances instead of classes?

**Comment by jdemaeyer** [comment]
Passing Python objects instead of strings (even passing classes in the
literal sense wasn't possible before, only passing strings representing
class paths)

There's an example using this in the "Example add-ons" section in a later
commit (I'm on mobile and can't get a link to that right now, sorry)

**Comment by jdemaeyer** [comment]
Sorry, I hadn't realised (on mobile) that I was replying to *this* PR.

What I meant by "also see this commit" was "here's another implementation". The difference between this PR and the commit linked to is that a) as you said, it allows passing instances and not just classes, and b) the "don't try to load non-string values" part lives in `load_object()`

**Comment by kmike** [comment]
My reservation for passing instances (not classes) is that many (most?) Scrapy components are tied to a crawler, and they can use a wrong crawler if a shared instance is used. Classes doesn't have these problem.

What's the use case for passing instantiated objects?

**Comment by nramirezuy** [comment]
@kmike I guess the use case can be that one; a component not tied to a crawler. But this is usable for "`lib` `mode`".

**Comment by jdemaeyer** [comment]
> What's the use case for passing instantiated objects?

Using the same class twice, with different settings, e.g. writing to two different databases through the same class. (Providing the two different settings and instantiating is than another question, but will become easy through the add-on framework.)

I can see that there might be troubles when objects are bound to a crawler (as in "initiated via `from_crawler()`, or is there another way they're tied to a crawler I'm missing right now?). At least for the add-on framework that wouldn't pose a problem, as settings can only be updated *before* add-ons receive access to a crawler object.

**Comment by kmike** [comment]
@jdemaeyer sorry, I don't quite get it. So is passing an instance a workaround for having classes/class paths as dict keys in various Scrapy settings?

**Comment by jdemaeyer** [comment]
Hmm, say you have a pipeline that writes items to a file, and takes the filename as constructor argument:

```python
class FilePipeline(object):
    def __init__(self, filename):
        # Save filename
    # open_spider(): opens a file,
    # process_item(): writes to it, and
    # close_spider(): closes the file
```

Being able to pass instances, not classes, into the component settings allows you to reuse this code for writing to two different files:

```python
# in settings.py, or set from an add-on callback
ITEM_PIPELINES = {
    FilePipeline('all_items.txt'): 0,
    # some
    # filter
    # pipelines
    # here
    FilePipeline('important_items.txt'): 100,
}
```

Another advantage, in conjunction with the add-on framework, is that you can keep settings out of the global settings namespace by passing them directly to the component constructor, instead of saving them to the settings and then reading them back in the component.

**Comment by kmike** [comment]
Thanks, I see, it makes sense. Just checked built-in Scrapy components, and from_crawler usage is not as widespread as I expected. 

But still, most of Scrapy built-in extensions, all builtin pipelines and some of the downloader middlewares won't work if used this way, they need and use a crawler. Built-in spider middlewares are almost ok. It should be also possible to make builtin pipelines work.

I think we need some sort of protection for built-in components, or at least some docs on what works and what doesn't work.

That said, with 

```python
ITEM_PIPELINES = [
    ('FilePipeline', {'path': 'all_items.txt'}, 0),
    ('FilePipeline', {'path': 'important_items.txt'}, 100)
]
```
or similar syntax it'd be possible to have multiple instances of the same component even if it uses crawler. I'm not proposing to switch to this syntax though :)

**Comment by nramirezuy** [comment]
@jdemaeyer  I don't know how much do I like that feature; since those components will have limited access. Those wont be able to connect to `signals` or write `stats` for example.

**Comment by jdemaeyer** [comment]
I see your concerns. Passing instances is aimed at add-on developers who insert their self-written components into Scrapy in their add-on callbacks, and who have reasons to not just insert a class or a class path. These should know what they're doing and that they cannot use the `from_crawler()` or `from_settings()` constructors if they go this way. It's not meant to replace passing class paths in `settings.py`, and certainly not meant for usage with the built-in components.

(I'm sorry that I keep tracing back everything to the add-on framework, it's just that that's why I implemented the instance-passing behaviour, and that's what I've been working on the last three months ;))

Maybe we could restore access to the crawler for these components (avoiding the spider hack) by adding
```
mw.crawler = crawler
# possibly also:
# mw.settings = crawler.settings
```
after [this line](https://github.com/jdemaeyer/scrapy/commit/7fca7b59b87f9700a2ccb1cd7a2ade60497605f3#diff-44cb97c7f8ba235ce430be6566670bbdR35)?

**Pull request closed without merging**
