### PR TITLE
[WIP] Add Ubuntu Trusty (14.04 LTS) env for tox + Travis CI

### PR DESCRIPTION
**Pull request by redapple**
Packages versions from http://packages.ubuntu.com/trusty/allpackages

### CODE REVIEW

**Comment by redapple** [comment]
@lopuhin , do you know what minimal `botocore` version is needed for scrapy?
I added a `trusty` env here and I'm getting on Travis

```
self = <scrapy.pipelines.files.S3FilesStore object at 0x7fc88b79b490>
uri = 's3://example/images/'
    def __init__(self, uri):
        self.is_botocore = is_botocore()
        if self.is_botocore:
            import botocore.session
            session = botocore.session.get_session()
>           self.s3_client = session.create_client(
                's3', aws_access_key_id=self.AWS_ACCESS_KEY_ID,
                aws_secret_access_key=self.AWS_SECRET_ACCESS_KEY)
E           AttributeError: 'Session' object has no attribute 'create_client'
```

`trusty`is using quite [an old `botocore` (0.29)](http://packages.ubuntu.com/fr/trusty/python-botocore)

**Comment by redapple** [comment]
Looks like at least 0.66 is required to be safe (https://botocore.readthedocs.org/en/latest/client_upgrades.html#client-upgrades)

**Comment by lopuhin** [comment]
Yes, looks like 0.66 is required, but I can add support for 0.29 too - there is not too much botocore code at the moment. Or we can add the version check at the place where we check for boto/botocore.

**Comment by redapple** [comment]
We decided for Debian "Jessie" as the new baseline (https://github.com/scrapy/scrapy/pull/2212)

**Pull request closed without merging**
