### PR TITLE
[MRG+1] Change the content

### PR DESCRIPTION
**Pull request by donhuvy**
Change the content

### CODE REVIEW

**Comment by kmike** [comment]
Looks good to me, thanks!

**Comment by eliasdorneles** [comment]
Hm, that phrase shows up here: https://scrapy.readthedocs.io/en/latest/
I always thought of it as a description of the documentation as a whole, which isn't really described by "basic information".

I realize "everything you need to know" isn't strictly true, but it's the spirit we want to have for the documentation.

**Comment by donhuvy** [comment]
Oh, friend. I think it isn't important, it's merely a simple change. Feel free to decide by yourself.

**Comment by eliasdorneles** [comment]
Alright, I'll close this then.

**Pull request closed without merging**
