### PR TITLE
Update doc with our package distribution process

### PR DESCRIPTION
**Pull request by cyberplant**
Related to #1438.

### CODE REVIEW

**Comment by dangra** [comment]
by introducing _stable/testing/unstable_ words it becomes unclear what branch the debian packages are built for, it wasn't clear before either because it is not documented that packages are built only for *latest stable* git branch (1.0) but now it is more confusing.

I think we just need to add a paragraph saying what branch is used to build debian packages and make it clear that all packages published to the three apt components are from the same git branch.

**Comment by cyberplant** [comment]
Interesting.. what branch is used for building the debian package?

**Comment by dangra** [comment]
I'd like to rename apt components to:

- main - no rename, just make it clear it is production ready packages.
- testing->staging - A subset of Scrapinghub real world crawlers uses this for a week.
- unstable->canary - Only development environments uses this for a week.

what do you think?

**Comment by dangra** [comment]
> Interesting.. what branch is used for building the debian package?

1.0 for now, but it will always be latest Scrapy stable branch.

**Comment by cyberplant** [comment]
Understood, perfect. About the renaming.. I like the names as they are now because they are similar to what we're used to, regarding debian packages in general. 

What do you think, @agusc ?

**Comment by agusc** [comment]
I like the current naming convention, I think is pretty straightforward to deduce each component usage by its name. I give you that it is boring and common but what it lacks in originality makes up for quick understanding. Just my 2 cents.   
BTW, how did you come up with that canary name @dangra :)

**Comment by dangra** [comment]
I'm OK to keep using current names, we only have to make it clear what is stable/testing/unstable in this context.

> BTW, how did you come up with that canary name @dangra :)

Chrome has a Canary channel https://www.google.es/chrome/browser/canary.html, but it is common in:

- http://whatis.techtarget.com/definition/canary-canary-testing
- http://martinfowler.com/bliki/CanaryRelease.html

**Pull request closed without merging**
