### PR TITLE
Add .dmg, .iso & .apk to ignored other extensions

### LINKED ISSUE #1837: Add more extensions to IGNORED_EXTENSIONS
A follow-up to https://github.com/scrapy/scrapy/pull/1835. For the record, in my last project I had to also add the following extensions to ignored:

```
{
    '7z', '7zip', 'xz', 'gz', 'tar', 'bz2',   # archives
    'cdr',  # Corel Draw files
    'apk', # Android packages
}
```

cdr and apk look safe; I wonder if we can add .gz: Scrapy decompresses gz responses automatically, so if we add .gz to `IGNORED_EXTENSIONS` spider may stop following e.g. sitemap.xml.gz links. 

On the other hand, for broad crawls most .gz files are archives, and we're filtering out .zip files already.

### PR DESCRIPTION
**Pull request by akhterwahab**
I run into downloading large files while scraping

Fixes #1837, fixes #2067

### CODE REVIEW

**Comment by kmike** [comment]
Looks good to me, thanks @akhterwahab!

**Comment by kmike** [comment]
See also: https://github.com/scrapy/scrapy/pull/2067

**Comment by Gallaecio** [comment]
@akhterwahab Do you think you can add other extensions suggested in #2067? Otherwise, we can merge this _as is_ and include additional extensions later.

**Comment by wRAR** [comment]
Ping @akhterwahab :)

**Comment by akhterwahab** [comment]
> extensions

hi @Gallaecio Maybe we can merge these and add other extensions later on in another PR

**Comment by Gallaecio** [comment]
I’ve added the additional extensions myself using the GitHub editor since it was trivial to do.

**Pull request merged**
