### PR TITLE
added JavaScript FAQ

### PR DESCRIPTION
**Pull request by umrashrf**
I have seen questions popup in Scrapy google group that boils down to "Scrapy can't execute JavaScript" so I think it should be added to Scrapy official FAQ page.

### CODE REVIEW

**Comment by nyov** [comment]
Status? I support this notice. Rebase&Merge?

**Comment by kmike** [comment]
I think it should point to https://github.com/scrapy-plugins/scrapy-splash instead of Splash.

**Comment by Gallaecio** [comment]
Can we close this now that #3703 has been merged?

**Comment by kmike** [comment]
Yes!

**Pull request closed without merging**
