### PR TITLE
Preserve redirect path in metadata

### PR DESCRIPTION
**Pull request by maramsumanth**
As suggested by @whalebot-helmsman  in https://github.com/scrapy/scrapy/issues/3656#issuecomment-471030562

Consider example ```http://www.wikipedia.net/wiki/Hello``` which is finally redirected to ```https://en.wikipedia.org/wiki/Hello```:-

```request.meta``` gives:-
{ .....
  'redirect_urls': [ 'http://www.wikipedia.net/wiki/Hello',
                                         'http://www.wikipedia.org/wiki/Hello',
                                         'https://www.wikipedia.org/wiki/Hello']}

```response.meta``` gives:-
{ .....
  'redirect_urls': [ 'http://www.wikipedia.org/wiki/Hello',
                                            'https://www.wikipedia.org/wiki/Hello',
                                            'https://en.wikipedia.org/wiki/Hello']}

I think it isn't handled properly in https://github.com/scrapy/scrapy/blob/c72ab1d4ba5dad3c68b12c473fa55b7f1f144834/scrapy/downloadermiddlewares/redirect.py#L35

This is what I am aware regarding meta, If I have made any mistake please do let me know.
@whalebot-helmsman @lopuhin , can you please review? :)
Thanks :) :+1:

### CODE REVIEW

**Comment by maramsumanth** [comment]
The following is the redirect chain in which first 3 urls are requests and last 3 urls are corresponding responses


some

**Comment by whalebot-helmsman** [comment]
Sorry @maramsumanth It was my mistake, for unknown reason I decided there is some problem with preserving redirection URLs.
In example you provided I don't see an error. I test using wget
```
[nikita@machine:~/dev/scrapy]$ wget 'http://www.wikipedia.net/wiki/Hello' -O /dev/null                                                                     
--2019-03-12 07:25:40--  http://www.wikipedia.net/wiki/Hello                                                                                                  
Resolving www.wikipedia.net (www.wikipedia.net)... 91.198.174.192, 2620:0:862:ed1a::1                                                                         
Connecting to www.wikipedia.net (www.wikipedia.net)|91.198.174.192|:80... connected.                                                                          
HTTP request sent, awaiting response... 301 Moved Permanently                                                                                                 
Location: http://www.wikipedia.org/wiki/Hello [following]                                                                                                     
--2019-03-12 07:25:40--  http://www.wikipedia.org/wiki/Hello                                                                                                  
Resolving www.wikipedia.org (www.wikipedia.org)... 91.198.174.192, 2620:0:862:ed1a::1                                                                         
Reusing existing connection to www.wikipedia.net:80.                                                                                                          
HTTP request sent, awaiting response... 301 TLS Redirect                                                                                                      
Location: https://www.wikipedia.org/wiki/Hello [following]                                                                                                    
--2019-03-12 07:25:40--  https://www.wikipedia.org/wiki/Hello                                                                                                 
Connecting to www.wikipedia.org (www.wikipedia.org)|91.198.174.192|:443... connected.                                                                         
HTTP request sent, awaiting response... 301 Moved Permanently                                                                                                 
Location: https://en.wikipedia.org/wiki/Hello [following]                                                                                                     
--2019-03-12 07:25:40--  https://en.wikipedia.org/wiki/Hello                                                                                                  
Resolving en.wikipedia.org (en.wikipedia.org)... 91.198.174.192, 2620:0:862:ed1a::1                                                                           
Connecting to en.wikipedia.org (en.wikipedia.org)|91.198.174.192|:443... connected.                                                                           
HTTP request sent, awaiting response... 200 OK                                                                                                                
Length: 66751 (65K) [text/html]                                                                                                                               
Saving to: ‘/dev/null’
```
List of redirection is `["http://www.wikipedia.net/wiki/Hello", "http://www.wikipedia.org/wiki/Hello", "https://www.wikipedia.org/wiki/Hello", "https://en.wikipedia.org/wiki/Hello"]`

And simple scrapy spider https://gist.github.com/whalebot-helmsman/4d6a8aac5d42ba6b842feb00030e3037
```
[nikita@dsc-dev-02:~/dev/scrapy]$ runinenv.sh ~/ves/scrapy scrapy runspider ~/tmp/redirector.py                                                               
Executing scrapy runspider /home/nikita/tmp/redirector.py in /home/nikita/ves/scrapy                                                                          
2019-03-12 07:34:00 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)                                                                            
2019-03-12 07:34:00 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.0, w3lib 1.19.0, Twisted 17.9.0, Python 3.6.3 
(default, Jun  4 2018, 10:24:41) - [GCC 4.8.4], pyOpenSSL 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Linux-4.4.0-96-generic-x86_64-wit
h-debian-jessie-sid                                                                                                                                           
2019-03-12 07:34:00 [scrapy.crawler] INFO: Overridden settings: {'SPIDER_LOADER_WARN_ONLY': True}                                                             
2019-03-12 07:34:00 [scrapy.middleware] INFO: Enabled extensions:                                                                                             
['scrapy.extensions.corestats.CoreStats',                                                                                                                     
 'scrapy.extensions.telnet.TelnetConsole',                                                                                                                    
 'scrapy.extensions.memusage.MemoryUsage',                                                                                                                    
 'scrapy.extensions.logstats.LogStats']                                                                                                                       
2019-03-12 07:34:00 [scrapy.middleware] INFO: Enabled downloader middlewares:                                                                                 
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',                                                                                                  
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',                                                                                    
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',                                                                                      
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',                                                                                                
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',                                                                                                        
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',                                                                                               
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',                                                                                    
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',                                                                                                  
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-03-12 07:34:00 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-03-12 07:34:00 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2019-03-12 07:34:00 [scrapy.core.engine] INFO: Spider opened
2019-03-12 07:34:00 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)                                    
2019-03-12 07:34:00 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023                                                              
2019-03-12 07:34:00 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET http://www.wikipedia.org/wiki/Hello> from <GET http://www.wikipedia.net/wiki/Hello>
2019-03-12 07:34:00 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://www.wikipedia.org/wiki/Hello> from <GET http://www.wikipedia.org/wiki/Hello>
2019-03-12 07:34:01 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://en.wikipedia.org/wiki/Hello> from <GET https://www.wikipedia.org/wiki/Hello>
2019-03-12 07:34:01 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://en.wikipedia.org/wiki/Hello> (referer: None)                                      
2019-03-12 07:34:01 [redirect] INFO: ['http://www.wikipedia.net/wiki/Hello', 'http://www.wikipedia.org/wiki/Hello', 'https://www.wikipedia.org/wiki/Hello']  
2019-03-12 07:34:01 [redirect] INFO: https://en.wikipedia.org/wiki/Hello
2019-03-12 07:34:01 [scrapy.core.engine] INFO: Closing spider (finished)
2019-03-12 07:34:01 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1046,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,
 'downloader/response_bytes': 21124,
 'downloader/response_count': 4,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/301': 3,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 3, 12, 7, 34, 1, 289857),
 'log_count/DEBUG': 4,
 'log_count/INFO': 10,
 'memusage/max': 51957760,
 'memusage/startup': 51957760,
 'response_received_count': 1,
 'scheduler/dequeued': 4,
 'scheduler/dequeued/memory': 4,
 'scheduler/enqueued': 4,
 'scheduler/enqueued/memory': 4,
 'start_time': datetime.datetime(2019, 3, 12, 7, 34, 0, 936595)}
2019-03-12 07:34:01 [scrapy.core.engine] INFO: Spider closed (finished)
```
`response.meta["redirect_urls"]` and `response.url` provide correct chain of redirections
```
2019-03-12 07:34:01 [redirect] INFO: ['http://www.wikipedia.net/wiki/Hello', 'http://www.wikipedia.org/wiki/Hello', 'https://www.wikipedia.org/wiki/Hello']  
2019-03-12 07:34:01 [redirect] INFO: https://en.wikipedia.org/wiki/Hello
```

I think we can close this PR

**Comment by maramsumanth** [comment]
Ok Thanks for looking at this. I am also having a little confusion regarding metadata. Now it is clarified  Thanks :) :+1:

**Comment by maramsumanth** [comment]
@whalebot-helmsman , can you give exactly what urls should contain in response.meta ?

**Comment by whalebot-helmsman** [comment]
I raised this issue based on one crawl I done before. It was misconfiguration from my side and I didn't check sources properly. After https://github.com/scrapy/scrapy/issues/3656#issuecomment-470859425 my mistake was obvious. Sorry for created confusion, I didn't want to do that. Next time I will check sources.

**Comment by maramsumanth** [comment]
Ok np :)

**Pull request closed without merging**
