### PR TITLE
[MRG+1] dissolve contrib_exp

### PR DESCRIPTION
**Pull request by nyov**
Here's a start for #1063, getting rid of contrib_exp.
I haven't deleted the old xml_iter yet, I think it should be done in the next commit so we have at least a point in history where bot are available.
The decompression middleware I moved to contrib, django item was only a deprecation warning anyway.

edit: I don't think we need backwards-compat. for this one, it said "experimental" for a reason.

### CODE REVIEW

**Comment by kmike** [comment]
1. What about keeping both xmliter_lxml and xmliter for now? Before removing xmliter we should check that xmliter_lxml works better.
2. Even though contrib_exp was experimental, people used it, so +1 from me to add a backwards compatibility shim.

**Comment by nyov** [comment]
Not my decision to remove xmliter, I wouldn't mind to keep both, @Curita mentioned that in https://github.com/scrapy/scrapy/issues/1063#issuecomment-89200496.

On the compat shims, would you agree that we don't need one for djangoitem? It was already a shim (since 70f8e51).

**Comment by kmike** [comment]
> On the compat shims, would you agree that we don't need one for djangoitem? It was already a shim (since 70f8e51).

Yes, +1 to dropping the existing djangoitem shim.

**Comment by Curita** [comment]
I don't recall why we decided on removing xmliter really (/cc @nramirezuy, @pablohoffman). I'm OK with keeping it too.

**Comment by kmike** [comment]
Thanks @nyov, the PR looks good to me. 
+1 to merge it after https://github.com/scrapy/scrapy/pull/963.

**Comment by pablohoffman** [comment]
needs rebase after merging #963

**Comment by nyov** [comment]
done

**Pull request merged**
