### PR TITLE
Deprecate scrapy.pipelines.images.NoimagesDrop

### PR DESCRIPTION
**Pull request by PluT00**
Deprecate scrapy.pipelines.images.NoimagesDrop

Resolves https://github.com/scrapy/scrapy/issues/5368

### CODE REVIEW

**Comment by wRAR** [comment]
(I don't think `@deprecated` works as expected for classes)

**Comment by PluT00** [comment]
Thanks for your response. Will fix it.

**Comment by PluT00** [comment]
This should work correctly

**Comment by PluT00** [comment]
Hey! Could you tell me please, what should I do with these checks which were cancelled? And what do you think about the solution? @wRAR

**Review by Gallaecio — APPROVED** [review]

**Review by wRAR — APPROVED** [review]

**Pull request merged**
