### PR TITLE
[MRG+1] Doc improve log formating examples

### PR DESCRIPTION
**Pull request by Digenis**
When the formatting is done by the logger (`logger.info('%s', val)`)
and a formatting exception occurs, there are several problems:
- The exception & stacktrace is printed to stderr, not the log (#2450)
- The debugger is not invoked by twisted (#1551)
- Extensions don't see errors; Errors are not even counted in the stats.
- It's impossible to see the full stacktrace
  with frames from the caller of the logger

I demonstrated some of this in #1551.
This is why I prefer early formatting when logging.

Code updated like this is backward incompatible
because exceptions will occur early, in the caller of the log
stopping execution of any code that failed formatting.
(This is irrelevant to deprecation policy,
 I only update documentation examples)

Edit: I also updated another formatting example that could be simple.
Edit2: Build fails because of the twisted update

### CODE REVIEW

**Comment by eliasdorneles** [comment]
I agree formatting earlier is better, +1 to merge.

**Comment by chekunkov** [comment]
+1

**Comment by Digenis** [comment]
How about doing this to actual code of scrapy components?

**Comment by nramirezuy** [comment]
I'm not sure if any of the issued log lines here is used by someone, but by doing this we are choosing a route I don't quite agree. I would like to keep [structured logging](https://docs.python.org/2/howto/logging-cookbook.html#implementing-structured-logging).

**Comment by Digenis** [comment]
I'd much prefer to have some of the bullet-points above resolved
than discuss early vs late formatting and the usefulness of structured logging.
To me, these are the real bugs bugging the 1.0 release.
So far I only managed to pull together #1551 which is yet to be reviewed.

**Comment by rolando** [comment]
Keep in mind that Sentry (and surely other tools as well) rely on proper lazy formatting to be able to aggregate/deduplicate log messages.

**Comment by Digenis** [comment]
Let's leave this PR aside for a while.
I added a reference to #2450 on my first bullet point
and I hope to get some comments there.
Perhaps more things can be fixed without breaking structured logging.

**Comment by dangra** [comment]
This is not happening. Lazy formatting is the preferred way.

**Pull request closed without merging**
