### PR TITLE
Update __init__.py import

### PR DESCRIPTION
**Pull request by azenkwed**
Update __init__.py import to fix import error.

### CODE REVIEW

**Comment by wRAR** [comment]
What problem does this solve?

**Comment by elacuesta** [comment]
I'm +0 on this. I haven't seen any errors from this particular import (`NameOID` is imported [here](https://github.com/pyca/cryptography/blob/3.2.1/src/cryptography/x509/__init__.py#L94)).

**Comment by azenkwed** [comment]
It doesn't solve an issue. It was just cleaning the code as bit as I'm reading through it.

**Comment by Gallaecio** [comment]
Thanks for the pull request, but I think it’s a change for the worse.

In the [documentation](https://cryptography.io/en/stable/x509/reference/#cryptography.x509.oid.NameOID) they document the import path that the code currently uses. If they ever decide to remove one of the import paths, I think they would remove the one that is _not_ documented.

**Comment by azenkwed** [comment]
Thank you.

**Pull request closed without merging**
