### PR TITLE
implement AWS_SECURE_CONNECTION as setting instead

### PR DESCRIPTION
**Pull request by maksimbormot**

### CODE REVIEW

**Comment by redapple** [comment]
@maksimbormot , is this the same as the last commit for https://github.com/scrapy/scrapy/pull/2246 ?
(https://github.com/scrapy/scrapy/pull/2085/commits/a717e4425fdc76aa4d71ed19748f546264f28f94)
I believe you can close this one and review can continue there

**Comment by redapple** [comment]
@lopuhin may have comments too.

**Comment by lopuhin** [comment]
@redapple probably you meant #2085? I think that the general approach outlined there is good, it's nice to have SSL on by default and be able to turn it off.

**Comment by redapple** [comment]
@lopuhin , yes, I meant #2085. I'm mixing PR numbers these days, I dunno why.

**Comment by redapple** [comment]
Let's keep discussing in https://github.com/scrapy/scrapy/pull/2085

**Pull request closed without merging**
