### PR TITLE
pass on item to thumb_path function as additional argument 

### LINKED ISSUE #5504: ImagesPipeline.thumb_path should allow access to item
## Summary

ImagesPipeline should pass on item to thumb_path function as additional argument.

## Motivation

The ImagesPipeline.file_path function allows access to item. So when an user overwrites this function and makes the file name
depended on the item itself, it makes sense to have the thumb path to be depended on the item as well.

This way main image file and thumbnail image file can have the same name and it is easily possible to jump between different sizes of the image.

Example of how a file and thumbnail could be build:
```python
file_path = f"full/{item['ID']}.jpg"
thumb_path = f"thumbs/small/{item['ID']}.jpg"
```

So I suggest to change the signature of ImagesPipeline.thumb_path to the following:
```python
def thumb_path(self, request, thumb_id, response=None, info=None, *, item=None):
```
which makes the functions thumb_path and file_path more consistent.

## Describe alternatives you've considered

As a workaround when I overwrite `file_path` I set `request._item = item` which I can then access in `thumb_path` function.

## Additional context

In case this is of interest I am happy to work on a pull request.

### PR DESCRIPTION
**Pull request by mtabbasi**
Fixes #5504

### CODE REVIEW

**Comment by wRAR** [comment]
Can you please take a look at #4686 and update your PR accordingly?

**Comment by mtabbasi** [comment]
> 

Sure

**Review by Gallaecio — APPROVED** [review]

**Comment by kmike** [comment]
Thanks @mtabbasi, the PR looks good!

**Comment by mtabbasi** [comment]
My pleasure @kmike

**Pull request merged**
