### PR TITLE
Update responsetypes.py

### PR DESCRIPTION
**Pull request by jmaynier**
Typo in header name, that make the from_headers function fail.

### CODE REVIEW

**Comment by kmike** [comment]
When are you getting this error? Headers are supposed to be case-insensitive, so `headers` should be an instance of case-insensitive `Headers`, not a regular dict.

**Comment by jmaynier** [comment]
I use a cache middleware https://github.com/Kpler/scrapy-history-middleware that save request/response as json and then recreate the request/response from the json.
It does not use the Headers class, that's why. I will use it. 
But you should use the official header name in the code.

**Comment by nramirezuy** [comment]
@jmaynier [looks like fixed](https://github.com/Kpler/scrapy-history-middleware/commit/0cc91b1a68ecb804562f9f87c6f26018502fdcd5); can we close?

**Comment by jmaynier** [comment]
yes you can close it. Thanks


Best regards,

--
Jean Maynier
Co-founder / CTO
Mail:           jmaynier@kpler.com
Office:        + 33 1 8381 8790
Mobile:       +33 6 11 46 92 31 <%2B%2033%206%2011469231>
YahooIM:    jean.maynier
Twitter:       @jmaynier
kpler.com | Kpler, SAS.

**Pull request closed without merging**
