### PR TITLE
Fix scrapy shell from hanging when a request is filtered by the dupefilter

### PR DESCRIPTION
**Pull request by marven**
Shell hangs when a request is filtered by the dupefilter since it waits for a response when the original request that was supposed to be enqueued already got discarded.

```
>>> from scrapy.http import Request
>>> fetch(Request(url='http://example.com'))
2015-03-19 01:21:12+0800 [default] INFO: Spider opened
2015-03-19 01:21:13+0800 [default] DEBUG: Crawled (200) <GET http://example.com> (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x103b6b3d0>
[s]   item       {}
[s]   request    <GET http://example.com>
[s]   response   <200 http://example.com>
[s]   settings   <scrapy.settings.Settings object at 0x103b6af10>
[s]   spider     <DefaultSpider 'default' at 0x1041c2ed0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser
>>> fetch(Request(url='http://example.com'))
2015-03-19 01:21:15+0800 [default] DEBUG: Filtered duplicate request: <GET http://example.com> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
>>> fetch(Request(url='http://example.com'))
>>> fetch(Request(url='http://example.com', dont_filter=True))
2015-03-19 01:21:32+0800 [default] DEBUG: Crawled (200) <GET http://example.com> (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x103b6b3d0>
[s]   item       {}
[s]   request    <GET http://example.com>
[s]   response   <200 http://example.com>
[s]   settings   <scrapy.settings.Settings object at 0x103b6af10>
[s]   spider     <DefaultSpider 'default' at 0x1041c2ed0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser
>>>
```

### CODE REVIEW

**Comment by nramirezuy** [comment]
I'm [not able to reproduce](https://gist.github.com/nramirezuy/67820d76430ffe65bb40) on master branch.

**Comment by marven** [comment]
@nramirezuy, `fetch(url)` doesn't get doesn't get dupefiltered, try `fetch(Request(url))`

**Comment by nramirezuy** [comment]
@marven You are right!

In theory this can be solved by doing [this](https://gist.github.com/nramirezuy/81e0875079e5889d2a86).

**Comment by marven** [comment]
I wanted to avoid having to change the default `DUPEFILTER_CLASS` just for the shell in case someone was testing multiple fetch's and was checking for duplicate urls.

**Comment by Digenis** [comment]
What is the status on this PR?

I was about to open a PR doing exactly what @nramirezuy suggested
when I noticed there already this PR right here.

My opinions on your two points @marven :
- using `fetch` to test for duplicate urls is an overkill, `scrapy.utils.request.request_fingerprint` would do this very well without the side effect of downloading
- while testing a custom dupefilter, again, the shell is an overkill. Most tests can be adapted from the builtin tests and be run efficiently from a test script/suite

Because of this, I'd prefer the second, simpler solution: overriding the setting just for the shell.

**Comment by Digenis** [comment]
I think #1598 resolves this unless someone can demonstrate the usefulness of a dupefilter in the shell.
So far @marven hypothesized that someone would use the scrapy shell to filter duplicate urls or test a custom dupefilter. Are there any practical use-cases?

**Comment by kmike** [comment]
Closing in favor of #1598. Feel free to repoen if there is a real use case!

**Pull request closed without merging**
