### PR TITLE
[MRG+1]Pydispatch pep8

### PR DESCRIPTION
**Pull request by chekunkov**
Tabs to spaces, proper number of blank lines between imports, classes and methods

### CODE REVIEW

**Comment by kmike** [comment]
The long-term plan is to drop bundled pydispatch copy. I wonder if it make sense to do such changes to it.

**Comment by nramirezuy** [comment]
@chekunkov Already wasted time doing it, and merging it won't harm anyone. I will just suggest to sqash and rename commit to make allusion to `pydispatch`.

**Comment by chekunkov** [comment]
@kmike some plans are too long-term :) I was reading that code and fix costed me almost nothing - 2-5 clicks and 2 minutes of my time

@nramirezuy yep, I can squash and rename commit

**Comment by chekunkov** [comment]
@nramirezuy please tell if commit message looks better now

**Pull request merged**
