### PR TITLE
[MRG +1] remove scrapy deploy command

### PR DESCRIPTION
**Pull request by nyov**
For #1027

I'm not sure this if is really all there is to it. Basically just trashed the file here.

### CODE REVIEW

**Comment by kmike** [comment]
Looks good; +1 to merge once we create scrapyd-client package.

**Comment by Curita** [comment]
Since we merged #1124 I think we can merge this removal now, what do you think? (though it needs to be rebased before that).

**Comment by pablohoffman** [comment]
+1 but needs rebase

**Comment by Curita** [comment]
Rebased and merged in 0bf1ec1

**Comment by nyov** [comment]
Thank you! sorry for skipping out.

**Pull request closed without merging**
