### PR TITLE
Cleanup METHOD_SSLv3

### LINKED ISSUE #5635: SSLv3_METHOD where did you come from???????????????
[WHAT THE F](https://github.com/scrapy/scrapy/blob/1.5.0/scrapy/core/downloader/tls.py#L17)

does not exist in pyopenssl

no help anywhere

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

docs generation is not running for PRs?

Fixes #5632, fixes #5635.

### CODE REVIEW

**Comment by Gallaecio** [comment]
We need to update https://docs.scrapy.org/en/latest/topics/settings.html#downloader-client-tls-method as well.

**Comment by gliptak** [comment]
@Gallaecio updated

**Review by Gallaecio — APPROVED** [review]

**Comment by kmike** [comment]
Hey! In install_requires we list pyOpenSSL 21.0 as a minimum requirement; should we support SSLv3 if older pyOpenSSL is installed? I.e. do getattr instead of removing the support completely?

@Gallaecio @wRAR what do you think about backporting the fix (e.g. for 2.6.3)?

**Comment by Gallaecio** [comment]
Since [web browsers only support TLS 1.2+](https://github.com/scrapy/scrapy/issues/5621#issuecomment-1248231516), and [SSLv3 is worse than TLS 1.0](https://docs.twistedmatrix.com/en/twisted-20.3.0/core/howto/ssl.html#tls-protocol-options), I don’t think it is a big deal. In fact, I would be OK with dropping TLS 1.0 and 1.1 as well from there, just as the latest Twisted does, based on the argument that we aim to replicate browser behavior.

Not a strong opinion, though. @wRAR?

**Comment by kmike** [comment]
Ok, let's kill SSLv3 :) Thanks for the help @gliptak!

**Comment by xhMiao** [comment]
how to kill SSLv3？

**Comment by kmike** [comment]
It's killed in master @xhMiao; we're also going to do 2.6.3 release (https://github.com/scrapy/scrapy/pull/5637), but it's not released yet. For now you can pin pyOpenSSL version, as described in https://github.com/scrapy/scrapy/issues/5635#issuecomment-1257415952.

**Pull request merged**
