### PR TITLE
[MRG+1] 0 delay inside utils/defer.py->defer_succeed makes reactor not to be async enough

### PR DESCRIPTION
**Pull request by aliowka**
This will make scrapy to be more async by letting the reactor spend extra cycles to accomplish its needs.

### CODE REVIEW

**Comment by pablohoffman** [comment]
do you have a particular real-world case where this change produces a clear improvement?

**Comment by aliowka** [comment]
Yes, sure. Please see the issue #1074.
I need to store a whole htmls of the site with httpcache middlewate to run/rerun different tasks on it without actually querying the web site. As I described in the issue, when using httpcache middleware, scrapy effectively becoms synchronous (0 delay is not enough). So I can't use a reactor for storing the items to queue. I can't use txamqp - a twisted-based client for Rabbitmq, it just blows up in memory(please see the opened issue for numbers). 
The fix will make scrapy more async, therefore better.

**Comment by nramirezuy** [comment]
@aliowka Can we reproduce it with some simple code?

I tried [here](https://gist.github.com/nramirezuy/14055275449bc4a08fad) but I wasn't able to.

**Comment by dangra** [comment]
The original intention of `defer_succeed()` and `defer_fail()`  was to provide enough reactor cycles for other tasks to run, there is not a point on using `callLater()` if not. I think the bug and its fix are valid even if 0.1 is an arbitrary value as 0 was.

**Comment by dangra** [comment]
The background on this issue is that Twisted process timed calls before file descriptors.  Zero delay means it will process all delayed calls (pending and newly generated while processing existent calls) immediately after it reaches the reactor loop for 1 second max, only then it attend file descriptors but the next iteration will be busy again for 1 second handling delayed calls. 

Scrapy generates lot of delayed calls, it is not rare to add more delayed calls from within delayed calls, so the IO loop is not handling real IO most of the time.

**Comment by Curita** [comment]
Closed by #1253

**Pull request closed without merging**
