### PR TITLE
FormRequest.from_response supports multiple forms instead of just the first matching form

### PR DESCRIPTION
**Pull request by theresia**
1. `_get_form` will return all forms matching `formxpath`, `formname`, and `formid` instead of just the first matching form.

2. `from_response` collects and merges the `formdata` from all matching forms.

3. added `tests/test_from_response_multiple_xpaths`

Case found at https://us.topshop.com/webapp/wcs/stores/servlet/UserRegistrationForm?langId=-1&catalogId={catalogId}&storeId={storeId}

During Guest Checkout, the page does a POST to one endpoint with `formdata` from two different forms with the same xpath: `//form[@action="ProcessDeliveryDetails"]`

### CODE REVIEW

**Comment by dangra** [comment]
hi @theresia, it looks backward incompatible and it is hard to believe browsers submit fields from unrelated forms. Do browsers really do that or is it a javascript trick?

**Comment by kmike** [comment]
I agree with Daniel: browsers don't submit multiple HTML forms; -1 to make FormRequest do that. It is true that custom JS code can collect data from multiple `<form>` elements, but this is non-standard, and it shouldn't be default Scrapy behaviour.

What I'd like to see is to refactor scrapy.http.request.form to make it easy to send such requests without hacking around FormRequest implementation. We should have better & more versatile helper functions there.

**Comment by theresia** [comment]
@dangra @kmike I see your points, looking into refactoring and the idea for helper functions.

**Comment by theresia** [comment]
@dangra By the way, how is it backward incompatible? It passes all the existing tests.

**Comment by dangra** [comment]
> By the way, how is it backward incompatible? It passes all the existing tests.

@theresia because there is not a test case for a page with 2 forms matched by selection method that only submit fields on the first form. All other tests assume the selection method matches exactly one form.

**Comment by Youwotma** [comment]
Similar but not exactly this, browsers add data from fields outside of a form if they have the form="id" attribute set, so `_get_inputs` could be improved to be compliant with this (basically implement the [form attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-form)).

**Comment by dangra** [comment]
@Youwotma that's a valid feature we are missing.

**Pull request closed without merging**
