### PR TITLE
Fixing tests for upcoming 3.10.

### PR DESCRIPTION
**Pull request by wRAR**
Closes: #5212.

There is an elusive problem in `SpiderLoaderTest` which I can't reproduce when running tests only for that module. It's related to #5160 because that test checks the warning list and gets an unexpected one ("_SixMetaPathImporter.find_spec() not found;").

### CODE REVIEW

**Comment by wRAR** [comment]
The remaining warning ("_SixMetaPathImporter.find_spec() not found; falling back to find_module()") looks like a valid `six` problem already fixed in its code and we don't even use it directly, so I don't think we should (or can) do anything to remove this warning. This takes us back to the generic problem of "we expect a warning but get a different one first" tackled in #5160.

**Comment by Gallaecio** [comment]
xfail?

**Comment by wRAR** [comment]
Actually if we go as far as adding such checks we could just edit the test to skip this six warning.

**Comment by wRAR** [comment]
The most recent six version actually contains the fix for this, but six is vendored in several other libraries, and botocore contains an older version, and importing `botocore.vendored.six` before running this test makes it fail (not sure if this piece of data is useful though).

**Comment by Gallaecio** [comment]
Since it is not a direct dependency, your suggestion of [ignoring warnings from six in our test runs](https://docs.pytest.org/en/6.2.x/warnings.html) makes sense to me.

**Comment by wRAR** [comment]
Not sure how to express that though, do you mean warnings mentioning `_SixMetaPathImporter`? Also it's technically a warning from Python importlib.

**Comment by wRAR** [comment]
category: `ImportWartning`, message: '_SixMetaPathImporter.find_spec() not found; falling back to find_module()'

**Review by Gallaecio — APPROVED** [review]

**Pull request merged**
