### PR TITLE
[MRG+1] Add ``errors`` argument to Headers.to_unicode_dict().

### LINKED ISSUE #2589: Headers.to_unicode_dict() fails with badly encoded values
Here is an example:

```
n [21]: response.headers
{b'Accept-Ranges': b'bytes',
 b'Cache-Control': b'max-age=604800',
 b'Content-Type': b'text/html',
 b'Date': b'Wed, 22 Feb 2017 04:03:39 GMT',
 b'Etag': b'"801764d9a9acf1:0"',
 b'Last-Modified': b'Mon, 06 Jan 2014 06:38:03 GMT',
 b'Public-Key-Pins': b'pin-sha256=\x94SPKI_digest#1"; pin-sha256="SPKI_digest#2"; max-age=31536000',
 b'Server': b'Microsoft-IIS/7.5',
 b'Strict-Transport-Security': b'max-age=31536000; includeSubDomains',
 b'Vary': b'Accept-Encoding,Accept-Encoding',
 b'X-Powered-By': b'ASP.NET',
 b'X-Powered-By-Plesk': b'PleskWin'}

In [22]: response.headers.to_unicode_dict()
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-22-259fb34b3193> in <module>()
----> 1 response.headers.to_unicode_dict()

<env>/lib/python3.5/site-packages/scrapy/http/headers.py in to_unicode_dict(self)
     87             (to_unicode(key, encoding=self.encoding),
     88              to_unicode(b','.join(value), encoding=self.encoding))
---> 89             for key, value in self.items())
     90
     91     def __copy__(self):

<env>/lib/python3.5/site-packages/scrapy/utils/datatypes.py in __init__(self, seq)
    191         super(CaselessDict, self).__init__()
    192         if seq:
--> 193             self.update(seq)
    194
    195     def __getitem__(self, key):

<env>/lib/python3.5/site-packages/scrapy/utils/datatypes.py in update(self, seq)
    227         seq = seq.items() if isinstance(seq, dict) else seq
    228         iseq = ((self.normkey(k), self.normvalue(v)) for k, v in seq)
--> 229         super(CaselessDict, self).update(iseq)
    230
    231     @classmethod

<env>/lib/python3.5/site-packages/scrapy/utils/datatypes.py in <genexpr>(.0)
    226     def update(self, seq):
    227         seq = seq.items() if isinstance(seq, dict) else seq
--> 228         iseq = ((self.normkey(k), self.normvalue(v)) for k, v in seq)
    229         super(CaselessDict, self).update(iseq)
    230

<env>/lib/python3.5/site-packages/scrapy/http/headers.py in <genexpr>(.0)
     87             (to_unicode(key, encoding=self.encoding),
     88              to_unicode(b','.join(value), encoding=self.encoding))
---> 89             for key, value in self.items())
     90
     91     def __copy__(self):

<env>/lib/python3.5/site-packages/scrapy/utils/python.py in to_unicode(text, encoding, errors)
    105     if encoding is None:
    106         encoding = 'utf-8'
--> 107     return text.decode(encoding, errors)
    108
    109

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 11: invalid start byte
```

### PR DESCRIPTION
**Pull request by rolando**
Fixes #2589

### CODE REVIEW

**Comment by rolando** [comment]
This address #2589:

```
In [2]: response.headers.to_unicode_dict(errors='ignore')

{'accept-ranges': 'bytes',
 'cache-control': 'max-age=604800',
 'content-type': 'text/html',
 'date': 'Thu, 23 Feb 2017 06:19:22 GMT',
 'etag': '"3acb6d9a9acf1:0"',
 'last-modified': 'Mon, 06 Jan 2014 06:38:03 GMT',
 'public-key-pins': 'pin-sha256=SPKI_digest#1"; pin-sha256="SPKI_digest#2"; max-age=31536000',
 'server': 'Microsoft-IIS/7.5',
 'strict-transport-security': 'max-age=31536000; includeSubDomains',
 'vary': 'Accept-Encoding',
 'x-powered-by': 'ASP.NET',
 'x-powered-by-plesk': 'PleskWin'}
```

**Comment by kmike** [comment]
Looks good to me, thanks!

**Comment by redapple** [comment]
What about also adding an encoding argument to override `self.encoding`?
It seems scrapy [never explicitly sets encoding of Response headers](https://github.com/scrapy/scrapy/blob/adb180fbaf7de9f720e76b33c742f6cdaa083cdd/scrapy/core/downloader/handlers/http11.py#L358), defaulting to UTF-8. (I don't know if it changes it afterwards).
Though different headers could have different encoding, so errors argument is still handy.

**Comment by rolando** [comment]
@redapple I found out there is a [RFC](https://tools.ietf.org/html/rfc7230#section-3.2.4) that says:

>    Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

So, by default headers should be decoded with `latin1` charset. But that's a backwards incompatible change (only in cases where headers are non-ascii / non-latin1 compatible).

The example of the issue decodes fine with `latin1`:
```
In [2]: response.headers.to_unicode_dict('latin1')

{'accept-ranges': 'bytes',
 'cache-control': 'max-age=604800',
 'content-type': 'text/html',
 'date': 'Thu, 23 Feb 2017 19:45:35 GMT',
 'etag': '"801764d9a9acf1:0"',
 'last-modified': 'Mon, 06 Jan 2014 06:38:03 GMT',
 'public-key-pins': 'pin-sha256=\x94SPKI_digest#1"; pin-sha256="SPKI_digest#2"; max-age=31536000',
 'server': 'Microsoft-IIS/7.5',
 'strict-transport-security': 'max-age=31536000; includeSubDomains',
 'vary': 'Accept-Encoding,Accept-Encoding',
 'x-powered-by': 'ASP.NET',
 'x-powered-by-plesk': 'PleskWin'}
```

I've updated the PR to include a `encoding` parameter.

**Comment by kmike** [comment]
@rolando yeah, latin1 is a better default, but as I recall e.g. Cookie header should be decoded from utf-8. I'm not wild about adding another argument which still doesn't solve the issue with encodings, but having this argument can be a bit more convenient indeed. Maybe encoding=None should have a meaning "do as good as you can - e.g. utf-8 for a fixed set of known headers (with latin1 fallback), latin1 for other headers". It is also not clear what is `encoding` constructor argument for.

**Comment by rolando** [comment]
@kmike I created this issue https://github.com/scrapy/scrapy/issues/2592 to follow the default encoding discussion.

**Comment by rolando** [comment]
See PR https://github.com/scrapy/scrapy/pull/2593 as an alternative solution.

**Comment by rolando** [comment]
Closing in favor of https://github.com/scrapy/scrapy/pull/2593

I'm not sure if it's worth to add `errors` support to #2593 as, IMO, that implementation would cover 99% of the cases. Also it's not clear how would `errors` interact with the encodings fallback because it will disable the fallback.

**Pull request closed without merging**
