### PR TITLE
SCRAPY_CHECK will be set while running contact (Fixes #4222)

### LINKED ISSUE #4222: SCRAPY_CHECK is not set while running contract
### Description

Hi, it seems that #3739 is not doing what the [documentation describe](https://docs.scrapy.org/en/latest/topics/contracts.html#detecting-check-runs):

`os.environ.get('SCRAPY_CHECK')` is returning `None` in my contract check.

### Steps to Reproduce

1. Create a project from scratch
2. Add a random spider
3. Contract code is as follow
```
    def parse(self, response):
        """
        @url http://www.amazon.com/s?field-keywords=selfish+gene
        @returns requests 1 1
        """
        print("test", os.environ.get('SCRAPY_CHECK'))
        if os.environ.get('SCRAPY_CHECK'):
            yield scrapy.Request(url="next_url")
```

**Expected behavior:** Request should be yielded as per the documentation

**Actual behavior:** Nothing happen

**Reproduces how often:** In my local project and with fresh project

### Versions

Windows
```
(globenv) C:\Users\johnl>scrapy version --verbose
Scrapy       : 1.8.0
lxml         : 4.4.1.0
libxml2      : 2.9.5
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.10.0
Python       : 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1c  28 May 2019)
cryptography : 2.7
Platform     : Windows-10-10.0.18362-SP0
```

Linux
```
scrapy version --verbose
Scrapy       : 1.8.0
lxml         : 4.4.1.0
libxml2      : 2.9.9
cssselect    : 1.1.0
parsel       : 1.5.2
w3lib        : 1.21.0
Twisted      : 19.7.0
Python       : 3.6.8 (default, Oct  7 2019, 12:59:55) - [GCC 8.3.0]
pyOpenSSL    : 19.0.0 (OpenSSL 1.1.1d  10 Sep 2019)
cryptography : 2.8
Platform     : Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
```

### PR DESCRIPTION
**Pull request by faizan2700**
(Edit) Fixes #4222

### CODE REVIEW

**Comment by elacuesta** [comment]
Looks good, thanks. Do you think you could add some tests?

**Comment by faizan2700** [comment]
sure

**Comment by Gallaecio** [comment]
@faizan2700 Could you share here the traceback of the exception that you get while running the tests?

**Comment by faizan2700** [comment]
[
error1


](url)

**Comment by faizan2700** [comment]
error1
error2

**Comment by faizan2700** [comment]
I am using tox command.

**Comment by Gallaecio** [comment]
Please, use text instead of images.

**Comment by faizan2700** [comment]
It is very long traceback can you please tell me which part is not clear or what part should I write in text format from above images.

**Comment by Gallaecio** [comment]
I’m not too worried about the length, but [it looks like you can make the text collapsible](https://stackoverflow.com/a/52215506/939364).

**Comment by faizan2700** [comment]
<details>
<summary>Error Traceback</summary>

C:\user's content\github repos\scrapy>tox > D:\a.txt
Traceback (most recent call last):
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\run.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\run.py", line 85, in _run_code
		exec(code, run_globals)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\scripts\tox.exe\__main__.py", line 9, in <module>
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
		main(args)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 64, in main
		config = load_config(args)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 80, in load_config
		config = parseconfig(args)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 269, in parseconfig
		ParseIni(config, config_file, content)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1152, in __init__
		for key, (exec, trace) in failures.items()
	tox.exception.ConfigError: ConfigError: docs-links failed with No closing quotation at Traceback (most recent call last):
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
		results[name] = cur_self.make_envconfig(name, section, subs, config)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
		res = meth(env_attr.name, env_attr.default, replace=replace)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
		return _ArgvlistReader.getargvlist(self, s, replace=replace)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
		commands.append(cls.processcommand(reader, current_command, replace))
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
		return list(shlexer)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
		token=self.get_token()
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
		raw = self.read_token()
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
		raise ValueError("No closing quotation")
ValueError: No closing quotation

docs failed with No closing quotation at traceback (most recent call last):
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
		results[name] = cur_self.make_envconfig(name, section, subs, config)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
		res = meth(env_attr.name, env_attr.default, replace=replace)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
		return _ArgvlistReader.getargvlist(self, s, replace=replace)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
		commands.append(cls.processcommand(reader, current_command, replace))
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
		return list(shlexer)
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
		token=self.get_token()
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
		raw = self.read_token()
	File "C:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
		raise ValueError("No closing quotation")
ValueError: No closing quotation
		
		
</details>

**Comment by faizan2700** [comment]
I am sorry I could not find a way to copy from commandline and as command is not successful it is not directing to output logfile therefore I had to type everything.  I hope this is now helpful can you please tell me what should I do to avoid this error (@Gallaecio ). Thank You

**Comment by Gallaecio** [comment]
> I am sorry I could not find a way to copy from commandline

Sorry, I should have realized that may have been the issue here. This should help: https://stackoverflow.com/a/1420981/939364. Also, you should be able to copy text from the terminal even in Windows. In Windows I think it gets copied into the clipboard after you select it, but I’m not sure.

**Comment by Gallaecio** [comment]
It looks like the issue comes from Tox. Searching for the error I reached https://bugs.launchpad.net/ironic/+bug/1527562, which leads to https://bitbucket.org/hpk42/tox/issues/181

Could you try Tox version 3.14.5? (the one I am using)

**Comment by faizan2700** [comment]
<details> 
<summary> getting same traceback error < /summary> 
Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Smart Gadget\AppData\Local\Programs\Python\Python37\Scripts\tox.exe\__main__.py", line 9, in <module>
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 64, in main
    config = load_config(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 269, in parseconfig
    ParseIni(config, config_file, content)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1152, in __init__
    for key, (exc, trace) in failures.items()
tox.exception.ConfigError: ConfigError: docs failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

docs-coverage failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

docs-links failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation


</details>

**Comment by faizan2700** [comment]
<details>
<summary> getting same error </summary> 

Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Smart Gadget\AppData\Local\Programs\Python\Python37\Scripts\tox.exe\__main__.py", line 9, in <module>
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 64, in main
    config = load_config(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 269, in parseconfig
    ParseIni(config, config_file, content)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1152, in __init__
    for key, (exc, trace) in failures.items()
tox.exception.ConfigError: ConfigError: docs failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

docs-coverage failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

docs-links failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

</details>

**Comment by faizan2700** [comment]
Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Smart Gadget\AppData\Local\Programs\Python\Python37\Scripts\tox.exe\__main__.py", line 9, in <module>
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 64, in main
    config = load_config(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\session\__init__.py", line 80, in load_config
    config = parseconfig(args)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 269, in parseconfig
    ParseIni(config, config_file, content)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1152, in __init__
    for key, (exc, trace) in failures.items()
tox.exception.ConfigError: ConfigError: docs failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

docs-coverage failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

docs-links failed with No closing quotation at Traceback (most recent call last):
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1125, in run
    results[name] = cur_self.make_envconfig(name, section, subs, config)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1273, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1522, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1732, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace))
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\config\__init__.py", line 1781, in processcommand
    return list(shlexer)
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 295, in __next__
    token = self.get_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 105, in get_token
    raw = self.read_token()
  File "c:\users\smart gadget\appdata\local\programs\python\python37\lib\shlex.py", line 187, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation

**Comment by faizan2700** [comment]
Thanks for stackoverflow answer of copying text from windows that worked and I have copied the above error with the help of that answer.

**Comment by Gallaecio** [comment]
Could you run `tox --version` to check which version of Tox you are running?

**Comment by faizan2700** [comment]
3.14.5 imported from c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\__init__.py

3.14.6 imported from c:\users\smart gadget\appdata\local\programs\python\python37\lib\site-packages\tox\__init__.py

**Comment by Gallaecio** [comment]
Could you remove the comment lines from your `tox.ini` file and try again?

**Comment by faizan2700** [comment]
Just tried that. But it gives the same output error of no quotation mark as described above.
Is there any other way to run tests? I have tried pytest command too but some tests fail in that ( the branch I checked it with is identical with scrapy/master ). I think I am missing something here do I have to update something before runnings tests?

**Comment by faizan2700** [comment]
@Gallaecio thanks a lot for your help with this.

**Comment by Gallaecio** [comment]
If you look at `tox.ini`, you will see that it installs some additional dependencies before running the tests. You should create a virtual environment, install all requirements and run the tests there.

**Pull request merged**
