### PR TITLE
2.6.3

### PR DESCRIPTION
**Pull request by Gallaecio**

### CODE REVIEW

**Comment by kmike** [comment]
Should we backport https://github.com/scrapy/scrapy/pull/5632/ as well?

**Comment by kmike** [comment]
Do failing tests mean https://github.com/scrapy/scrapy/pull/5617 needs to be ported as well?

**Comment by Gallaecio** [comment]
I think so, and I think it may not be the only one.

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/5639 seems to be the only remaining issue.

**Comment by Gallaecio** [comment]
A Scrapy patch release coming up…

**Pull request merged**
