### PR TITLE
docs(README.rst): make install command copyable

### PR DESCRIPTION
**Pull request by armujahid**
Add copy to clipboard button in install command

### CODE REVIEW

**Comment by kmike** [comment]
This might break setup.py, which reads README.rst; I'm not sure pypi long_description supports all instance.
Could you please use https://twine.readthedocs.io/en/stable/#twine-check to see if it's ok to use this markup?

**Comment by armujahid** [comment]
I am getting below result with and without my patch. It's passing with warnings
```
python setup.py sdist bdist_wheel
twine check dist/*
Checking dist/Scrapy-2.6.2-py2.py3-none-any.whl: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`.                                                                                                          
Checking dist/Scrapy-2.6.2.tar.gz: PASSED with warnings
WARNING  `long_description_content_type` missing. defaulting to `text/x-rst`. 
```

**Comment by armujahid** [comment]
Rebased so that CI twine check could run. Everything except windows/tests are green which are unrelated.

**Review by kmike — APPROVED** [review]
Thanks @armujahid!

**Review by Gallaecio — APPROVED** [review]

**Pull request merged**
