### PR TITLE
Move CrawlerProcess to scrapy/utils/command.py

### PR DESCRIPTION
**Pull request by Curita**
Discussed in #873

### CODE REVIEW

**Comment by kmike** [comment]
I tried using CrawlerRunner in a script, and there were (unsurprising) surprises - for example, Ctrl+C didn't work properly. For me it looks like for script usage CrawlerProcess is a better fit, and CrawlerRunner is better if you have some Twisted-based service and want to run Scrapy in the same reactor. It is a problem because we document script usage with CrawlRunner. Just some thoughts, maybe they are not related to this PR :)

**Comment by Curita** [comment]
We could document both and describe what to expect from them I think. In that case maybe it's best to keep CrawlerProcess in `crawler.py`.

**Comment by chekunkov** [comment]
@kmike 

>  For me it looks like for script usage CrawlerProcess is a better fit, and CrawlerRunner is better if you have some Twisted-based service and want to run Scrapy in the same reactor

ScrapyRT uses CrawlerProcess to run multiple crawlers in the same reactor with Twisted server - it reuses code from `__init__` and `_stop_logging`. But probably you are right and CrawlerRunner is a better fit - I should review the code as Scrapy core changed a bit since ScrapyRT core was developed.

**Comment by Curita** [comment]
I'm going to close this PR until we decide to reallocate CrawlerProcess again, seems like it's good where it is right now.

**Pull request closed without merging**
