### PR TITLE
Feature: XmlItemExporter can use custom tags for iterables.

### PR DESCRIPTION
**Pull request by lorlouis**
At the moment scrapy exports element in a list using the <value> tag and it is impractical to change this behavior.
My patch aims to make exporting an xml according to a specified formal easier.

- the function is 100% retro compatible
- you can define the default tag to be anything else using the "default_key" argument
- you can specify custom names for elements in a given iterable field using the "serialized_keys" dictionary 
e.g. serialized_keys={'array1':'CustomNameForArray1Elements'}
- you can choose to enable derived names so that fields with a plural name have elements with the same name but singular.
e.g. fruits[]'s elements will have the fruit tag

### CODE REVIEW

**Comment by Gallaecio** [comment]
I have several doubts about this.

I think an easier and more flexible approach would be to move list serialization into a separate method, so that subclassing the default XML exporter to cover these use cases is much easier.

**Comment by lorlouis** [comment]
Would you prefer to get rid of theses features or keep them in the new method?

**Comment by Gallaecio** [comment]
I would personally just extract that into a method, so that it’s easy to implement what you want in a subclass. I feel like the flexibility that your changes bring is not worth 3 Scrapy settings.

But maybe we should wait for other people to give their opinion, there is no need to rush a decision.

**Comment by lorlouis** [comment]
We have been using scrapy at jobillico and we use xml to encode lots of data between internal and external systems so I thought packaging our solution more neatly into the repo would be a good idea, but it is true that more control over xml output isn't that useful for smaller projects.

**Comment by lorlouis** [comment]
I removed the features their tests and moved the serialization of list like items into it's own method.

**Comment by Gallaecio** [comment]
What I had in mind was something more in the lines of #4161. What do you think?

**Pull request closed without merging**
