### PR TITLE
Update test-standard link in contributing docs

### PR DESCRIPTION
**Pull request by gliptak**
correcting

```
arning, treated as error:
/home/runner/work/scrapy/scrapy/docs/contributing.rst:216:unknown document: twisted:core/development/policy/test-standard
ERROR: InvocationError for command /home/runner/work/scrapy/scrapy/.tox/docs/bin/sphinx-build -W -b html . /home/runner/work/scrapy/scrapy/.tox/docs/tmp/html (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   docs: commands failed
```

### CODE REVIEW

**Comment by wRAR** [comment]
The test now says

> /home/runner/work/scrapy/scrapy/docs/contributing.rst:216:unknown document: twisted:core/development/test-standard

**Comment by gliptak** [comment]
@wRAR this seem to be the page available https://docs.twisted.org/en/stable/development/test-standard.html

maybe cross linkage works differently

**Comment by Gallaecio** [comment]
I think we may need to remove `core/` as well.

**Comment by gliptak** [comment]
Thanks @Gallaecio updated

**Review by wRAR — APPROVED** [review]

**Comment by Gallaecio** [comment]
Thanks!

**Pull request merged**
