### PR TITLE
Fix argument type (int -> bool)

### PR DESCRIPTION
**Pull request by azenkwed**
Fix warning: Expected type 'bool', got 'int' instead.

Changing value from **1** to **True** for parameter **doseq** as per the documenation of [urllib.parse.urlencode()](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode)

### CODE REVIEW

**Comment by elacuesta** [comment]
Looks good, thanks. FYI, I merged the master branch because the diff was showing some changes that were already merged in #4940.

**Review by elacuesta — APPROVED** [review]

**Review by elacuesta — CHANGES_REQUESTED** [review]
Actually, I just found a few more occurrences, could you update them as well?
```
$ grep -rni "doseq=1" .
./tests/spiders.py:48:        url = self.mockserver.url(f"/follow?{urlencode(qargs, doseq=1)}")
./tests/spiders.py:248:            url = self.mockserver.url(f"/follow?{urlencode(qargs, doseq=1)}")
./scrapy/commands/bench.py:53:        url = f'{self.baseurl}?{urlencode(qargs, doseq=1)}'
```

**Comment by azenkwed** [comment]
> Looks good, thanks. FYI, I merged the master branch because the diff was showing some changes that were already merged in #4940.

Yes sorry about that, I saw that, but I am not sure why that happened.

**Comment by kmike** [comment]
Hey! I'm merging this PR, as it is an improvement over what we have now, but @elacuesta's comment is valid.

**Pull request merged**
