### PR TITLE
HTML Conventions

### PR DESCRIPTION
**Pull request by FJMonteroInformatica**
I have updated the HTML files following SonarCloud's recommendations.

### CODE REVIEW

**Comment by Gallaecio** [comment]
I don’t get why, but I have no argument against it either.

**Comment by FJMonteroInformatica** [comment]
Hello, this is my first PR. Is the failure in the tests necessarily an error in the modification I have entered? It seems strange to me because they are very small changes.

**Comment by Gallaecio** [comment]
Sadly we have a few tests in Scrapy that fail randomly. Do not worry about it.

**Review by Gallaecio — APPROVED** [review]

**Comment by kmike** [comment]
I'm also unsure what's the advantage, but the changes look fine, let's merge them :)

**Pull request merged**
