### PR TITLE
Update tutorial.rst: clarify how to run spider

### PR DESCRIPTION
**Pull request by JessA-L**
When I used the tutorial, I was confused about how to run the spider again. I later realized that I never exited the Scrapy shell. 

This edit should provide more guidance to future users of Scrapy and the tutorial.

### CODE REVIEW

**Comment by wRAR** [comment]
I'm not convinced we should expect users to not understand the difference between console commands and Python code :-/

**Comment by JessA-L** [comment]
Hi, thanks for your quick reply. 

I’m proposing this change because I had to troubleshoot it myself. Another fellow student had issues at this section as well. Further, Scrapy is used by others who aren’t super familiar with the command line, like those in the marketing field. The tutorial begins with references to basic python instruction, so it seems like it targets unexperienced users.

**Comment by wRAR** [comment]
Yeah, it makes sense, but in that case I'd want something more general or something written in the beginning of the tutorial that explains these basics, as the proposed "exit the scrapy shell" line would be OK in a differently structured doc (one that expected a single terminal opened in a specific directory and showed exact commands one after another,  with "now open the scrapy shell", "now close it and run scrapy crawl" etc. steps) but looks out of place to me in this somewhat more abstract tutorial.

@Gallaecio what do you think?

**Review by Gallaecio — APPROVED** [review]
I think the proposed changes are great. While I agree with @wRAR’s points for general documentation, I think in a tutorial specifically hand-holding is more important than not repeating yourself.

**Review by wRAR — APPROVED** [review]

**Comment by wRAR** [comment]
Thanks!

**Pull request merged**
