### PR TITLE
Pin mitmproxy to < 8 for now.

### PR DESCRIPTION
**Pull request by wRAR**
Related to #5454 

Should this go into 2.6.2?

### CODE REVIEW

**Comment by Gallaecio** [comment]
> Should this go into 2.6.2?

Makes sense to me, we definitely need to run tests as part of the release process and it would be great for them not to break :)

**Review by Gallaecio — APPROVED** [review]

**Comment by wRAR** [comment]
Rebased onto 2.6

**Comment by wRAR** [comment]
Should this be merged?

**Comment by Gallaecio** [comment]
I am porting this to the main branch as well.

**Pull request merged**
