### PR TITLE
[MRG+1] [1.1.x][backport] #1766, #1770, #1750, #1662, #1765

### PR DESCRIPTION
**Pull request by redapple**
Cherry-picked commits from:
- https://github.com/scrapy/scrapy/pull/1767
- https://github.com/scrapy/scrapy/pull/1771
- https://github.com/scrapy/scrapy/pull/1750
- https://github.com/scrapy/scrapy/pull/1662
- https://github.com/scrapy/scrapy/pull/1765

into 1.1 branch

- [x] Update 1.1 release notes

### CODE REVIEW

**Comment by redapple** [comment]
Are these worth it for 1.1?

- https://github.com/scrapy/scrapy/pull/1750
- https://github.com/scrapy/scrapy/pull/1662

**Comment by redapple** [comment]
Also missing: release notes update.

**Comment by eliasdorneles** [comment]
Looks good!

**Comment by eliasdorneles** [comment]
@redapple is it easy to include #1765 here too?

**Comment by redapple** [comment]
@eliasdorneles , done.
Release notes still need update:
> The previously bundled scrapy.xlib.pydispatch library was deprecated and replaced by pydispatcher.

**Comment by redapple** [comment]
@eliasdorneles , nevermind. reads good enough

**Pull request merged**
