### PR TITLE
PY3 port scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware

### PR DESCRIPTION
**Pull request by nyov**
Kindly let me know if the reorganized testcases are okay, I have some trouble finding the best organization here.

(Side note; I watched Eugene’s talk on "Sustainable way of testing your code" from EuroPython, but had some trouble to follow the video. Are those slides available somewhere?)

### CODE REVIEW

**Comment by kmike** [comment]
I think that your changes are fine; these tests look over-complicated and hard to read from the beginning.

**Comment by kmike** [comment]
Should we uncomment some tests after the merge?

**Comment by nyov** [comment]
Oh indeed, ouch ouch. I missed this because I always ran them explicitely this time
(`tox -e py34 -- tests/test_downloadermiddleware_robotstxt.py`)
So removing `tests/test_downloadermiddleware_robotstxt.py` from the blocks should be safe now.

**Comment by kmike** [comment]
Thanks, I'll commit this change now.

**Pull request merged**
