### PR TITLE
[MRG+1] add item_error to be catchable

### PR DESCRIPTION
**Pull request by chainly**
add item_error to be catchable (ie. by `extension` with `signal`).

### CODE REVIEW

**Comment by lucywang000** [comment]
@chainly can you explain the motivation for this, like a typical use case to justify this new signal? What's more I think a new test case is required.

**Comment by chainly** [comment]
I want to count how many `item` dropped by unhandled exception occurred in `pipeline` easily ,  but only printed in log.

**Comment by kmike** [comment]
This feature makes sense to me, and implementation looks good. The only question I have is why Failure is returned, not an exception, like in item_dropped?

**Comment by chainly** [comment]
1. There are mistake in test case(`self.run.itemerror` ==> `self.run.itemresp`), now fix. Thanks to the question : )
2. For the question: if someone need `traceback`, `Failure` a good choise, see the doc [failure.Failure](https://github.com/twisted/twisted/blob/twisted-18.4.0/src/twisted/python/failure.py#L167-L174), and [failure.Failure.getTracebackObject](https://github.com/twisted/twisted/blob/twisted-18.4.0/src/twisted/python/failure.py#L540). Why lost, not known.

**Comment by whalebot-helmsman** [comment]
@chainly Problem with unit-tests was fixed in master. Can you merge master to this PR?

**Comment by chainly** [comment]
OK, fast-forwarded and push again.

**Pull request merged**
