### PR TITLE
[MRG+1] support namespace prefix in xmliter_lxml

### PR DESCRIPTION
**Pull request by tpeng**

### CODE REVIEW

**Comment by kmike** [comment]
@tpeng I wonder why are you using this code. We have some evil plans to remove it from Scrapy (see https://github.com/scrapy/scrapy/issues/1063), or to move it to some other place. 

But I'm not familiar enough with xmliter_lxml - is it really better than scrapy.utils.iterators.xmliter? If so, does it make sense to move it to scrapy.utils.iterators? Or maybe even use it by default?

**Comment by pablohoffman** [comment]
@tpeng bump to @kmike question

**Comment by tpeng** [comment]
@kmike sorry for the delay. the original reason was i found the `xmliter_lxml` is memory efficient and can work with the xml i used. `scrapy.utils.iterators.xmliter` didn't work if the namespace is not empty.

**Comment by kmike** [comment]
See also: https://github.com/scrapy/scrapy/pull/605 which introduces a third way to parse XML iteratively in Scrapy.

**Comment by nyov** [comment]
In #1063 it was decided to keep `xmliter_lxml` in favor of `xmliter`.
Let's merge this before the relocation.

**Comment by kmike** [comment]
+1 to merge it.

**Pull request merged**
