### PR TITLE
Remove obsolete S3FeedStorage instancing without AWS credentials

### PR DESCRIPTION
**Pull request by ashellunts**
I have taken this PR https://github.com/scrapy/scrapy/pull/4411 and added fix for a failure in tests (not used import).

I hope @nyov is fine with that.

https://github.com/scrapy/scrapy/issues/4356

### CODE REVIEW

**Comment by ashellunts** [comment]
@Gallaecio @wRAR can you review please?

**Comment by ashellunts** [comment]
Can this be merged?

**Comment by ashellunts** [comment]
Hi @Gallaecio. Can this PR be merged? Or something missing?

**Comment by kmike** [comment]
@ashellunts looks good, thanks! 

We require +1's from 2 core team members before a merge; @Gallaecio approved it, but another commiter haven't reviewed it until now, that's why it was not merged.

**Pull request merged**
