### PR TITLE
Issue #5366 Move from optparse to argparse

### LINKED ISSUE #5366: Move from optparse to argparse
The [optparse](https://docs.python.org/3/library/optparse.html) module has been deprecated since `3.2` in lieu of [argparse](https://docs.python.org/3/library/argparse.html).

At the time of this writing, we only have 3 modules that use it directly:

- https://github.com/scrapy/scrapy/blob/master/scrapy/cmdline.py
- https://github.com/scrapy/scrapy/blob/master/scrapy/commands/__init__.py
- https://github.com/scrapy/scrapy/blob/master/tests/test_commands.py

I'm filing this ticket to keep track of this task. In addition there were several attempts on this in the past that hasn't pushed through:

- https://github.com/scrapy/scrapy/pull/1118
- https://github.com/scrapy/scrapy/pull/829

### PR DESCRIPTION
**Pull request by alexpdev**
Update deprecated optparse it's equivalent in argparse  (#5366 )

(edit) fixes #5366

### CODE REVIEW

**Comment by alexpdev** [comment]
I'm working on a fix for the coverage gaps.

**Comment by alexpdev** [comment]
Hello... Let me know if I missed something. 
Thanks

**Comment by alexpdev** [comment]
I adjusted the help message formatter.  CLI help messages are now almost identical to how they looked using the optparse module.

**Comment by alexpdev** [comment]
I am having trouble understanding what the errors mean.  
Are they my fault?

**Comment by elacuesta** [comment]
There seems to be a problem when determining the correct `testfixtures` version to install, due to the (not so) new pip dependency resolver. Could you try pinning `testfixtures`? Since it's for tests, the most recent version should be fine.

**Comment by alexpdev** [comment]
> There seems to be a problem when determining the correct `testfixtures` version to install, due to the (not so) new pip dependency resolver. Could you try pinning `testfixtures`? Since it's for tests, the most recent version should be fine.

Sure thing.   Now it looks like it is failing on a different dependency?

**Comment by alexpdev** [comment]
Okay.  Let me know if any further actions are needed.

Thanks

**Comment by Gallaecio** [comment]
The unrelated issues should be fixed now. Please, undo any unrelated change made to address those (e.g. https://github.com/scrapy/scrapy/pull/5374/commits/3290e4d996799f25d36bf7da6c895e459a066932).

**Comment by alexpdev** [comment]
> The unrelated issues should be fixed now. Please, undo any unrelated change made to address those (e.g. [3290e4d](https://github.com/scrapy/scrapy/commit/3290e4d996799f25d36bf7da6c895e459a066932)).

No problem, they have all been reversed.

**Comment by alexpdev** [comment]
> > The unrelated issues should be fixed now. Please, undo any unrelated change made to address those (e.g. [3290e4d](https://github.com/scrapy/scrapy/commit/3290e4d996799f25d36bf7da6c895e459a066932)).
> 
> Working on it.

Okay all fixed.

**Review by wRAR — APPROVED** [review]

**Review by Gallaecio — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
