### PR TITLE
[MRG+1] Fixed choosing of response class.

### PR DESCRIPTION
**Pull request by matveinazaruk**
Hey scrapy team!

This fix is connected to [this](https://github.com/scrapy/scrapy/issues/2000) issue. 
Little changes performed will fix detecting of response type. Seems that passing `body` into `responsetypes.from_args(...)` was missed. 

It caused a little incomprehension when I expected text type, and it should be text, but I had a simple `Response`, not `TextResponse`. 

Thanks, 
Matvei.

### CODE REVIEW

**Comment by matveinazaruk** [comment]
Hey scrapy team. 
What should I do to promote this little fix?

**Comment by redapple** [comment]
@matveinazaruk ,
could you add a test for this change?

**Comment by matveinazaruk** [comment]
@redapple Thanks for remark. Done!
Also, As I've investigated it was setting simple `Response` in case of all types of request and all expected types of bodies. 
Now it fixed for http 1.1.

Can you check please?

**Comment by redapple** [comment]
Looks good to me.
Thanks @matveinazaruk

**Pull request merged**
