### PR TITLE
Added Python 3.3+ to readme

### PR DESCRIPTION
**Pull request by mgachhui**
Added Python 3.3+ to readme, as referenced in #1961

### CODE REVIEW

**Comment by nyov** [comment]
Duplicate of #1972.
Please close.

**Comment by mgachhui** [comment]
I thought I had to make separate PRs for separate branches?

**Comment by nyov** [comment]
Oh, sorry! Please excuse my ignorance.

**Comment by redapple** [comment]
thanks @mgachhui , I cherry-picked it into master in https://github.com/scrapy/scrapy/commit/aecc23d24a801f8b7c50497bc37a0c0a2e37e173

**Pull request closed without merging**
