### PR TITLE
Fix tests that expect a specific warning

### PR DESCRIPTION
**Pull request by whalebot-helmsman**
Two fixes a here:
- solution for https://github.com/pypa/pip/issues/9215 in our python3.8 environment. https://github.com/scrapy/scrapy/pull/5146/checks?check_run_id=2570524886 python3.8 runs are killed by 6 hours timeout now.
- don't rely on warnings order in tests

### CODE REVIEW

**Review by Gallaecio — APPROVED** [review]
I wonder if the first issue could be solved by updating https://github.com/scrapy/scrapy/blob/master/tests/upper-constraints.txt with additional contraints, or updating the existing constraints. But it could break again any time in the future. So maybe it’s OK to use an old pip where the issue occurs.

About the second change, I think the current tests are correct in that they make sure that the only exceptions that happen are the expected exceptions. It should not happen that unrelated exceptions are caught. But unexpected exceptions have been leaking from unrelated tests for a while in Scrapy, so maybe this change is OK as well.

+0.5 from be for both changes. Even if they do not address the root issues, they make tests less fragile. And fragile tests are a waste of time.

**Comment by whalebot-helmsman** [comment]
> I wonder if the first issue could be solved by updating https://github.com/scrapy/scrapy/blob/master/tests/upper-constraints.txt with additional contraints, or updating the existing constraints. But it could break again any time in the future. So maybe it’s OK to use an old pip where the issue occurs.

tox creates environments with latest pip available for python (3.8 in our case), so using constraints doesn't help here

**Comment by whalebot-helmsman** [comment]
> About the second change, I think the current tests are correct in that they make sure that the only exceptions that happen are the expected exceptions. 

The problem is there is a race condition in https://github.com/scrapy/scrapy/blob/ee682af3b06d48815dbdaa27c1177b94aaf679e1/scrapy/extensions/telnet.py#L72 . Without return it leads to `ResourceLeakedWarning`. With return it creates closing socket after engine stop

**Comment by kmike** [comment]
> The problem is there is a race condition

Sorry @whalebot-helmsman, could you please elaborate? Arre you saying that there is a bug in telnet extension, and that's the reason for extra warnings? Would it make sense to fix the bug instead of fixing the tests? I think I'm missing something obvious :)

**Comment by whalebot-helmsman** [comment]
This race condition somewhere in `@inlineCallbacks`-`send_deffered_signal`-`engine.close`complex, extension is only a collateral damage. It should be fixable somehow.

**Comment by pawelmhm** [comment]
@whalebot-helmsman  about fixing tests. Is it supposed to fix all possible tests failures? Because here in my PR I see some failures about mitmproxy installation and some about tox. https://github.com/scrapy/scrapy/issues/5166 is your PR fixing "no matching distribution for tox" errors? https://github.com/scrapy/scrapy/pull/5175/checks?check_run_id=2772942979

We had some talk recently with @Gallaecio about using tox in github actions. This test failure seems to indicate that tox can be a burden. I don't really understand why it fails now, do you know @whalebot-helmsman ? I test with Python 3.9.5 locally and I'm able to install tox locally, so why it says no matching version in github build?

**Comment by wRAR** [comment]
This changes the checks in test_engine because of a problem apparently specific to that test suite (though I'm not sure we can't get the same race outside it) but the problem is more generic as we check warnings in other test cases too.

Should we change this for all cases to search for a specific warning in the list? Or should we decide that we actually want to check that only the specific warnings are raised (though in this case we shouldn't only check the first one in the list but also the list size) and filter unwanted but expected ones with e.g. a global warning filter?

**Comment by Gallaecio** [comment]
I suggest we implement a function in the tests that is meant to (eventually) check for a perfect match, and have all warning checks use that.

However, we make the first implementation of the function ignore specific warnings that we know happen due to race conditions. Or, if we cannot reliable determine which warnings are those, make the function ignore any unexpected warning.

If we ever work on solving the issue we can modify just that 1 function to be more strict.

It has not always been my position, but at the moment I would rather have unexpected warnings in production be reported to us by users instead of found by CI, than have CI fail intermittently.

**Comment by kmike** [comment]
The warnings in test_engine are addressed in https://github.com/scrapy/scrapy/pull/5561.

**Comment by wRAR** [comment]
As both the pip issue and the test_engine deprecation warning issue have been fixed this is no longer needed.

**Pull request closed without merging**
