### PR TITLE
[CRAWLERA-6600] Renaming scrapy-crawlera to scrapy-zyte-proxy

### PR DESCRIPTION
**Pull request by zloidemon**
Blocked by scrapy-crawlera [PR-96](https://github.com/scrapy-plugins/scrapy-crawlera/pull/96).

### CODE REVIEW

**Comment by zloidemon** [comment]
@Gallaecio could you please look at this PR?

**Comment by zloidemon** [comment]
> Blocked by scrapy-crawlera [PR-96](https://github.com/scrapy-plugins/scrapy-crawlera/pull/96).

Merged [PR-97](https://github.com/scrapy-plugins/scrapy-zyte-smartproxy/pull/97)

**Comment by zloidemon** [comment]
@Gallaecio Who can merge?

**Comment by Gallaecio** [comment]
We usually wait for a second maintainer to approve changes before merging, but in this case I think we can just merge.

**Pull request merged**
