### PR TITLE
Changed test_fixed_delay(fixes #4268)

### LINKED ISSUE #4268: Random failures in CrawlTestCase.test_fixed_delay
On some test runs `CrawlTestCase.test_fixed_delay`  fails with
```
>       yield self._test_delay(total=3, delay=0.1)
E   twisted.trial.unittest.FailTest: twisted.trial.unittest.FailTest: True is not false : test total or delay values are too small
```

### PR DESCRIPTION
**Pull request by sakshamb2113**
changed delay to 0.11 in test_fixed_delay(). This will greatly reduce any chance of the test failing randomly.

Fixes #4268

### CODE REVIEW

**Comment by wRAR** [comment]
@Gallaecio @sakshamb2113 I didn't try this change yet, but I don't have this problem on every run anyway, so I don't know how to make sure it helps :)

**Comment by sakshamb2113** [comment]
@wRAR I wrote a simple bash script to execute the command
tox -e py3 tests/test_crawl.py::CrawlTestCase::test_fixed_delay
 for running tests multiple times.

**Comment by wRAR** [comment]
I ran the tests with the change and I got the error once. I don't know how many runs would I do to get an approximate error rate, but I'd prefer the error to be fixed completely.

**Comment by sakshamb2113** [comment]
@wRAR could you tell me what method did you use to test the function repeatedly ?

**Comment by sakshamb2113** [comment]
I have changed delay to 0.2. I have not got any error until now. @wRAR could you please check it ?

**Comment by wRAR** [comment]
> @wRAR could you tell me what method did you use to test the function repeatedly ?

Just `for i in {1..50}; tox -e py35 tests/test_crawl.py::CrawlTestCase::test_fixed_delay` and looking for the red lines manually.

**Comment by sakshamb2113** [comment]
@wRAR I have run the tests many times with delay=0.2 without any error . I guess there is no case when this value of delay is too small.

**Comment by wRAR** [comment]
Looks like it's fine with 0.2 on my machine.

**Pull request merged**
