### PR TITLE
Use psutil if available to measure RSS on memusage extension

### PR DESCRIPTION
**Pull request by dangra**
memusage extension fires immediately when the scrapy process is `exec()`'ed from another process whose max resident memory is higher than `MEMUSAGE_LIMIT_MB`.

The limitation comes from the use of stdlib `resource` package that can measure _max RSS_ and not _current RSS_. The overcome this limiation this PR proposes to use [psutil](https://github.com/giampaolo/psutil)

For a proof on how max RSS propagates across exec() calls see:

_memtest_

``` python
#!/usr/bin/env python
import os
import sys
import resource
import psutil
from argparse import ArgumentParser

def _mem():
    rss, vms = psutil.Process().memory_info()
    maxrss = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return {'maxrss': maxrss, 'rss': rss / 1024, 'vms': vms / 1024}

def _allocate_mb(mb):
    return open('/dev/urandom', 'rb').read(mb * 1024**2)

def main():
    ap = ArgumentParser()
    ap.add_argument('-a', '--allocate', type=int, default=0)
    ap.add_argument('subcmd', nargs="*")
    args = ap.parse_args()

    if args.allocate:
        _ = _allocate_mb(args.allocate)

    print("{} {}".format(_mem(), sys.argv))

    if args.subcmd:
        os.execvp(args.subcmd[0], args.subcmd)


if __name__ == '__main__':
    sys.exit(main())
```

Running it:

```
$ ./memtest -- ./memtest -a 10 -- ./memtest 
{'maxrss': 11792, 'vms': 71084, 'rss': 11792} ['./memtest', '--', './memtest', '-a', '10', '--', './memtest']
{'maxrss': 22232, 'vms': 81328, 'rss': 22232} ['./memtest', '-a', '10', '--', './memtest']
{'maxrss': 22236, 'vms': 71084, 'rss': 11992} ['./memtest']
```

See how RSS goes from 11792 to 22232 and then back to 11992, but maxrss jumps from 11792 to 22232 and is inherited by third memtest.

This is particulary problematic when running spiders inside docker containers because docker daemon can take up to GBs of RAM and its max_rss is propagated to init process of the docker container.

The following Dockerfile was used to build an image to test memtest script with docker:

``` Dockerfile
FROM ubuntu:12.04
RUN apt-get update -q && apt-get install -qy python python-dev
ADD https://raw.github.com/pypa/pip/master/contrib/get-pip.py /get-pip.py
RUN python /get-pip.py && pip install -U wheel==0.24.0
RUN pip install psutil
COPY memtest /bin/memtest
ENTRYPOINT ["/bin/memtest"]
```

then built and ran:

``` bash
$ docker build -t memtest .
...

$ docker run -it --rm memtest -- memtest -a 10 -- memtest
{'maxrss': 8021068, 'vms': 40528, 'rss': 11504} ['/bin/memtest', '--', 'memtest', '-a', '10', '--', 'memtest']
{'maxrss': 8021068, 'vms': 50772, 'rss': 21672} ['/bin/memtest', '-a', '10', 'memtest']
{'maxrss': 8021068, 'vms': 40516, 'rss': 11416} ['/bin/memtest']

$ ps v -p 26812
  PID TTY      STAT   TIME  MAJFL   TRS   DRS   RSS %MEM COMMAND
26812 ?        Ssl  649:53      0     0 26969720 8032092 12.1 /usr/bin/docker -d --iptables=false
```

See how memtest maxrss reports ~8GB which coincides with docker daemon RSS reported by @ps@ unix command.

### CODE REVIEW

**Comment by kmike** [comment]
Using psutil makes sense, but I'm a bit worried about the semantics change. 

Memusage measures the memory in a LoopingCall, on reactor "ticks". Does it mean that if we measure current memory usage, and an user parses e.g. a huge HTML file in a callback or creates a large image, measured memory usage won't account for these spikes because measures are taken in between? If a callback is doing this for all pages it may happen that average spider memory consumption can be e.g. 2GB while MemoryUsage extension sees only 200MB.

**Comment by dangra** [comment]
The memusage extension is designed to trigger a **friendly** shutdown when it goes above a soft limits. It can't prevent python processes from consuming all available memory, any hard limits should be enforced by the environment (docker, lxc, ...).

For the case you describe it is OK if process's memory spikes but doesn't reach the hard limit, if it does it will be terminated by system, and if not it has a chance to finish successfully even when it gradually increase memory usage and reaches the soft limit.

I understand the semantics changes but for me it is more useful and practical this way.

**Comment by curita** [comment]
I'd rather prefer `psutils` having a max rss option like `resource` (or a workaround in `resource` to reset the max rss in `exec()` calls though I guess this is system dependent, os x resets it for example), but I think extending support of memusage to windows is a good enough reason to support `psutils`.

I can see somebody relying entirely on memusage instead of forcing hard limits in the env, but I agree that's probably not the way they should handle that. For memory spikes between checks decreasing the loopcall interval with the setting proposed in #1282 should help a little.

Before/If this pull request gets merged, can we log which library is being used? I think that'll make things slightly easier to debug. Also, could we add `psutils` as optional dependency to the package?

**Comment by dangra** [comment]
> I'd rather prefer psutils having a max rss option like resource (or a workaround in resource to reset the max rss in exec() calls though I guess this is system dependent, os x resets it for example),

For completeness, can you share the output of `./memtest -- ./memtest -a 10 -- ./memtest` on OSX ? 

> but I think extending support of memusage to windows is a good enough reason to support psutils.

Indeed.

> I can see somebody relying entirely on memusage instead of forcing hard limits in the env, but I agree that's probably not the way they should handle that.

It is not possible to rely on memusage even if it trigger on maxrss, this extension is a gentleman kindly asking your crawler to stop because it is using too much resources but it won't prevent taking your system down.

> For memory spikes between checks decreasing the loopcall interval with the setting proposed in #1282 should help a little.

#1282 is fine, but not sure how it helps with the case Mikhail describes, the allocated memory will be free immediately after used in spider callbacks.

> Before/If this pull request gets merged, can we log which library is being used? I think that'll make things slightly easier to debug. Also, could we add psutils as optional dependency to the package?

Yes! I'd love to add some tests too before merging.

**Comment by dangra** [comment]
What do you about using a daemon thread to collect the memory samples?

**Comment by kmike** [comment]
Collecting samples in a thread makes sense. In this case it is better to increase the frequency and measure it every second or half second; it will give us a behaviour closer to the existing.

> this extension is a gentleman kindly asking your crawler to stop

This is not how we [document](http://doc.scrapy.org/en/latest/topics/extensions.html#module-scrapy.extensions.memusage) it: "closes the spider when [the memory used by the Scrapy process] exceeds a certain value". It may worth adding a note.

**Comment by kmike** [comment]
With a LoopingCall psutil-based extension will be doing something completely different; I don't like the idea of having a single extension which does completely different things based on whether a python package is installed. It may be better to have 2 extensions in this case IMHO.

**Comment by nramirezuy** [comment]
What about creating `BackendLike` objects to control the 2 different behaviours. Each object will implement how to check for limits and start the task; the middleware implements the rest (logging; mail alert; closing the spider).

I think default we should keep the same. But I'm not sure what to do with windows users; probably just adding a note on the documentation telling them to use the other back end is enough.

**Comment by curita** [comment]
> For completeness, can you share the output of ./memtest -- ./memtest -a 10 -- ./memtest on OSX ?

Sure, here it is:
```bash
$ ./memtest -- ./memtest -a 100 -- ./memtest
{'maxrss': 8810496, 'vms': 2469576L, 'rss': 8604L} ['./memtest', '--', './memtest', '-a', '100', '--', './memtest']
{'maxrss': 113778688, 'vms': 2570956L, 'rss': 111112L} ['./memtest', '-a', '100', '--', './memtest']
{'maxrss': 8699904, 'vms': 2460360L, 'rss': 8496L} ['./memtest']
```

> #1282 is fine, but not sure how it helps with the case Mikhail describes, the allocated memory will be free immediately after used in spider callbacks.

Oh, didn't know the LoopingCall waited for callbacks to finish, I thought the problem was that we weren't sampling frequently enough. In that case it makes sense to use a different thread for checking memory.

> What about creating BackendLike objects to control the 2 different behaviours.

It may be difficult if implementing the thread logic deviates too much from memusage code, but +1 if possible.

**Comment by dangra** [comment]
> > What about creating BackendLike objects to control the 2 different behaviours.
> It may be difficult if implementing the thread logic deviates too much from memusage code, but +1 if possible.

I prefer the BackendLike approach too, @nramirezuy has a good point about reusing middleware code for logging, mail and closing spider.

**Comment by jschilling1** [comment]
i'm having memory issues with one of my spiders, so i've been calling `psutil.Process().memory_info_ex().rss / 1024 ** 2` in spider_closed to keep an eye on it, that call returns 114MB mb for a test run which is exactly what i need, `dl_stats.get('memusage/max') / 1024 ** 2` returns 1323MB on the same run which is useless, i do hope you switch to psutil

**Pull request closed without merging**
