### PR TITLE
[MRG+1] prioritize default headers over user agent middlewares

### LINKED ISSUE #2088: DEFAULT_REQUEST_HEADERS can't set User-Agent
If I use DEFAULT_REQUEST_HEADERS to set `User-Agent`, it doesn't work.

```python
DEFAULT_REQUEST_HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, sdch',
    'Accept-Language': 'en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4',
}
```

I know I can set `User-Agent` for  crawler  by using USER_AGENT setting key:

```python
# settings.py
USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36'
```

I think this behaviour is not corresponding with the doc [User Agent](http://doc.scrapy.org/en/latest/topics/settings.html#user-agent) and [DefaultHeadersMiddleware](http://doc.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware) (_This middleware sets all default requests headers specified in the DEFAULT_REQUEST_HEADERS setting._)

If this behaviour is designed, maybe the doc should be modified.

Thanks.

### PR DESCRIPTION
**Pull request by eLRuLL**
fixes #2088

### CODE REVIEW

**Comment by redapple** [comment]
@eLRuLL , I suspect this is related to https://github.com/scrapy/scrapy/issues/2088, right?

**Comment by eLRuLL** [comment]
Yes, I commented on the issue the reason behind this change

**Comment by kmike** [comment]
+1 to merge it, but I'm not sure we should backport it to 1.1 branch.

**Comment by redapple** [comment]
Right, let's keep this for 1.2 and mention the backward incompatiblity accordingly in the release notes

**Comment by djunzu** [comment]
Is Scrapy using semantic versioning?
Anyone expecting semantic versioning also expects no backward-incompatible changes in minor increments!
(Maybe it should go for v2.0?)

**Pull request merged**
