### PR TITLE
[MRG+1] BF: fail if docs failed to build

### PR DESCRIPTION
**Pull request by yarikoptic**
Otherwise build seems to succeed (exit code 0) whenever it does not

### CODE REVIEW

**Comment by kmike** [comment]
It makes sense, but I wonder why was `-` [added](https://github.com/scrapy/scrapy/commit/ff987fb5a571ba91cb4e8bd0472e94579acbf2a2) in first place. /cc @curita

**Comment by curita** [comment]
I added it so the `linkcheck` build doesn't break if there are invalid links, and then `linkfix` can fix those invalid links from `linkcheck` output.

I didn't find a way to ignore the exit code in build dependencies at the time (it ignores it in a per-command basis prefixing that `-` sign), but it wasn't the best way to deal with it. This pull request breaks `linkfix` because of that, @yarikoptic maybe be you could copy the commands needed to run `linkfix` inside its declaration so it doesn't rely on the other builds so we can fix it?

**Comment by yarikoptic** [comment]
In none of my environments (sweep of Debian and ubuntu releases, now available from NeuroDebian) I believe build failed due to that. In which environment it failed for you before due to broken links?

**Comment by curita** [comment]
If you run `make linkfix` with your fix you'll see that building `linkcheck` finishes with problems currently, so the additional commands in the `linkfix` build are never ran (and they should, since `linkfix` fixes those problems in the `linkcheck` build). You can verify this by not seeing the "Fixing redirecting links in docs has finished; ..." message at the end of the build.

**Comment by yarikoptic** [comment]
Gotcha @curita -- what about smth like 5f3e1e9 ?

**Comment by curita** [comment]
Awesome! Much better fix from what I proposed, thanks :)

+1 to merge

**Pull request merged**
