### PR TITLE
[MRG+1] httpcache dont_cache meta #19 #689

### PR DESCRIPTION
**Pull request by nramirezuy**
Implementation of: #19 #689

I think doing it on the middleware is the best, because it handle it for all the policies.

### CODE REVIEW

**Comment by kmike** [comment]
Ping @nramirezuy :) It is an useful feature, and it is almost ready.

**Comment by nramirezuy** [comment]
@kmike is that doc enough? or there are other places to change?

**Comment by kmike** [comment]
@nramirezuy this flag should be also added here: https://github.com/scrapy/scrapy/blob/master/docs/topics/request-response.rst#requestmeta-special-keys

**Comment by nramirezuy** [comment]
@kmike done

**Comment by kmike** [comment]
:+1:

**Pull request merged**
