### PR TITLE
fix: pin most of the dependencies

### PR DESCRIPTION
**Pull request by azzamsa**
Fixes https://github.com/scrapy/scrapy/issues/5298

### CODE REVIEW

**Comment by Gallaecio** [comment]
The pull request does not pin any dependency at the moment. Do you wish to have it merged as is, in which case you should probably update the title, or do you plan to extend the pull request with more commits, in which case you should mark it as a draft or prepend `[WIP] ` to the title?

**Comment by azzamsa** [comment]
Oh, sorry. I use this PR just to show that some tests are failed. Probably due to upstream changes. Github does not allow a PR with no advanced commit.

**Comment by azzamsa** [comment]
Why I don't find any macOS test being run?
As the [config)(https://github.com/scrapy/scrapy/blob/3225de725720bba246ba8c9845fe4b84bc0c82e7/.github/workflows/tests-macos.yml#L2) it should run.

**Review by cristianMuntean1 — CHANGES_REQUESTED** [review]
@click.command()
@click.option("--count", default=1, help="Number of greetings.")
@click.option("--name", prompt="Your name", help="The person to greet.")
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for _ in range(count):
        click.echo(f"Hello, {name}!")

if __name__ == '__main__':
    hello()

**Comment by azzamsa** [comment]
I would like to close this pr temporary to avoid spamming, and reopen when it is ready for public.

**Pull request closed without merging**
