### PR TITLE
docs: change DOWNLOAD_DELAY description format

### PR DESCRIPTION
**Pull request by yolile**
To be consistent with the other settings' descriptions

### CODE REVIEW

**Review by Gallaecio — CHANGES_REQUESTED** [review]
I do not appreciate an improvement in the rewording.

The use of “Note” as a paragraph seems like a change for the worse. Sphinx has a directive, `note`, for that. But I am not sure a note format is right here, as this is the main place in the documentation where this spider attribute is covered.

The use of `:attr:` could be an improvement if it was pointing somewhere, but I don’t think it does.

**Comment by yolile** [comment]
Ops, sorry, fixed now. My proposal is just to be consistent with the other `DOWNLOAD_` settings description format, e.g. https://docs.scrapy.org/en/latest/topics/settings.html#download-timeout

**Comment by Gallaecio** [comment]
Makes sense. And I see that even though :attr: does not link anything, the formatting itself is a welcome change.

Thank you!

**Review by Gallaecio — APPROVED** [review]

**Review by wRAR — APPROVED** [review]

**Comment by Gallaecio** [comment]
Note before merging: someone needs to make sure it renders OK, usually the note text starts on the same line as the directive, and I am not sure the syntax used here will work.

**Comment by wRAR** [comment]
@Gallaecio web-poet uses the same syntax (even with the empty line in at least one place).

**Comment by wRAR** [comment]
Actually even the same docs/topics/settings.rst includes the same syntax.

Unless I've misunderstood your concerns.

**Comment by yolile** [comment]
It renders fine for me (in case this helps):
image

**Pull request merged**
