### PR TITLE
Added isort functionality and necessary config files (#5737)

### PR DESCRIPTION
**Pull request by cshel16**
Installed pre-commit functionality and hooked in isort. Also added necessary configurations for using isort and black.

**Will need to stay open until #5734 is merged, as per the issue description**

### CODE REVIEW

**Comment by Gallaecio** [comment]
Thanks!

Could you have a look at those 4 failing tests, see if you can figure out why they are failing after these changes? (I could not figure it out from a quick look at the error messages, but the issue seems to be the same in all 4)

**Comment by wRAR** [comment]
Note that some of those tests make real network requests so maybe something changed externally.

**Comment by cshel16** [comment]
Yes, I'll do my best to look into these problems!

**Comment by wRAR** [comment]
Implemenyed in #5806

**Pull request closed without merging**
