### PR TITLE
Update practices.rst 

### PR DESCRIPTION
**Pull request by WilliamKinaan**
Adding calling the settings object to the CrawlerRunner instance

### CODE REVIEW

**Comment by kmike** [comment]
What's the reason you want to add `get_project_settings()` to this example?

**Comment by WilliamKinaan** [comment]
that is because without adding the settings, i was getting error that the CrawlerRunner constructor needs one more argument, i checked the native code of scrapy, for this class, and the settings was an argument, when i added it to my crawler, everything worked

**Comment by WilliamKinaan** [comment]
that is because without adding the settings, i was getting error that the
CrawlerRunner constructor needs one more argument, i checked the native
code of scrapy, for this class, and the settings was an argument, when i
added it to my crawler, everything worked

On Fri, Aug 21, 2015 at 4:10 PM, Mikhail Korobov <notifications@github.com>
wrote:

> What's the reason you want to add get_project_settings() to this example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scrapy/scrapy/pull/1446#issuecomment-133457363>.
>



-- 
William.

**Comment by kmike** [comment]
@WilliamKinaan what is your Scrapy version? Settings argument is optional in Scrapy 1.0 (see https://github.com/scrapy/scrapy/pull/1285) - if no settings are passed, defaults are used.

**Comment by WilliamKinaan** [comment]
my scrapy version is:
Version: 1.0.0rc1
and i can of the native code for CrawlerRunner

def __init__(self, settings):

it is not optional, is it?

**Comment by kmike** [comment]
1.0.0rc1 is a pre-release version, while the docs are for 1.0.x release. Check the current source code: https://github.com/scrapy/scrapy/blob/280eab241680c93a763a3ef3a9ccd0c257259ca0/scrapy/crawler.py#L111

**Comment by WilliamKinaan** [comment]
At least i wasn't wrong :)

Thanks

**Comment by WilliamKinaan** [comment]
And btw, (pip update) command installed this pre-released version. it should have installed the latest released version

**Comment by kmike** [comment]
> And btw, (pip update) command installed this pre-released version. it should have installed the latest released version

When did it happen? And what is your pip version?

**Pull request closed without merging**
