### PR TITLE
[MRG+1] data URI download handler.

### LINKED ISSUE #2156: Is it any plan to support downloading "data:image/jpeg;base64"
[scrapy] ERROR: Error downloading <GET data:/robots.txt>: Unsupported URL scheme 'data': no handler available for that scheme
...
scrapy.exceptions.NotSupported: Unsupported URL scheme 'data': no handler available for that scheme

I try to download a image form src attribute "data:image/jpeg;base64", But, an error happens to me.

### PR DESCRIPTION
**Pull request by ArturGaspar**
GitHub does not let me change head branch in #2175, so I have to open a new PR.

Fixes #2156

### CODE REVIEW

**Comment by redapple** [comment]
@ArturGaspar , w3lib 1.17 will be released soon (see https://github.com/scrapy/w3lib/pull/87)

**Comment by redapple** [comment]
@ArturGaspar , I relaunched the Travis builds with w3lib 1.17. All green :)

**Comment by dangra** [comment]
`FileDownloadHandler` class is in a module named `file`, `HTTPDownloadHanlder` is in a module named `http` so I would name the file `datauri.py` instead of `data.py`, it is analogous to class name `DataUriDownloadHanlder`.

**Comment by dangra** [comment]
This PR should bump required minimum w3lib version to 1.17 in scrapy's setup.py

**Comment by kmike** [comment]
Could you please rebase it on master?

There was a few other places w3lib version should be bumped, and a few other pull requests which needed this bump, so the required w3lib version is now increased in master.

**Comment by redapple** [comment]
Looks good to me.
@dangra , @kmike , what do you think?

**Comment by kmike** [comment]
@ArturGaspar looks good! 

Could you please add a test (or modify an existing test) to check other Response attributes: url, headers?

**Comment by kmike** [comment]
Looks good, thanks @ArturGaspar!

**Pull request merged**
