### PR TITLE
[MRG+2] LOG_SHORT_NAMES option to disable TopLevelFormatter

### PR DESCRIPTION
**Pull request by kmike**
Fixes https://github.com/scrapy/scrapy/issues/1309

This is a rebased version of https://github.com/scrapy/scrapy/pull/1583. 

Like in @akhillb's PR, default value is False, i.e. logs are switched to long names by default. Is that OK?

TODO:
- [x] tests
- [x] confirm that's OK to use long names by default
- [x] update output of examples in docs
- [x] add example of overriding log level for a specific Scrapy component

### CODE REVIEW

**Comment by redapple** [comment]
@kmike , can you share (in a comment or in the description of the PR) some sample console output before and after the change?

**Comment by kmike** [comment]
This is how it looks after the change: https://gist.github.com/kmike/2e4ed9f45c162481bf39c4d36e9e9920. Before the change all prefixes like `[scrapy.extensions.logstats]` were just `[scrapy]`.

**Comment by redapple** [comment]
I must say I'm quite used to short names (current behavior), but I don't remember how it was earlier.
Why will `LOG_SHORT_NAMES` be off by default? (honest question)

**Comment by kmike** [comment]
To enable or disable it by default is a controversial question which needs a discussion :) In https://github.com/scrapy/scrapy/issues/1309 @curita seems to be +1 on long names, @nramirezuy seems to be -1. 

I like long names because they make debugging easier, and they makes scrapy components more discoverable: if you see e.g. a "request is dropped" message you can see that it is caused by `[scrapy.dupefilters]`; if it is dropped by an offsite middleware you get a log message from `[scrapy.spidermiddlewares.offsite`]; if a request is dropped with "Ignoring response %(response)r: HTTP status code is not handled or not allowed" message it will point you right to `[scrapy.spidermiddlewares.httperror`]. They are more verbose, but they provide additional debugging information, that's why I think they are useful. 

A related advantage is that it is easier to understand how to customize scrapy logging - there is a direct mapping between logger name and text shown in `[brackets]` - if you find some of the messages too verbose (e.g. https://github.com/scrapy/scrapy/issues/1308) you can change log level just for this logger, and this is easy to do because you can see the logger name right away. You can do the same if option is off by default by turning it on and re-running the crawl, but it means one extra crawl which is not always feasible.

https://github.com/scrapy/scrapy/pull/2434 may help to alleviate the pain for all us who got used to `[scrapy]`: maybe we can highlight logger name using a different color, or use a different color strength for it.

**Comment by redapple** [comment]
Right @kmike , I think you've convinced me to enable long names by default. Experienced users could switch it off easily.

**Comment by kmike** [comment]
@redapple what do you think now? //cc @eliasdorneles @dangra @nyov @Digenis @curita and everyone else

**Comment by redapple** [comment]
Looks good to me. +1

**Comment by redapple** [comment]
(before I forget, and just as a note to self mainly, I've seen this for Elasticsearch -- maybe it's common in the Java world: the module has 1-letter levels, only the last one is a full name:

```
$ ./bin/elasticsearch
[2016-12-16T18:24:39,647][INFO ][o.e.n.Node               ] [] initializing ...
[2016-12-16T18:24:40,260][INFO ][o.e.e.NodeEnvironment    ] [gJGLBp4] using [1] data paths, mounts [[/ (/dev/sdb1)]], net usable_space [123.1gb], net total_space [450.5gb], spins? [possibly], types [ext4]
[2016-12-16T18:24:40,261][INFO ][o.e.e.NodeEnvironment    ] [gJGLBp4] heap size [1.9gb], compressed ordinary object pointers [true]
[2016-12-16T18:24:40,617][INFO ][o.e.n.Node               ] node name [gJGLBp4] derived from node ID [gJGLBp4PTR63XS_RAGppkQ]; set [node.name] to override
[2016-12-16T18:24:40,666][INFO ][o.e.n.Node               ] version[5.1.1], pid[15166], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/4.4.0-53-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_05/25.5-b02]
[2016-12-16T18:24:44,101][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [aggs-matrix-stats]
[2016-12-16T18:24:44,101][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [ingest-common]
[2016-12-16T18:24:44,102][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [lang-expression]
[2016-12-16T18:24:44,102][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [lang-groovy]
[2016-12-16T18:24:44,102][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [lang-mustache]
[2016-12-16T18:24:44,102][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [lang-painless]
[2016-12-16T18:24:44,102][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [percolator]
[2016-12-16T18:24:44,102][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [reindex]
[2016-12-16T18:24:44,103][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [transport-netty3]
[2016-12-16T18:24:44,103][INFO ][o.e.p.PluginsService     ] [gJGLBp4] loaded module [transport-netty4]
[2016-12-16T18:24:44,103][INFO ][o.e.p.PluginsService     ] [gJGLBp4] no plugins loaded
[2016-12-16T18:24:50,223][INFO ][o.e.n.Node               ] initialized
[2016-12-16T18:24:50,223][INFO ][o.e.n.Node               ] [gJGLBp4] starting ...
[2016-12-16T18:24:50,510][INFO ][o.e.t.TransportService   ] [gJGLBp4] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2016-12-16T18:24:50,516][WARN ][o.e.b.BootstrapCheck     ] [gJGLBp4] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2016-12-16T18:24:53,708][INFO ][o.e.c.s.ClusterService   ] [gJGLBp4] new_master {gJGLBp4}{gJGLBp4PTR63XS_RAGppkQ}{Gil2k4u_T5q8lQU-V_keoQ}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2016-12-16T18:24:53,797][INFO ][o.e.h.HttpServer         ] [gJGLBp4] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}
[2016-12-16T18:24:53,797][INFO ][o.e.n.Node               ] [gJGLBp4] started
[2016-12-16T18:24:54,570][INFO ][o.e.g.GatewayService     ] [gJGLBp4] recovered [2] indices into cluster_state
[2016-12-16T18:24:58,117][INFO ][o.e.c.r.a.AllocationService] [gJGLBp4] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
```
)

**Comment by kmike** [comment]
omg, I think I've seen something like that in Twisted docs :P

**Comment by eliasdorneles** [comment]
Looks great!

**Comment by eliasdorneles** [comment]
wait, I meant the PR looks great!
not the the `o.e.e.Node` component abbreviated names thing, that doesn't :)

**Comment by nyov** [comment]
Oh, I had not come across this and the preceding PRs somehow.
Looks nice, I first noticed long names when wrapping scrapy in another project (with custom logging).

I'd like the short names better, by default, simply for the output alignment.
But that's a matter of taste, and I'm used to scrapy enough to know which log line comes from where. I can see the pro's of having it for others.
And being easy to configure, it may not matter too much what the default is.

+1 from me, nice option, nice work.

**Comment by nyov** [comment]
@redapple, yes that seems common in the Java world. But urgh, what an ugly thing to do. You still don't know what component it came from without knowing some internals first.

**Comment by Digenis** [comment]
I'd go with the long, non-abbreviated names.

I do mind that the log lines are getting too long.
(This will get a bit off-topic)
I think this was once better solved by breaking them into multiple lines
but now I'm hesitant to write multiline log messages
because scrapy-1.0 and later releases
no longer indent multiline log messages
making it theoretically impossible¹ to have a perfect log parser
and hard² to write one that takes good guesses.

¹A parser must check if a log line does not match the configured logging format.
If it doesn't match, it definitely belongs to a log message starting above.
If it matches, it can only guess that it's a log message's first/only line.

²Pattern matching using some configured log format
is much harder than matching indented lines.

**Comment by redapple** [comment]
Alright, so we need another "official" +1. @eliasdorneles , @dangra or @curita perhaps?

**Comment by redapple** [comment]
@eliasdorneles gave me his +1 offline. So we're good to merge.

**Comment by eliasdorneles** [comment]
I had already given my +1 online (some comments above) :)

**Pull request merged**
