### PR TITLE
Deprecate the `scrapy.downloadermiddlewares.decompression` module

### LINKED ISSUE #5546: Deprecate the scrapy.downloadermiddlewares.decompression module
It is not used by default, not documented, and I found no relevant search results on the internet.

### PR DESCRIPTION
**Pull request by Laerte**
Closes #5546

### CODE REVIEW

**Comment by Gallaecio** [comment]
We have a [policy](https://docs.scrapy.org/en/latest/versioning.html#deprecation-policy) not to remove features right away, and instead issue deprecation warnings for at least 1 year.

So the change at this stage should consist of doing this in the module:

```python
from warnings import warn

from scrapy.exceptions import ScrapyDeprecationWarning

warn(
    'scrapy.downloadermiddlewares.decompression is deprecated',
    ScrapyDeprecationWarning,
    stacklevel=2,
)
```

The tests can remain there until the feature is removed.

**Comment by Laerte** [comment]
@Gallaecio Like this?

**Review by Gallaecio — APPROVED** [review]
Yes, thank you!

**Comment by kmike** [comment]
Looks good, thanks!

**Pull request merged**
