### PR TITLE
Add support for multipart upload to the S3 feed storage

### PR DESCRIPTION
**Pull request by jersub**
This PR adds support for multipart upload to the S3 feed storage. It aims to allow uploading of large files (e.g. items containing HTML from a big crawl) and to fix the issue #960.

Source snippets:
- http://boto.readthedocs.org/en/latest/s3_tut.html#storing-large-data
- boto/boto#2704

### CODE REVIEW

**Comment by kmike** [comment]
I like this feature :+1: 
It is a shame we don't have any tests for s3 uploads. 
Maybe we can use https://github.com/spulec/moto?

**Comment by eliasdorneles** [comment]
moto is pretty nice, I've used with good success for testing against boto API in a bunch of projects -- +1.

Only beware of this gotcha: https://github.com/spulec/moto/issues/416

**Comment by redapple** [comment]
@jersub , @kmike , @eliasdorneles , how can we make progress on this?
Add tests for S3 first, and then work on multipart uploads?
Move to boto3 first? (cf. #1866)
(Recent WIP on using boto3 for file uploads: #2036)

**Comment by BurnzZ** [comment]
Hi @kmike,

Any chance we could resurrect this feature? We need it in several spiders that scrape millions of items and it fails uploading to S3 due to: `An error occurred (EntityTooLarge) when calling the PutObject operation: Your proposed upload exceeds the maximum allowed size`.

Since it's been _almost 3 years_ since the last commit, would it be better to start a new issue and PR for this?

Thanks!

**Comment by Gallaecio** [comment]
I am closing this pull request, since it seems boto3 is the way to go, and I don’t think there is much a boto3-based implementation can take from this approach.

**Pull request closed without merging**
