### PR TITLE
[MRG+1] Remove --lsprof command-line option. 

### PR DESCRIPTION
**Pull request by kmike**
See #1531 for motivation.

### CODE REVIEW

**Comment by eliasdorneles** [comment]
I've already +1 -- @redapple wanna do the honors here? :)

**Comment by nramirezuy** [comment]
@kmike I've never used this option but might get someone mad xD

**Comment by kmike** [comment]
@nramirezuy it looks trivial to work around using e.g. https://pypi.python.org/pypi/pyprof2calltree

**Comment by dangra** [comment]
:monkey:

**Comment by nramirezuy** [comment]
:octopus:

**Pull request merged**
