### PR TITLE
Add support to Selectors for querying by tag name and attribute filters

### PR DESCRIPTION
**Pull request by stphivos**
Hi, I thought it would be nice to have an alternative way to xpath/re/css selectors when searching for elements, that uses python built-in dictionaries in a declarative manner. While it feels simple and familiar it still provides a lot of flexibility and expressiveness. I have included an example in scrapy/selector/querytranslator.py. If you like my idea I can also update the unit tests and docs in a new pull-request. Thanks!

### CODE REVIEW

**Comment by stphivos** [comment]
Here is the example of how the code would look like using the DmozSpider example in the docs:
```python
import scrapy


class DmozSpider(scrapy.Spider):
    name = "dmoz"
    allowed_domains = ["dmoz.org"]
    start_urls = [
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Books/",
        "http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/"
    ]

    # parse using attributes dictionary
    def parse(self, response):
        for x in response.find('li', {'class': 'list-item'}):
            title = response.inside(x).value_of('a', {'class': 'title'}, QueryComparison.contains).as_text()
            link = response.inside(x).attr_of('a', {'class': 'url'}, 'href').as_text()
            price = response.inside(x).value_of('span', {'class': 'price'}).as_float()
            print title, link, price
```

**Comment by kmike** [comment]
Hey @stphivos!

-1 from me to add this to Scrapy, BUT I like the syntax and the general idea.

I'd love to see Scrapy supporting other ways to extract data like yours, pyquery, BeautifulSoup, csselect2, as well as other backends like html5lib or gumbo-parser in addition to lxml.

Currently we're moving builtin Scrapy selectors to a separate library which can be used without Scrapy: https://github.com/scrapy/scrapy-selectors. Scrapy still will be providing shortcuts like response.xpath(..) or response.css(..), but the actual work will be done by this separate parsing library.

I'm keen to an idea of providing more (optional) shortcuts, like WebTest [does](http://webtest.pythonpaste.org/en/latest/api.html#webtest-response-testresponse): there are response.html, response.xml, response.json, response.pyquery, response.lxml attributes which provide entry points for various parsing libraries: BS, ElementTree, json, pyquery and lxml. We should think about the names, but it looks solvable.

So I think that what we need is to either refactor scrapy-selectors to allow extensions from the user code (/cc @redapple), or provide a way for users to extend Scrapy Response with more shortcuts, or do both. 

If a query language uses LXML XPaths then extending Selectors looks better because it allows to use several query languages in a single chained query - like we allow to chain CSS and XPath selectors. If the query library is not based on lxml then providing a separate method sounds fine to me.

Either way, your library could work better as a separate project in a separate repo. I'm fine with putting it under scrapy github organization if you want (/cc @dangra @pablohoffman), or creating an organization with a curated set of user-contributed projects like this (of course, if you want it there). Until scrapy-selectors or Scrapy is refactored, it'd be possible to use this library without shortcuts:

```python
from turboparse import turbo  # or whatever name you choose

# ....
for x in turbo(response).find('li', {'class': 'list-item'}):
    # ....
```

Proposals on how to refactor Scrapy or Selectors are very welcome! Someone needs to get the ball rolling.

---

Regarding syntax: why not do the following?

```python
def parse(self, response):
    for x in response.find('li', {'class': 'list-item'}):
        title = x.value_of('a', {'class': 'title'}, QueryComparison.contains).as_text()
        link = x.attr_of('a', {'class': 'url'}, 'href').as_text()
        price = x.value_of('span', {'class': 'price'}).as_float()
        print title, link, price
```

**Comment by dangra** [comment]
I fully second @kmike opinion

**Comment by stphivos** [comment]
Hey kmike, thanks for your comments. Looking at the big picture I see your point about having parsing libraries in separate modules as they are outside the scope of scrapy and need to be interchangeable.

I will study scrapy-selectors a bit more and try to propose ideas to refactor so that external dependencies are easily expanded and bridged from a central location.

I think right after scrapy-selectors are refactored, it would be easier to provide more optional shortcuts like WebTest in scrapy.

It would be great if you put this module under scrapy or separate organization if it makes more sense, with the name “markupquery” maybe? I like the syntax change you proposed it makes the code more readable. I’ve also seen some ideas in pymongo api that I intend to add to make queries more flexible.

**Pull request closed without merging**
