### PR TITLE
Add python-scrapy and python3-scrapy links

### PR DESCRIPTION
**Pull request by yaamas**
There is no official way described to download as ubuntu package in the docs.
Also, they are up to date currently.

### CODE REVIEW

**Comment by grammy-jiang** [comment]
The failure in Travis-ci is very wired. I have seen these no sense errors these days. 

Does anyone know what happens?

**Comment by lopuhin** [comment]
I think these are failures of 1.5 branch, the base was changes but probably the build was using the old base and wasn't restarted, I'll try restarting it manually.

**Comment by grammy-jiang** [comment]
hi, @lopuhin,

How things is going on? I have the same problem in my PR, and I am looking forward to passing my testings.

**Comment by kmike** [comment]
The problem is that these packages will become outdated soon - we're going to release scrapy 1.6, and then they will stay outdated for another 5 years (18.04 is a recent LTS release), right?

**Comment by nyov** [comment]
Whether they are outdated or not, I don't think there needs to be a tutorial on how to install packages in Ubuntu, here. Then the next guy wants to add a line on how to install them with aptitude or synaptic instead :p My 2 cents.
Also: `**sometimes** typically` ?

**Comment by Kogam22** [comment]
@nyov : 
>I don't think there needs to be a tutorial on how to install packages in Ubuntu, here. Then the next guy wants to add a line on how to install them with aptitude or synaptic instead :p My 2 cents.

Yup that is sensible. But it should at least be available in tavailable in the Docshe Docs right ?

**Comment by nyov** [comment]
I don't have a strong opinion either way. Only that I think people writing python scrapers are knowledgeable enough to know how to use their system package manager or build toolchain.
The dependencies are the actual package names, right? And the location is the standard system repository (`apt search scrapy` is enough to find it?), not a 3rd-party source that would require a linking, so I don't see the point really.
But I also haven't been a new user in a long time, so YMMV.

I do think the emphasis on "don't use [system packages]" could be relaxed. It's usually only the devs who think everyone should use their latest and greatest version. A version packaged and frozen 5 years ago (with dependencies) still works today as it did then. Some people might prefer that stability (until they hit on an old bug).

**Pull request closed without merging**
