### PR TITLE
S3FilesStore support for other S3 providers (botocore options)

### PR DESCRIPTION
**Pull request by otobrglez**
Hi guys!

Scrapy internally uses [botocore] for Amazon S3 data "manipulation". However there are other "S3" compatible storages that can also be used as alternative to S3 - services like [Minio] or [s3.scality].

In order to get the `S3FilesStore` to work with this and other providers [botocore] internally needs to know the `endpoint_url` and since `SSL/VERIFY` then become optional this settings can/should be set by user in `settings.py`.

This patch adds options to [botocore.session.create_client()][create_client] via:

- [x] Support for [botocore] `endpoint_url` via new `AWS_ENDPOINT_URL` scrapy setting.
- [x] Support for [botocore] `region_name` via new `AWS_REGION_NAME` scrapy setting.
- [x] Support for [botocore] `use_ssl` via new `AWS_USE_SSL` scrapy setting.
- [x] Support for [botocore] `verify` via `AWS_VERIFY` scrapy setting.

Example `setting.py` for [Minio] now looks like this:

```python
AWS_ENDPOINT_URL = 'http://minio.example.com:9000'
AWS_USE_SSL = False # or True (None by default)
AWS_VERIFY = False # or True (None by default)
AWS_ACCESS_KEY_ID = "aws_key"
AWS_SECRET_ACCESS_KEY = "aws_pass"
FILES_STORE_S3_ACL = 'public-read' 
```

Please review and marge if you feel like this is something that people might find useful. Thanks for your time and effort. Cheers!

[botocore]: https://github.com/boto/botocore
[s3.scality]: https://s3.scality.com/
[Minio]: https://github.com/minio/minio
[create_client]: https://github.com/boto/botocore/blob/develop/botocore/session.py#L709-L712

### CODE REVIEW

**Comment by kmike** [comment]
Hey @otobrglez! Thanks for the pull request; I think it is a good feature to have.

Questions:

1. Does S3 still works without defining new options? Should we add them to https://github.com/scrapy/scrapy/blob/master/scrapy/settings/default_settings.py?
2. Could you please add docs for new options?

**Comment by otobrglez** [comment]
Hey @kmike! 👋

1. It works without defining and changes to `default_settings.py`. The underlaying `botocore` library has predefined default values,...
2. I've added documentation to `settings.rst` and `media-pipeline.rst`. Hope this is enough? 

Cheers!

- Oto

**Comment by otobrglez** [comment]
@kmike or @redapple - can someone please merge this? :) Cheers!

**Comment by otobrglez** [comment]
@kmike @redapple Ping. Anyone merging this?

**Comment by dangra** [comment]
Useful and implementation looks clean. thanks!

**Pull request merged**
