### PR TITLE
[WIP] Upgrading optparse code (deprecated since Py2.7) to argparse

### PR DESCRIPTION
**Pull request by redapple**
Closes #829

### CODE REVIEW

**Comment by nyov** [comment]
+1, using argparse has been on my mind.
Why is it WIP, is something left to fix?

**Comment by nramirezuy** [comment]
I also did this :tongue: 
https://github.com/scrapy/scrapy/pull/829

**Comment by nyov** [comment]
oh. I didn't even see. Now that is a pickle, trying to choose the better PR or merging them?

**Comment by redapple** [comment]
@nyov , was a [WIP] when my first commit failed miserably...

Oh sorry @nramirezuy , I totally missed yours.
I'm fine with any, as long as I can revive https://github.com/scrapy/scrapy/pull/303

I'm not particularly fond of what's being discussed in https://github.com/scrapy/scrapy/issues/356 and https://github.com/scrapy/scrapy/pull/1048

**Comment by Gallaecio** [comment]
https://github.com/scrapy/scrapy/pull/5374

**Pull request closed without merging**
