### PR TITLE
Fix Twisted deprecation warning by using A twisted.web.http.HTTPClient with twisted.web.client.Agentgent instead of HTTPClient

### PR DESCRIPTION
**Pull request by smritisubh**

### CODE REVIEW

**Comment by smritisubh** [comment]
twisted.web.http.HTTPClient with twisted.web.client.Agent

**Comment by wRAR** [comment]
Is this from ChatGPT?

**Comment by smritisubh** [comment]
> Is this from ChatGPT?

No

**Comment by wRAR** [comment]
What generated it then?

**Pull request closed without merging**
