### PR TITLE
Simplify Publish workflow

### PR DESCRIPTION
**Pull request by Laerte**
Simplify publish workflow by using official PyPI publish action.

### CODE REVIEW

**Comment by Laerte** [comment]
💡 We could even simplify this workflow:

```yaml
name: Publish
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+(rc[0-9]+|.dev[0-9]+)?$"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: | 
          pip install --upgrade build twine
          python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
```
With this we can remove the **Check Tag** step and this action will be only executed when we push a new tag that matches our pattern.

**Review by Gallaecio — APPROVED** [review]
Thanks!

**Comment by Gallaecio** [comment]
The proposed simplification also sounds good to me. In fact, we haven’t released an rc or dev version in years, and I don’t expect us to do so any time soon, so we could even remove those 2 patterns as well.

**Comment by Laerte** [comment]
@Gallaecio I pushed the refactor, i also use the same workflow on my personal projet: https://github.com/Laerte/aes_pkcs5/blob/main/.github/workflows/publish.yml and works flawless!

**Review by Gallaecio — APPROVED** [review]
:heart:

**Comment by kmike** [comment]
Thanks @Laerte!

**Pull request merged**
