### PR TITLE
Change local docs theme

### PR DESCRIPTION
**Pull request by kmike**
In this PR local docs theme is made the same as http://doc.scrapy.org/en/latest/. This makes it easier to work on docs - after this change what you see locally is what you get on the official web site.

### CODE REVIEW

**Comment by pablohoffman** [comment]
+1 but shouldn't we update `docs/README` to point out we need to install sphinx_rtd_theme to build the doc?

**Comment by Curita** [comment]
+1, I'm using locally actually and I've always forgot to send a PR.

Not sure if necessary, there are only two packages needed after all, but we could create a `requirements.txt` file inside `docs/` like `tests/requirements.txt`.

**Comment by kmike** [comment]
@pablohoffman @Curita sphinx_rtd_theme is installed automaticaly when you install recent sphinx (1.3 works).

**Comment by pablohoffman** [comment]
@kmike great, didn't know that!

**Pull request merged**
