### PR TITLE
[MRG+1] drop deprecated "optional_features" set

### PR DESCRIPTION
**Pull request by nyov**
remove all `optional_features` support after the removal of 'boto' (#1357)

### CODE REVIEW

**Comment by nyov** [comment]
get lost, bot >:|

**Comment by kmike** [comment]
LGTM.

**Comment by nyov** [comment]
I'm sorry, I know I should try doing more tests for coverage. I'm afraid my free time for contributions has very much expired :(
It's been fun while it lasted.

**Comment by eliasdorneles** [comment]
Thanks @nyov!
This looks great actually, don't worry too much about that bot -- it's just a (noisy) metric. :)

**Pull request merged**
