### PR TITLE
Remove deprecated %z formatting from the default LOG_DATEFORMAT

### LINKED ISSUE #1270: scrapy logging show UnicodeDecodeError
hello,all, I use scrapy 1.00rc1 from pip ,my pc is win7x64,python is 2.7.9(x64),
when I start my project 
```python
scrapy crawl imzx
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 19: ordinal not in range(128)
Logged from file log.py, line 108
```
Then I find utils/log.py ,line 108 ,I commented-out the code as you can see
```python
#logger.info("Scrapy %(version)s started (bot: %(bot)s)",
                #{'version': scrapy.__version__, 'bot': settings['BOT_NAME']})
```
And I restart my project,it's OK ,but something about logging error still:
```python
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 474, in format
    s = self._fmt % record.__dict__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 19: ordinal not in range(128)
Logged from file engine.py, line 212
```
It's to much in my screen,though  too many logging Traceback , my code work fine ,I get all data I need, But I confused,my code work fine in scrapy 0.24 without any above logging Traceback,so I think it's maybe scrapy bug

### PR DESCRIPTION
**Pull request by Curita**
Closes #1270

Not sure if the timezone is going to be missed from the logs (twisted logging had it) and I'm not entirely sure why windows is expanding it to contain non-ascii chars as reported in the issue, but '%z' time formatting is deprecated as stated here: ~~https://docs.python.org/2/library/time.html#id2~~ [EDIT: I misread it, but is not listed in https://docs.python.org/2/library/time.html#time.strftime so it seems it's not officially supported], so it's probably safer to just remove it. '%Y-%m-%d %H:%M:%S' is the default datefmt for 'asctime' if there isn't one specified as well.

Note that this change just aims to have a sane default, since this is really a python logging issue. Users could still set LOG_DATEFORMAT to whatever they want, but they'll have to deal with the issues the python logging could arise.

### CODE REVIEW

**Comment by kmike** [comment]
@Curita it is `%Z` which is deprecated (we use `%z`), and it is deprecated by email-related [RFC2822](http://tools.ietf.org/html/rfc2822.html) in favor of `%z`. These format specifiers are not deprecated by Python; "deprecated" means that non-numeric time zones (`%Z`) are deprecated for use in emails. 

I second your question from https://github.com/scrapy/scrapy/issues/1270#issuecomment-108592908 - it is not clear why is `%z` formatted as `%Z` for @binbibi.

**Comment by kmike** [comment]
Aha, it seems '%z' is not officially supported in Python 2.x - it is even not in a list of possible options in 2.x docs. It is added to the list in 3.x docs, but I'm not sure it is supported even in 3.x. I think it is fine to remove it.

**Comment by Curita** [comment]
Just updated the issue description too :) I misread '%Z' as '%z', but it does seem is not officially supported.

**Comment by kmike** [comment]
The problem with this change is that without timezone info timestamps in logs become ambiguous. I wonder if it is possible to either force UTC time in logs or somehow bring timezones back.

**Comment by nramirezuy** [comment]
If I understand correctly we can use [`formatter.converter = time.gmtime`](https://docs.python.org/2/library/logging.html#logging.Formatter.formatTime)

**Pull request merged**
