### PR TITLE
[MRG+1] Add test for webclient with POST method and no body given

### PR DESCRIPTION
**Pull request by drack3800**
Discussed in [#823](https://github.com/scrapy/scrapy/issues/823)

### CODE REVIEW

**Comment by kmike** [comment]
:+1: 

Could you please move this check to a separate method and mark it as expectedFailure? Use https://docs.python.org/2/library/unittest.html#unittest.expectedFailure if it works (I'm not sure it'll work here), something pytest-specific if it doesn't work.

**Comment by drack3800** [comment]
@kmike I have added few lines to ```ScrapyHTTPClientFactory``` implementation and now it passes the test. Could you check this?

**Comment by kmike** [comment]
LGTM.

I think we shouldn't set Content-Length header if it is already set, but it is not related to this issue because  when body is not None scrapy also overrides the header.

**Comment by drack3800** [comment]
Thanks for feedback, should I correct something?

**Comment by kmike** [comment]
I think this PR is fine as-is. 

We usually require 2 team members to review the PR before merging (unless the PR is obvious); let's wait for someone else to check & merge it :)

**Comment by drack3800** [comment]
Ok!

**Comment by nyov** [comment]
@drack3800,  I know i'm nitpicking but please don't add whitespace on empty lines? same in your referenced bugfix. Thanks.

**Comment by drack3800** [comment]
@nyov fixed.

**Pull request merged**
