### PR TITLE
[MRG+1] Support 'True' and 'False' strings as boolean settings values

### PR DESCRIPTION
**Pull request by redapple**
'1' and '0' are supported.
I think we can support "True" and "False".

### CODE REVIEW

**Comment by kmike** [comment]
@pablohoffman have you by chance changed your opinion? :)

**Comment by pokkie** [comment]
Would be great if the documentation[1] could be updated to reflect that for boolean values 0 / 1 would be acceptable. 

[1] https://doc.scrapy.org/en/latest/topics/settings.html#command-line-options

**Comment by pablohoffman** [comment]
@kmike let's just say I'm not against this change :) - so feel free to merge

**Comment by redapple** [comment]
(This patch now has conflicts with master branch)

**Comment by kmike** [comment]
Fixed in #2519.

**Pull request closed without merging**
