### PR TITLE
Add Appveyor integration

### LINKED ISSUE #1684: Test Windows builds with Appveyor integration
Just like scrapy has Travis CI integration, scrapy can also be tested on Windows with http://www.appveyor.com/

### PR DESCRIPTION
**Pull request by jdemaeyer**
Resolves #1684

### CODE REVIEW

**Comment by redapple** [comment]
Not so bad :)
`14 failed, 1268 passed, 6 skipped, 25 xfailed, 2 error`

**Comment by jdemaeyer** [comment]
This is 'ready' with a couple of issues:
- lxml is hard to compile/install on Windows. I have resorted to using the inofficial (though well-known) binaries by Christoph Gohlke (http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml)
- Gohlke asks to only manually download from his page, and there is no public mirror. The test script downloads them from a Gist I created for now. I don't like how this relies on a privately owned contributor repo
- pip won't accept the x64 lxml binaries, I don't think this makes much difference for us but it still annoys the shit out of me ^^
- The AppVeyor build sometimes hangs (and are only killed by a 1h timeout) after the tests have run through. I don't know whether this is a pytest or an AppVeyor issue

**Comment by kmike** [comment]
I'm closing it in favor of https://github.com/scrapy/scrapy/pull/3315. Thanks @jdemaeyer, you were years ahead!

**Comment by jdemaeyer** [comment]
> Thanks @jdemaeyer, you were years ahead!

@kmike I may print this comment and hang it on my wall :sweat_smile:

**Pull request closed without merging**
