### PR TITLE
[MRG+1] fixed: Issue #1564 (Incorrectly picked URL in `scrapy.linkextractors.regex.RegexLinkExtractor` when there is a `<base>` tag. )

### PR DESCRIPTION
**Pull request by starrify**

### CODE REVIEW

**Comment by kmike** [comment]
Could you please add a test case?

**Comment by starrify** [comment]
Thanks for the kind notice @kmike :) A test case has now been added.

**Comment by kmike** [comment]
Looks good :+1: 

Should we also remove self.base_url from SgmlLinkExtractor? Comment says
> FIXME: was added to fix a RegexLinkExtractor testcase

**Comment by starrify** [comment]
:+1: Nice observation!

**Pull request merged**
