### PR TITLE
Adding dynamic item creation

### PR DESCRIPTION
**Pull request by WilliamKinaan**
Posting an example about how dynamic items can be created within Scrapy

### CODE REVIEW

**Comment by kmike** [comment]
Hey @WilliamKinaan,

Could you please what's the use case? In Scrapy 1.0 you can yield dicts instead of Item instances.

See also: https://github.com/scrapy/scrapy/pull/1081, https://github.com/scrapy/scrapy/pull/401, https://github.com/scrapy/scrapy/pull/1018, http://scrapy.readthedocs.org/en/0.24/topics/practices.html#dynamic-creation-of-item-classes

**Comment by WilliamKinaan** [comment]
Hi Kmike,

My idea is create the item dynamically without need to specify their names inside the item class.

Yielding an item or a dict is the same for me because the purpose is using dynamic items.

As you see in the items class, there are no items named “name”, “url”, nor “description”. Yet, you can call these items from inside the spider like this:
item['name'] = site.xpath('a/text()').extract()

That is the idea of dynamic items.

Regards,

**Comment by WilliamKinaan** [comment]
Hi Kmike,

My idea is create the item dynamically without need to specify their names
inside the item class.

Yielding an item or a dict is the same for me because the purpose is using
dynamic items.

As you see in the items

On 11 Aug 2015, at 15:42, Mikhail Korobov <notifications@github.com> wrote:

Hey @WilliamKinaan <https://github.com/WilliamKinaan>,

Could you please what's the use case? In Scrapy 1.0 you can yield dicts
instead of Item instances.

See also: #1081 <https://github.com/scrapy/scrapy/pull/1081>, #401
<https://github.com/scrapy/scrapy/pull/401>, #1018
<https://github.com/scrapy/scrapy/pull/1018>,
http://scrapy.readthedocs.org/en/0.24/topics/practices.html#dynamic-creation-of-item-classes

—
Reply to this email directly or view it on GitHub
<https://github.com/scrapy/scrapy/pull/1424#issuecomment-129911326>.

**Comment by kmike** [comment]
In your example [this](https://github.com/WilliamKinaan/ScrapyDynamicItems/blob/046bdc88723f0cb42307bca54d21d05531f385aa/DynamicItemsScrapy/DynamicItemsScrapy/spiders/spider.py#L15) line can be replaced with `item = {}`, and it will work the same, so I don't see a point of using dynamic items in Scrapy 1.0+.

**Comment by WilliamKinaan** [comment]
Oh I got your idea.

Great thanks,

**Comment by kmike** [comment]
Thanks for taking time to make a PR!

**Pull request closed without merging**
