### PR TITLE
Add support for multipart/form-data to FormRequest

### LINKED ISSUE #1897: support for  "multipart/form-data" in scrapy.FormRequest

### PR DESCRIPTION
**Pull request by alexandresgf**
Fixes #1897, closes #1954

### CODE REVIEW

**Comment by wRAR** [comment]
Doesn't look like this changes anything except Content-Type, is this correct?

**Comment by alexandresgf** [comment]
> Doesn't look like this changes anything except Content-Type, is this correct?

Right, as suggested by the OP in the ticket, it should be a flag, in this case `is_multipart`, which changes the `Content-Type` to `multipart/form-data`. I also added a new parameter to `FormRequest` constructor.

**Comment by wRAR** [comment]
The format of multipart/form-data requests is very different from the application/x-www-form-urlencoded one, see e.g. https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4 or the previous PR on this.

**Comment by alexandresgf** [comment]
Closing this PR because I'll move the code to the library [form2request](https://github.com/scrapy/form2request)

**Pull request closed without merging**
