### PR TITLE
Add Test Reporting to Travis CI

### PR DESCRIPTION
**Pull request by munderseth**
**Test Reporting for Travis using [Testspace.com](https://testspace.com)**

Hi `scrapy` team. We added test reporting to your repo. We have a blog article on [why we are staging repos](https://blog.testspace.com/testspace-and-open-source).

Note that we contacted you in the past via an email. We thought it would be easier for you (if interested) by using a Pull Request.   

Few of the benefits using Testspace:
- view all your test results from a single dashboard
- triage and manage your test failures faster
- add more metrics
- leverage built-in analytics 
- get a [test badge](https://help.testspace.com/how-to:get-badge) 
[Space Health](https://open.testspace.com/spaces/74470?utm_campaign=badge&utm_medium=referral&utm_source=test "Test Cases")

Checkout **your** test results: https://open.testspace.com/projects/TryTestspace:scrapy from our fork.

**Why** we are doing this: https://blog.testspace.com/testspace-and-open-source 

----

**Give Testspace a try?**

1. Create **Open** (free) account: https://testspace.com/pricing
2. Add a **New Project** from the list of Github repo's
3. Add a Travis **Environment Variable**: Name: `TS_ORG`  Value: `organization name` - based on subdomain selected in step 1
4. Invite others: https://help.testspace.com/how-to:invite-other-users

### CODE REVIEW

**Comment by munderseth** [comment]
Hi @kmike I was `hoping` if you had a moment to take a look/review this pull request. It basically captures your test results and presents them in an organized format based on your source repo. There is no impact on the workflow. There are a number of benefits and we are working on more analytics to be rolled out in 2018.

We somewhat new to open source, but not the enterprise world. So we decided to fork repos and add the test reporting. This is our approach to getting users.

Mark

**Comment by kmike** [comment]
Hi @munderseth,

I've checked the dashboard you company provides; some parts of it are useful and not covered by our existing CI tools - for example, you can see stdout / stderr output of each test case, even if it is not failing. There are also detailed timings - you can get them using a pytest plugin, but we're not doing that. I also appreciate the way you approached Scrapy, making your goals clear and setting everything up, so that getting benefits is just a single "Merge" button click away.

However, there are also downsides in merging it, so we have to weight our options. I see as downsides the following:

* this is an additional step in our CI which relies on a third-party provider, an additional point of failure - if for some reason testspace is not available, CI will fail;
* this is an additional third-party code we're running on CI, which means an additional security risk. AFAIK we're not using Travis secure env variables (pypi deployment looks different), but if they are used, scripts can access them.

Currently your dashboard looks nice to have, but not essential (e.g. running tests and computing coverage is essential), so I'm -0 on adding it to CI now, because of the downsides. But let's wait and collect other opinions.

**Comment by munderseth** [comment]
Hi @kmike,

First, I really appreciate you `taking time` to provide us feedback and list your concerns.  I have provided my responses to your concerns below. 

> * this is an additional step in our CI which relies on a third-party provider, an additional point of failure - if for some reason testspace is not available, CI will fail;

We do **not** fail in the context of a CI.  We designed our utility this way intentionally.

> * this is an additional third-party code we're running on CI, which means an additional security risk. AFAIK we're not using Travis secure env variables (pypi deployment looks different), but if they are used, scripts can access them.

Public repositories do **not** require a token when pushing content to the Testspace server (only private repos). 

Again thanks for your feedback.

**Comment by kmike** [comment]
> We do not fail in the context of a CI. We designed our utility this way intentionally.

If a script in before_install fails, build would error; fetching data from s3 looks reliable, but it is still an additional point of failure.

> Public repositories do not require a token when pushing content to the Testspace server (only private repos).

@munderseth to clarify, I was talking about private tokens not related to Testspace which testspace utility can access. I'm not saying you would do something bad with them (e.g. send all environment variables to your server), but this is still an addition attack vector we should take in account, and which we can't detect.

**Comment by munderseth** [comment]
Hi @kmike, OK I understand your concerns now. You do have a point. 

I am hopeful you will still give Testspace a try. It would be great to get yours and others feedback. We are also continuing to work on other features that we believe will be useful to your team.  

>Mark

**Comment by munderseth** [comment]
Hi @kmike would you find it useful to also include your code coverage from Codecov.io on the Testspace Dashboard? We think providing test results organized based on your test source organization and showing the coverage *with the tests* is helpful for contributors, especially if they are new. 

If Testspace is *not useful at this time* for you guys just go ahead and close the PR. Note, I do want you to know that I really appreciate you taking time to provide feedback. Thank you.

>Mark

**Comment by munderseth** [comment]
Hi @kmike I wanted to attempt to make a case again for you to give Testspace a try for a `couple of months.`

 * For your contributors it is a lot faster finding test failures versus using the Travis log files, especially for new contributors to scrapy. Take a look at an example I did using an [existing Pull Request](https://github.com/scrapy/scrapy/pull/3051) that has failures:  
    * https://open.testspace.com/projects/38490 - select the branch, then hit `Failures`

 * You can track your overall progress easily (including code coverage). For example, in the last 12 weeks your team increased test cases by [16.5%](https://open.testspace.com/spaces/74470/metrics?timespan=12w).

* We are `working on` a new analytic indicator assessing the **effectiveness of your tests**. It includes regression patterns, source code change rates, and bug tracking (GH Issues). We believe it will be helpful to owners of GitHub organizations. 

So it would be great if you gave a try!

> Mark

----

Simple to get going:
1. Create a free [Open Source Account](https://signup.testspace.com/?plan_id=open.2)
2. Create a `New Project` called **scrapy** - it will be listed 
3. Add a Travis **Environment Variable**: Name: `TS_ORG`  Value: `scrapy` - assuming you would pick this name

**Comment by lopuhin** [comment]
Hello @munderseth , thank you for taking your time to introduce Testspace. It provides some unique features indeed. Still, me and some other scrapy developers are not comfortable accepting Testspace into the scrapy build pipeline in it's current state, due to combination of several reasons: it's not essential for scrapy and adds an extra step (which could fail, might need maintenance, etc.), and this extra step is performed by a binary which is closed (as far as I can tell) and not versioned. I think the first reason is the most important one. The second adds additional concerns. For example, codecov which measures code coverage, is hosted on pypi (so it's at least versioned) and it's code is open and open source.

**Comment by munderseth** [comment]
Hi @lopuhin we are disappointed, but I appreciate you taking the time to respond back with your feedback.

Thank you and good luck to you and the Scapy team.

>Mark

**Pull request closed without merging**
