### PR TITLE
Rename three different Slot classes.

### PR DESCRIPTION
**Pull request by wRAR**
Related to #4296.

### CODE REVIEW

**Comment by wRAR** [comment]
#1392

**Comment by Gallaecio** [comment]
I wonder if we should deprecate the old names instead of just changing them.

**Comment by wRAR** [comment]
@Gallaecio they don't seem to be public, and I think if we cannot just drop them then it's easier to  keep them.

**Comment by Gallaecio** [comment]
I tend to consider public anything that does not start with a `_` XD. However, I guess if they are not documented we _could_ consider them implementation details. I’ll leave it for @kmike to decide.

**Pull request closed without merging**
