### PR TITLE
adding option to use html5lib instead of default htmlparser

### PR DESCRIPTION
**Pull request by markbaas**
#1039 using html5lib invalid chars as <, >, etc are not stripped. Safer, but a bit slower.

### CODE REVIEW

**Comment by Toilal** [comment]
Is it planned to be merged ?

**Comment by dangra** [comment]
I don't think it will make it into Scrapy in the short term, may be once selectors separation into its own project is complete. See #1007

**Comment by redapple** [comment]
@markbaas , could this be merged with or on top of https://github.com/scrapy/parsel/pull/54 (WIP)?
Would it make sense?

**Comment by markbaas** [comment]
Good be, I will check tomorrow ;)

**Comment by markbaas** [comment]
What needs to be done to make this work with parsel?

**Comment by eliasdorneles** [comment]
@markbaas I think it's mostly just making this pull request to Parsel's repo instead of this one.

**Comment by markbaas** [comment]
I will create a new PR when https://github.com/scrapy/parsel/pull/54 is merged.

**Comment by redapple** [comment]
Hey @markbaas !
https://github.com/scrapy/parsel/pull/54 is finally merged :)
are you still up for adding "html5" type in parsel?

**Comment by TilakMaddy** [comment]
Cool

**Comment by kmike** [comment]
Closing it, because such fixes now belong to parsel.

**Pull request closed without merging**
