### PR TITLE
Prepare 1.4.1 release

### PR DESCRIPTION
**Pull request by dangra**

### CODE REVIEW

**Comment by dangra** [comment]
[Outdated] release notes by Paul https://github.com/scrapy/scrapy/commit/5fc66e5ff2cbf2e944be3870b7fbd0f3b2f75568

**Comment by dangra** [comment]
Commits since 1.4.0 release https://github.com/scrapy/scrapy/commit/5fc66e5ff2cbf2e944be3870b7fbd0f3b2f75568

**Comment by dangra** [comment]
travis-ci build is not looking good 
image

**Comment by lopuhin** [comment]
and there is a diff between 1.4.0 release and 1.4 branch which cases at least pypy failures (it was allowed to fail in 1.4.0, and the fixes for that were released only in 1.5.0)

**Comment by kmike** [comment]
We're not going to make this release, unless someone really push for it, so I'm closing the PR.

**Pull request closed without merging**
