### PR TITLE
Remove manual pypy installation from .travis.yml.

### PR DESCRIPTION
**Pull request by wRAR**

### CODE REVIEW

**Comment by wRAR** [comment]
The tests failed with the Travis pypy3, I think I've seen this failure with some old OpenSSL version, I have no idea why it happens in this environment though.

**Comment by wRAR** [comment]
On the other hand, with a locally installed Debian pypy3 7.1.1 I get `OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert internal error')]` in the same test and in `Https11CustomCiphers.test_download`.

**Comment by wRAR** [comment]
And it works with pyenv `pypy3.6-7.1.1` :)

**Comment by Gallaecio** [comment]
The same version (same hash and everything) fails if coming straight from Travis CI but works if installed manually. I think we should just stick to the manual installation for now, and try the Travis CI version again once they upgrade away from 2.6-7.1.1-beta.

**Comment by Gallaecio** [comment]
What the…

**Comment by Gallaecio** [comment]
I am completely puzzled.

I’ve created a new pull request with the same commits. Same commits. As in same commit hash. [My pull request](https://github.com/scrapy/scrapy/pull/4130) ([merge commit](https://github.com/scrapy/scrapy/commit/26d264c68cd5797cbeb4981b752461ed715250c4)) [builds just fine](https://travis-ci.org/scrapy/scrapy/jobs/607839913). This one ([merge commit](https://github.com/scrapy/scrapy/commit/7e4ad928ac67ef1c5f5c2adc51bd6de5df1e3614)) [does not](https://travis-ci.org/scrapy/scrapy/jobs/607804390).

**Comment by wRAR** [comment]
I couldn't make it fail in a xenial chroot or in the travis docker image (I tried `travisci/ci-sardonyx:packer-1558623664-f909ac5`). I've also tried the docker image and pypy3 provided by Travis, and there I couldn't run it at all as the cryptography binaries (`cryptography-2.8-pp371-pypy3_71-linux_x86_64.whl`) are built for a newer libssl than the xenial one :-/

**Pull request closed without merging**
