### PR TITLE
[MRG] Fix startproject project name

### PR DESCRIPTION
**Pull request by nramirezuy**
#434 fixes.

> Add project name validation

### CODE REVIEW

**Comment by timschwab** [comment]
Correct me if I am wrong, but this code is meant to prevent users from creating projects with module names. Well I recently started using Scrapy and no errors are thrown on creation when I type `scrapy startproject test`. The errors start appearing later, the same way as the original issue, #428.

**Comment by dangra** [comment]
@timschwab what scrapy version are you using?

**Comment by timschwab** [comment]
Scrapy 0.24.6

**Comment by dangra** [comment]
@timschwab: that change is not part of 0.24 branch. You can install 1.0.0rc3 from pypi, it is going to be released this/next week as final: `pip install Scrapy==1.0.0rc3`

**Comment by timschwab** [comment]
@dangra: gotcha. Thanks.

**Pull request merged**
