### PR TITLE
[MRG+1] Add verification to check if Request callback is callable

### PR DESCRIPTION
**Pull request by stummjr**
This PR intends to fix https://github.com/scrapy/scrapy/issues/2766.

When users pass a string to `Request.__init__`'s `callback` parameter, they end up getting a Twisted exception, which doesn't help to uncover this, which is a rather simple issue.

This PR changes that, so that users get a proper message when passing something that's not callable to the `callback` and `errback` parameters.

### CODE REVIEW

**Comment by stummjr** [comment]
It seems that it broke other tests. I'll have a look on it. (I ran only the `test_http_request` tests locally)

**Comment by stummjr** [comment]
@redapple I just updated the PR. I had to update the `parse` command implementation and also the request serialization tests.

**Comment by redapple** [comment]
Looks good to me @stummjr

**Comment by redapple** [comment]
@kmike @eliasdorneles @dangra @lopuhin , what do you think?

**Comment by lopuhin** [comment]
The changes look good to me, 👍 
My only comment is maybe instead of saying ``callback must be a function, got ...``, we could say ``callback must be callable, got ...``, but I'm not sure here - the latter is more precise, but "function" is probably more familiar.

**Comment by dangra** [comment]
I second Konstantin but would like to vote for _callable_ as it is technically more correct.

**Comment by stummjr** [comment]
@redapple , @dangra, @lopuhin: I just fixed the error message. Thanks for your comments. 😃

**Pull request merged**
