### PR TITLE
added: Doc for `scrapy.http.TextResponse.urljoin`

### PR DESCRIPTION
**Pull request by starrify**

### CODE REVIEW

**Comment by kmike** [comment]
@Digenis a good suggestion, +1

**Comment by kmike** [comment]
The PR looks good; I think it misses a rebase, and probably it makes sense to apply @Digenis's suggestion.

**Comment by starrify** [comment]
Thank you @kmike and @Digenis :)
Please have a look at this updated PR.

**Comment by Digenis** [comment]
Looks good to me.

(though I don't remember my comment on the deleted diff)

**Review by wRAR — APPROVED** [review]

**Comment by kmike** [comment]
Thanks @starrify, and @Digenis for susggestion (though I don't recall what it was as well :)!

**Pull request merged**
