### PR TITLE
Fix some redirection links in documentation

### LINKED ISSUE #606: Redirection Links in docs
When i run

```
cd doc;
make linkcheck
```

It shows a list of url some which are redirection ones and some broken ones.

### PR DESCRIPTION
**Pull request by dufferzafar**
This fixes #606.

I wrote [this python script](https://github.com/dufferzafar/Python-Scripts/blob/master/Sphinx%20Linkfix/linkfix.py) to fix the docs. It uses the linkcheck output to work.

Most of the links have been fixed but in the docs/news.rst file all github issues are referred using `issue_role`, even pull requests.

Like [this line](https://github.com/scrapy/scrapy/commit/ee33efac3962edf4393fc90fb0bf1ec6a5593443#diff-598c16c78e0faacf69ff9ecf4ab00aa9R47) refers to issue 693. But 693 is actually a [pull request]( https://github.com/scrapy/scrapy/pull/693)!

Should I create a new role for pulls (in docs/_ext/scrapydocs.py) to fix them as well?

### CODE REVIEW

**Comment by kmike** [comment]
Looks good, +1 to merge. 
I'm fine with explicit /2/ links to python docs and /en/latest links to RTFD.

**Comment by eliasdorneles** [comment]
I don't understand why this build fails, it doesn't even touch the code.
Anyway, LGTM.

**Comment by kmike** [comment]
@eliasdorneles it failed because of https://github.com/scrapy/scrapy/issues/1034

**Comment by Curita** [comment]
LGTM too, but I'd also add the script because we'll surely need it again. @dufferzafar can you add the ``linkfix.py`` script to the repo? I think we could create a folder under ``docs`` (let's say ``docs/utils``) and put it there.

**Comment by dufferzafar** [comment]
@Curita Will do it today.

**Comment by pablohoffman** [comment]
what about adding a sub-command to documentation Makefile (`docs/Makefile`)?. There's already a `linkchecker`  (using standard sphinx plugin: http://sphinx-doc.org/latest/_modules/sphinx/builders/linkcheck.html)

**Comment by Curita** [comment]
@pablohoffman: @dufferzafar's script uses `linkcheck` output to fix those links. Maybe we could add a command in the [Makefile](https://github.com/scrapy/scrapy/blob/master/docs/Makefile) that runs `linkcheck` and then runs this script?

Could be something like:
```
linkfix: linkcheck
    $(PYTHON) utils/linkfix.py
    @echo "Fixing redirecting links in docs has finished, check all replacements before committing them"
```

**Comment by pablohoffman** [comment]
@Curita that sounds good, can you add and merge?

**Comment by Curita** [comment]
Merged in e17f97e637a9ed454161cf4f2eaf57bf58b0fe3c

**Pull request closed without merging**
