### PR TITLE
[MRG +1] bpython support

### PR DESCRIPTION
**Pull request by cyberplant**
Related to #1100, this shows the banner correctly on standard python, ipython and bpython.

### CODE REVIEW

**Comment by nyov** [comment]
It seems there is a slight difference in output behaviour now.

master:
```
2015-08-21 02:16:36 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x7ffb74db8c10>
[s]   item       {}
[s]   settings   <scrapy.settings.Settings object at 0x7ffb6f3b4ad0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser
2015-08-21 02:16:37 [root] DEBUG: Using default logger
2015-08-21 02:16:37 [root] DEBUG: Using default logger

In [1]:
```

this:
```
2015-08-21 02:16:44 [root] DEBUG: Using default logger
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f3452b18b90>
[s]   item       {}
[s]   settings   <scrapy.settings.Settings object at 0x7f3452b18b10>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser
In [1]:
```

It's eating the `[root] DEBUG: Using default logger` lines? (though I have no idea where those come from)

**Comment by cyberplant** [comment]
Hehe, I was doing some tests here, but wasn't able to reproduce your problem. :+1:

**Comment by nyov** [comment]
(actually the lines moved from after the banner output to above it, I just missed them)

**Comment by nramirezuy** [comment]
<:o)

**Comment by cyberplant** [comment]
Yeah! :fireworks: :+1:  :beers:

**Pull request merged**
