### PR TITLE
allow setting s3 host for Files Piepline

### LINKED ISSUE #1361: Feature Request: Allow setting `host` for S3 FilePipeline
Per https://github.com/boto/boto/issues/621, a `AWS_S3_HOST` in settings would be helpful.

### PR DESCRIPTION
**Pull request by zachguo**
Fixes #1361, tested working locally. 
But no test codes are included here, because I didn't find any existing tests for S3Connection in the repo.

### CODE REVIEW

**Comment by zachguo** [comment]
Build failure should not be caused by my codes, and I don't know what to do about coverage.

**Comment by zachguo** [comment]
The build failed because I used `NoHostProvided` which is not in `boto 2.2.2`. Shall I accommodate my codes to old `boto` or upgrade `boto` to `2.38.0`?
For coverage, I don't know what to do either. I didn't find any existing tests for `S3Connection`.

**Comment by kmike** [comment]
I think it is better to keep boto 2.2.2 support; we support it because that's the boto version which comes with Ubuntu 12.04.

**Comment by zachguo** [comment]
Unfortunately i don't have much time for this now. I prefer to upgrading boto, it's much easier (maybe [one-line change in tox.ini](https://github.com/scrapy/scrapy/blob/master/tox.ini#L26)).

**Comment by kmike** [comment]
Yeah, it is easy to upgrade boto in tox.ini, but the point of this line is to run tests with boto 2.2.2 because we support this boto version. Other tox environments use a more recent boto.

**Comment by zachguo** [comment]
Let's temporarily close it. I'll revisit when I have time.
TBH, I still don't understand why scrapy should carry the boto 2.2.2 burden.

**Pull request closed without merging**
