### PR TITLE
Updated setup-python and checkout actions workflow

### PR DESCRIPTION
**Pull request by Nirzak**
Updated setup-python workflow to version 4 and action checkout workflow to version 3.

### CODE REVIEW

**Review by wRAR — APPROVED** [review]

**Comment by Nirzak** [comment]
Looks liek getting issue from this command pytest --cov=scrapy --cov-report=xml --cov-report= {posargs:--durations=10 docs scrapy tests} from tox.ini in case of Python 3.10

**Comment by wRAR** [comment]
The actual error is 

E           twisted.trial.unittest.FailTest: 
E           Expected: (<class 'twisted.internet.error.TimeoutError'>,)
E           Got:
E           [Failure instance: Traceback (failure with no frames): <class 'twisted.web._newclient.ResponseNeverReceived'>: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '', 'wrong version number')]>]
E           ]

Not sure if this is something new or just a temporary problem.

**Comment by Nirzak** [comment]
hmm also this particular python file is causing HTTP timeout error tests/test_downloader_handlers_http2.py but the same file fetched properly in case of python 3.11 and other version.
May be the error is temporary.

**Comment by Nirzak** [comment]
Is it possible to manually re run the workflow?

**Comment by wRAR** [comment]
I've restarted the failed job.

**Comment by wRAR** [comment]
So it looks like an intermittent problem/

**Comment by Nirzak** [comment]
> So it looks like an intermittent problem/

Yes. Looks like a temporary network blip during that particular job.

**Comment by kmike** [comment]
Thanks @Nirzak!

**Pull request merged**
