### PR TITLE
item fields defined on fields class attribute fix

### PR DESCRIPTION
**Pull request by nramirezuy**
reported on: #1217

### CODE REVIEW

**Comment by dangra** [comment]
Do we really want to support defining fields like this in ItemMeta? 

The user says it works for DictItem which is fine because it is the case it must work, but for Item (and ItemMeta) it was working as a side effect, even untested.

In any case if we want to support defining fields mixed in `fields` attribute plus Field's attributes, let's add a simple test case without inheritance involved.

**Comment by nramirezuy** [comment]
It was working before and was fair easy to fix it. 
I defined an item that way, the only functionality I can think of is consistency with another side effect :tongue: 

```python
>>> class A(Item):
...     fields = {'save': Field(default='A')}
...     load = Field()
... 
>>> a = A()
>>> a.fields
{'load': {}, 'save': {'default': 'A'}}
>>> A.new = Field()
>>> a.fields
{'load': {}, 'save': {'default': 'A'}}
>>> A.fields['new_field'] = Field()
>>> a.fields
{'load': {}, 'new_field': {}, 'save': {'default': 'A'}}
>>> a['new_field'] = 1
>>> a
{'new_field': 1}
```

**Comment by dangra** [comment]
Ok, what do you think about adding a very simple test case without inheritance ?

**Comment by nramirezuy** [comment]
@dangra That works?

**Comment by dangra** [comment]
IMO is much easier to debug a broken test when it test a single case, even better if new cases doesn't modify previous well defined tests.

I would add a `test_metaclass_with_fields_attribute()` instead of modified `test_metaclass()`.

**Comment by nramirezuy** [comment]
done

**Comment by dangra** [comment]
Do we need documentation updates?

anyone want to comment before merging? /cc @Curita @kmike

**Pull request merged**
