### PR TITLE
Responsetypes

### PR DESCRIPTION
**Pull request by GregoryVigoTorres**
Port responsetypes to Py3

### CODE REVIEW

**Comment by kmike** [comment]
Hm, I thought from_headers method is wrong: Headers object uses bytes for keys and values. See https://github.com/scrapy/scrapy/pull/1393#discussion_r35811801. But it seems this is fine because Headers is a CaselessDict, and it calls self.normkey before each lookup, so using native strings is fine for keys.

**Comment by kmike** [comment]
I think test_responsetypes should be changed / improved: it is not doing the same in Python 2.x and 3.x, esp. in test_from_body method. In Python 3.x this method is not checking responsetypes for bytes body object, and Scrapy usually uses bytes for body.

**Comment by GregoryVigoTorres** [comment]
Would this be a reasonable addition to tests_responsetypes.test_from_body_method?
    (b'Some plain text\ndata with tabs\t and null bytes\0', Response)
Or should it test for TextResponse?

Are there written guidelines for Py3 porting anywhere? Or are too many details still undecided?

**Comment by kmike** [comment]
> Would this be a reasonable addition to tests_responsetypes.test_from_body_method?
(b'Some plain text\ndata with tabs\t and null bytes\0', Response)
Or should it test for TextResponse?

I think it should test for TextResponse. It could be enough to just make all body constants bytes in tests; I believe this was an intention of these tests.

> Are there written guidelines for Py3 porting anywhere? Or are too many details still undecided?

Yes, unfortunately there are no guidelines now. I think we should follow these rules:

1. Use a single codebase for Python 2.x and 3.x using six library;
2. URLs should be "native strings" - bytes in Python 2.x and unicode in Python 3.x.
3. Headers should use bytes for both keys and values.
4. Be careful with auto-decoding and auto-encoding of data.
5. We can't rely only on tests to make the port. Even if some test is passing we shouldn't consider a related module ported, and we shoudn't uncomment it from py3-ignores.txt without carefully reading the source code of a tested module and a source code of the test itself.
6. Common sense is useful.

Also, the decisions are not final; we made them to unblock the further porting. We may have to change some of them (e.g. make headers native strings) - after a reasonable subset of Scrapy is ported we should try using it in Python 3 and decide what to do based on experience.

**Comment by GregoryVigoTorres** [comment]
I've seen a few other tests where body constants is not bytes...
>We can't rely only on tests to make the port.
commits probably shouldn't be called py3 port just because the tests pass in py3

**Comment by kmike** [comment]
> I've seen a few other tests where body constants is not bytes...

Bytes is what is coming from the network; Response objects only support bytes (they raise an exception if user tries to create Response with unicode data). 

TextResponse and its subclasses support unicode as body. Internally the body will still be converted to bytes, but you can create TextResponse from unicode body if you pass an encoding. I believe Scrapy itself is not passing unicode bodies to TextResponse; it seems we're supporting this feature just for the convenience.

Do you have some examples? They could be errors in Scrapy code.

**Comment by GregoryVigoTorres** [comment]
It was in test_default_media_downloaded, but now body is b'' not '' .

**Comment by GregoryVigoTorres** [comment]
Another question:
Which python versions should I be testing with?
I'm currently testing with 2.7 and 3.4

**Comment by kmike** [comment]
> Which python versions should I be testing with?
I'm currently testing with 2.7 and 3.4

A good question. We're going to support Python 2.7 and Python 3.3+. You can continue testing with Python 3.4 because there is no much difference between Python 3.3 and 3.4 when it comes to porting.

**Comment by kmike** [comment]
Thanks @GregoryVigoTorres! I've merged your changes to master.

**Pull request closed without merging**
