### PR TITLE
hacktoberfest-2022

### PR DESCRIPTION
**Pull request by Tejas1020**
This is the data needed for the scrapy to work efficiently

### CODE REVIEW

**Comment by armujahid** [comment]
This is a spam PR. We should add spam label and close it. Reference: https://hacktoberfest.com/participation/#spam

**Review by armujahid — COMMENTED** [review]
This is a spam PR. We should add spam label and close it. Reference: https://hacktoberfest.com/participation/#spam

**Review by Clash-ion — COMMENTED** [review]
atleast add something

**Comment by roniemartinez** [comment]
@kmike You should add "spam" label. https://hacktoberfest.com/participation/#spam

**Comment by kmike** [comment]
Added, thanks for the pointer @roniemartinez!

**Pull request closed without merging**
