### PR TITLE
Update release notes with recent features and bug fixes.

### LINKED ISSUE #1927: Update changelog with changes since 1.1.0RC3
(major) Merged changes since v1.1.0rc3:

* #1875 -- FS cache storage misuses mtime for expiration (bugfix)
* #1822 -- Allow core Scheduler priority queue customization
* #1835 -- Add pps extension to IGNORED_EXTENSIONS (fixing #1834)
* #1857 -- response_status_message should not fail on non-standard HTTP codes (bugfix)
* #1851 -- Rename isbinarytext function to binary_is_text for clarity
* #1883 -- Make FilesPipeline work with S3FilesStore using botocore (bugfix)
* #1879 -- Improved Architecture overview (docs)
* #1847 -- Added FEED_TEMPDIR to settings (fixing #1779)
* #1902 -- Making it case-insensitive when extracting sitemap URLs from a robots.txt
* #1913 -- Fix link extractor tests for non-ASCII characters from latin1 document (tests)
* #1881 -- Remove duplicate code now handled by newer w3lib (refactoring)
* #1891 -- Change Files/ImagesPipelines class attributes to instance attributes (fixing #1850)
* #1938 -- Set SNI properly when using CONNECT (fixing #1936)
* #1912 -- Fix HTTP Pool key for HTTPS proxy tunneled connections (CONNECT method) (fixing #1807)
* #1933 -- Ignore HTTPS certificate verification failures (fixing #1930)
* #1923 -- Use newer w3lib.url.safe_url_string() and re-enable HTTP request tests
* #1947 -- Fix canonicalize_url() on Python 3 and re-enable tests

### PR DESCRIPTION
**Pull request by redapple**
Fixes #1927

### CODE REVIEW

**Comment by kmike** [comment]
It looks like the following changes are not in release notes:

* https://github.com/scrapy/scrapy/pull/1950
* https://github.com/scrapy/scrapy/pull/1883 - this one can be seen just as Python 3 port progress, but I think we should mention botocore is now supported

**Comment by redapple** [comment]
@kmike thx. Updated.

**Comment by kmike** [comment]
Could you please port it to master as well?

**Comment by redapple** [comment]
Done.

**Pull request merged**
