### PR TITLE
[MRG+1] py3: reviewed passing test_spidermiddleware_httperror.py

### PR DESCRIPTION
**Pull request by lopuhin**

### CODE REVIEW

**Comment by kmike** [comment]
yeah, it looks good

**Comment by eliasdorneles** [comment]
Oops! Failed in 3.5 for some weird reason: https://travis-ci.org/scrapy/scrapy/builds/104493145
Any ideas?

**Comment by kmike** [comment]
That's https://github.com/scrapy/scrapy/issues/1707 striking back :)

**Comment by eliasdorneles** [comment]
:+1: I restarted and it passed

**Pull request merged**
