### PR TITLE
Added installation notes about using Conda for Windows.

### PR DESCRIPTION
**Pull request by rolando**
This PR adds installation notes about installing Scrapy via conda and the Scrapinghub's anaconda.org channel.

### CODE REVIEW

**Comment by kmike** [comment]
Looks good, given that conda package works. 
Is it OK not to use service_identity? Will it cause failed HTTPS connections for Windows users (see https://github.com/scrapy/scrapy/issues/1418)?

**Comment by rolando** [comment]
That's a valid concern. I have created this issue to address it: https://github.com/scrapinghub/scrapinghub-conda-recipes/issues/2

**Comment by rolando** [comment]
@kmike this PR restores `service_identity` as a dependency https://github.com/scrapinghub/scrapinghub-conda-recipes/pull/4

**Comment by kmike** [comment]
@rolando is this PR ready to merge?

**Comment by rolando** [comment]
@kmike yes, it's good to merge.

**Pull request merged**
