### PR TITLE
Add Debian Jessie test env

### PR DESCRIPTION
**Pull request by redapple**
Testing if this could make a good baseline

### CODE REVIEW

**Comment by kmike** [comment]
Have we decided what to do with Ubuntu 14.04? Is it supported?

**Comment by redapple** [comment]
I believe we said that Twisted 13.2 in Ubuntu Trusty 14.04 is a bit too old.
@dangra , can you confirm?

**Comment by redapple** [comment]
@dangra , are you ok with using Debian Jessie as baseline?

**Comment by redapple** [comment]
@dangra , ping ;-)

**Comment by dangra** [comment]
@redapple sorry for delay.

**Comment by dangra** [comment]
We must mention in next release what is the new baseline.

**Comment by redapple** [comment]
@dangra , where do you see this mention? release notes? installation guide?

**Comment by dangra** [comment]
Release notes for sure. It has to be clear in installation guide what
distribution versions it is supported out of the box and what "may work".

**Pull request merged**
