### PR TITLE
[MRG+1] Updated architecture graph for organization/clarity

### PR DESCRIPTION
**Pull request by loreguerra**
Found the first graph hard to read when first learning about Scrapy architecture.

Open to edits!!

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
IMHO 100% better 👏

**Comment by eliasdorneles** [comment]
Wow, that's really neat, thank you! :+1: 

However, the numbers aren't quite matching the text now.
What is easier, to update the text or the graphic? :)

**Comment by loreguerra** [comment]
I figured I'd see what you all thought of that. The text smashes a few processes together. 

Let me group the steps by text number (to avoid changing text) and organize steps by color. 

I'll get back to you.

**Comment by eliasdorneles** [comment]
Yeah, the text is mixing up some process, feel free to break it down!

Thank you so much for working in this, this is awesome!

I never grasped that old graphic, but this one I can actually follow! :laughing:

**Comment by loreguerra** [comment]
Great! I wasn't sure if it was just me! I'll work on it.

**Comment by loreguerra** [comment]
Edits made. Text should align with graphic now.

**Comment by eliasdorneles** [comment]
Looks great, thank you very much @loreguerra !

**Comment by eliasdorneles** [comment]
@loreguerra btw, could you include the vector file too?
Just in case we need to update it someday. =)

**Comment by loreguerra** [comment]
Sure thing. Attached.


[scrapy.ai.zip](https://github.com/scrapy/scrapy/files/402447/scrapy.ai.zip)

**Comment by kmike** [comment]
Awesome, thanks @loreguerra!

**Pull request merged**
