### PR TITLE
Coverage and reports at codecov.io and coveralls.io

### PR DESCRIPTION
**Pull request by dangra**

### CODE REVIEW

**Comment by kmike** [comment]
Nice!

* Does it measure coverage when scrapy command is executed using Popen? It seems the answer is yes, but I don't understand why :)
* what about adding a badge to README? https://img.shields.io/codecov/c/github/scrapy/scrapy/master.svg
* did you add coveralls to try both and choose what we like more?
* it could be good to exclude moved modules if we don't have plans to add tests for them: scrapy/contrib, etc.

**Comment by dangra** [comment]
oops, wrongly closed PR.

**Comment by dangra** [comment]
> Does it measure coverage when scrapy command is executed using Popen? It seems the answer is yes, but I don't understand why :)

Seems to be a feature of pytest-cov:

* https://pypi.python.org/pypi/pytest-cov
* http://blog.fizyk.net.pl/blog/gathering-tests-coverage-for-subprocesses-in-python.html


> what about adding a badge to README? https://img.shields.io/codecov/c/github/scrapy/scrapy/master.svg

Added.

> did you add coveralls to try both and choose what we like more?

Yes, I did. Let's try both for some time and decide later with more experience.

> it could be good to exclude moved modules if we don't have plans to add tests for them: scrapy/contrib, etc.

I prefer testing deprecation of moved modules.

**Comment by dangra** [comment]
I reverted testing of moved modules because importing test_moves.py breaks tests/test_pipeline_media.py in py27 and py34. Even importing `scrapy/statscol.py` breaks other tests.

Now moved modules are ignored.

**Comment by kmike** [comment]
I like it, +1 to merge.

One question: is it possible to turn coverage off when running individual tests using tox - the report can be too verbose? What about moving --cov option to posargs?

**Comment by kmike** [comment]
I also wonder why does it show [scrapy.cmdline._run_command_profile](https://codecov.io/github/scrapy/scrapy/scrapy/cmdline.py?ref=384a2a7f3abc55392914eeca8650fee626f4e68e#l-152) uncovered - I added a test for it [here](https://github.com/scrapy/scrapy/commit/56be610e6e26ec7a17ec16dccc09fa832facb0fa).

**Pull request merged**
