### PR TITLE
Module relocation follow up

### PR DESCRIPTION
**Pull request by Curita**
Remaining module relocations introduced and briefly discussed in #1181 

_Move modules used as common code from packages to their respective packages:_
* `scrapy/command.py` -> `scrapy/commands/base.py` (imported in `scrapy/commands/__init__.py`)
* `scrapy/linkextractor.py` -> `scrapy/linkextractors/base.py` (imported in `scrapy/linkextractors/__init__.py`)

_Rename MiddlewareManager module:_
* `scrapy/middleware.py` -> `scrapy/middlewaremanager.py`

_Move modules with MiddlewareManagers inside their respective middleware packages (using ItemPipelineManager in scrapy/pipelines/ as convention):_
* `scrapy/extension.py` ExtensionManager-> `scrapy/extensions/__init__.py`
* `scrapy/core/downloader/middleware.py` DownloaderMiddlewareManager -> `scrapy/downloadermiddlewares/__init__.py`
* `scrapy/core/spidermw.py` SpiderMiddlewareManager-> `scrapy/spidermiddlewares/__init__.py`

It's still open the decision to establish what we want in `scrapy/core/`, particularly if the two MiddlewareManagers there can be moved out of that package.

### CODE REVIEW

**Comment by kmike** [comment]
Maybe it is just me, but I always have troubles locating code if it is put into `__init__.py` files. These files are most often empty, or contain only imports from sub-packages, so it is the last place to look at if you're trying to find something in the codebase. My preference is to add something like commands/base.py or commands/common.py, and import from there in `commands/__init__.py`.

**Comment by Curita** [comment]
I thought the same, and for `scrapy/linkextractors/__init__.py` and `scrapy/commands/__init__.py` I think it makes sense to rename them to `base.py` for example, a sort of base FilteringLinkExtractor and the base ScrapyCommand are there.

Not sure how to handle the MiddlewareManagers though. Putting them in a regular module inside their packages could look like they are just another one of those middlewares (For example, moving the ExtensionManager to `scrapy/extensions/manager.py` may seem like there's a new extension named "Manager"). So I copied the location for ItemPipelineManager inside `scrapy/pipelines/__init__.py` being sort of "hidden" on purpose, though I grant that it's probably not the best approach.

**Comment by Curita** [comment]
Just changed `scrapy/linkextractor.py` for `scrapy/linkextractors/base.py` and `scrapy/command.py` for `scrapy/commands/base.py`.

**Comment by Curita** [comment]
Decisions made last meeting:
* We're going to put on hold the MiddlewareManager relocations until we know what to do with `scrapy/core`, and we find some consistent place to put them close to the middleware they are related to. This isn't a blocker for 1.0 now.
* This PR is going to be split in two, one moving all base classes inside their packages (including `scrapy/spider.py`) in their `__init__.py` file as it is the convention now, and another one moving the base classes out of `__init__.py` and into a module named `base.py` inside the package. It's going to be done in two steps so we can discuss both things separately.

**Comment by Curita** [comment]
I'm closing this PR in favor of #1218.

**Pull request closed without merging**
