### PR TITLE
[WIP] Use docstrings where possible

### LINKED ISSUE #713: Bring docstrings back
What do you think about moving docstrings back to classes, functions and modules?

It'll make reading and understanding Scrapy code as well as working in Scrapy shell easier. Also, it will allow adding "viewcode" Sphinx extension to docs. Of course, there should be hand-written doc pages that explain main concepts, but the API reference can be mostly auto-generated.

### PR DESCRIPTION
**Pull request by Gallaecio**
Fixes #713 (and #2727). This is the first part of #3532.

I’ve gone through all matches of the following regular expression:

    \.\.\s+(?:function|data|exception|class|attribute|(?:static|class)?method|decorator(?:method)?)::

It should match all scenarios where `autodoc` can be used but it is not currently used.

I kept `module` outside of the regular expression on purpose, because none of the current usages of `.. module::` is designed in a way that it makes sense to extract the documentation from a docstring. There seem to be there just so that following a module link from the index leads somewhere.

After these changes, only the following 16 matches for the regular expression above remain while searching with a simple `*.rst` filename filter. Of those:

-   There is a match, `Item.fields`, where a [Sphinx bug](https://github.com/sphinx-doc/sphinx/issues/741) prevents removing the documentation from the reStructuredText file.

-   All other matches are due to fictional API members, members that are not really part of the Scrapy API but that users may implement in subclasses.

Regarding the latter, I believe the best approach to move that documentation to docstrings would be to implement the corresponding (zope) interfaces (à la [`scrapy.interfaces.ISpiderLoader`](https://github.com/scrapy/scrapy/blob/master/scrapy/interfaces.py)) for the following affected fictional members: [`scrapy.downloadermiddlewares.DownloaderMiddleware`](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.DownloaderMiddleware), [pipeline](https://doc.scrapy.org/en/latest/topics/item-pipeline.html#writing-your-own-item-pipeline), [`scrapy.spidermiddlewares.SpiderMiddleware`](https://doc.scrapy.org/en/latest/topics/spider-middleware.html#scrapy.spidermiddlewares.SpiderMiddleware). I see no solution at the moment for the remaining fictional members, two methods of [`scrapy.contracts.Contract`](https://doc.scrapy.org/en/latest/topics/contracts.html#scrapy.contracts.Contract).

If you agree with the interface definition approach for those remaining API members, please let me know whether I should create a separate pull requests or include those changes in this pull requests (squashed or as a separate commit).

### CODE REVIEW

**Comment by Gallaecio** [comment]
Some of the failed checks are due to doctests that used to be in `.rst` files on the `docs` folder, hence ignored, but are now in `.py` files on the `scrapy` folder, hence processed.

Of those, I don’t know how I should fix the ones that fail due to the output being different on Python 2 and Python 3. For example:

    https://travis-ci.org/scrapy/scrapy/jobs/487505259#L2191

How should I proceed to fix those scenarios? Should the output be for Python 2 or for Python 3? Is it OK to skip those doctests in the other versions of Python?

**Comment by Gallaecio** [comment]
I went with using Python 3 in the documentation and skipping those tests in environments with Python 2.

**Comment by Gallaecio** [comment]
Tests passed (by skipping doctests in Python < 3). I’m ignoring the coverage report, as the changes only affect documentation files, comments and configuration files.

**Comment by kmike** [comment]
Hey @Gallaecio! I know it is a huge amount of work you've done here; my worry is that it'd be hard to merge such big pull request - there is a lot of changes to review, and master is changing as well, adding merge conflicts. 

* Getting stuck in discussing even a single change may delay the merge of the whole PR, and increase work on resolving merge conflicts. 
* It is also hard to get back to a large pull request and figure out for which parts the review is finished, and for which there is still discussion ongoing.
* Reviewing big pull request requires a large time investement once; it is easier to find time here and there to review smaller pull requests.

Do you think it'd be possible to split it into several pull requests, e.g. a PR with some groundwork (adding extensions, CI changes), and then separate pull requests for different parts of Scrapy? This way it should be much easier to eventually merge all changes, one by one.

**Comment by Gallaecio** [comment]
Yes, I think that will be the only sane approach. I’ll get to it next week.

**Pull request closed without merging**
