### PR TITLE
Add OS X build in Travis CI

### PR DESCRIPTION
**Pull request by redapple**

### CODE REVIEW

**Comment by redapple** [comment]
Hm, I don't really know what I'm doing.
I can't get rid of this in travis
```
$ source ~/virtualenv/python2.7/bin/activate
/Users/travis/build.sh: line 45: /Users/travis/virtualenv/python2.7/bin/activate: No such file or directory
```

**Comment by kmike** [comment]
Travis used to allow OS X builds only on paid accounts - does it change?

**Comment by redapple** [comment]
@kmike , I can't see mention of paid account restriction on https://docs.travis-ci.com/user/osx-ci-environment/
I wanted to try after seeing https://www.youtube.com/watch?v=d-p6lJJObLU (https://speakerdeck.com/pycon2015/olivier-grisel-build-and-test-wheel-packages-on-linux-osx-and-windows) which suggest it's possible

**Comment by GandaG** [comment]
From what I've experienced, the only way to make it build on an osx machine with a free account is to place the language as "objective-c". The os option appears to be only for pro acounts.

Travis Weblint says: `your repository must be feature flagged for the os setting to be used`

**Comment by redapple** [comment]
@GandaG , thanks for th hint.

Closing this PR for now then.

**Pull request closed without merging**
