### PR TITLE
Use https for external links wherever possible in docs

### PR DESCRIPTION
**Pull request by codeaditya**
I have manually followed all the http links in docs and converted them to https wherever possible. 

I didn't touch links for docs.scrapy.org, scrapy.org and sub-domains of it. Shall we convert them to https too?

### CODE REVIEW

**Comment by kmike** [comment]
Awesome, thanks @codeaditya!

**Comment by codeaditya** [comment]
Thanks for mergin @kmike .. Would it be fine to use https links for docs.scrapy.org, scrapy.org and other subdomains of scrapy.org? I would be happy to fix them and send another request for it :-)

**Comment by kmike** [comment]
It sounds like a good change to me, but let's confirm it with @dangra.

**Comment by dangra** [comment]
Yes, it is!

**Comment by codeaditya** [comment]
Submitted PR #2982

**Pull request merged**
