### PR TITLE
[MRG] DOC Remove "Ubuntu" section from sidebar/ToC

### PR DESCRIPTION
**Pull request by redapple**
Continuation of https://github.com/scrapy/scrapy/issues/2137

### CODE REVIEW

**Comment by kmike** [comment]
We still have to include ubuntu.rst somewhere because otherwise it is not built at all; tests are failing because of that

**Comment by redapple** [comment]
Bummer. In the FAQ perhaps

**Comment by pablohoffman** [comment]
do we still support ubuntu packages or not?

**Comment by redapple** [comment]
@pablohoffman no, but I guess we want old links to show the page (and the current caution note)

**Comment by pablohoffman** [comment]
understood, all good!

**Comment by redapple** [comment]
Used the `:orphan:` trick. Neat.

**Comment by kmike** [comment]
Thanks @redapple, nice trick!

**Pull request merged**
