### PR TITLE
Fix typos in three files for Flake8 check

### PR DESCRIPTION
**Pull request by AngelikiBoura**
Some fixes in the extensions files memusage.py and statsmailer.py and in the test file twisted_reactor_custom_settings_same.py
were needed in order for the flake8 check to be succesful.

### CODE REVIEW

**Comment by wRAR** [comment]
The changes look fine to me but the flake8 test already succeeds without these changes, does it fail for you?

**Comment by AngelikiBoura** [comment]
Yeah, i run tox -e flake8 and it showed me these changes in order to pass.

**Comment by wRAR** [comment]
This is strange because neither `tox -e flake8` nor installing the latest flake8 and running it directly have any errors here.

**Comment by AngelikiBoura** [comment]
It is indeed. I'll try running it again then from a different computer and
let you know.

**Comment by wRAR** [comment]
Actually, `flake8 scrapy tests docs` processes them but `pytest --flake8 scrapy tests docs` doesn't, because pytest skips these files via conftest.py and tests/ignores.txt. I wonder how can we improve this to not skip any files when running flake8 and other checkers.

**Review by wRAR — APPROVED** [review]

**Comment by wRAR** [comment]
I also don't remember why those three files in tests/ignores.txt are there.

**Comment by AngelikiBoura** [comment]
When i ran now the same command from my terminal the check passed successfully without the changes.
The check didn't pass when i ran the command through the terminal of my IDE (pycharm).  
I'm not sure if this info is useful but i hope it helps.

**Review by Gallaecio — APPROVED** [review]

**Comment by Gallaecio** [comment]
Thanks!

**Pull request merged**
