### PR TITLE
[MRG+1] Cleanup http11 tunneling connection after #1678

### PR DESCRIPTION
**Pull request by lopuhin**
As discussed here https://github.com/scrapy/scrapy/pull/1678#discussion-diff-50129295 - this way is indeed much more readable :)

### CODE REVIEW

**Comment by redapple** [comment]
Indeed. +1

**Comment by redapple** [comment]
In fact, this does not work with hostname as bytes.
I just got the error while testing scrapy 1.1 with Crawlera, the string ending up as `b"CONNECT b'httpbin.org':443 HTTP/1.1\r\n"`
I'll submit a PR for this.

@kmike , @eliasdorneles , @lopuhin , which has your preference?

the original 
```
        tunnelReq = (
            b'CONNECT ' +
            to_bytes(self._tunneledHost, encoding='ascii') + b':' +
            to_bytes(str(self._tunneledPort)) +
            b' HTTP/1.1\r\n')
```

or a fix on bytes param with
```
        tunnelReq = to_bytes(
            'CONNECT %s:%s HTTP/1.1\r\n' % (
                to_unicode(self._tunneledHost),
                self._tunneledPort), encoding='ascii')
```

**Comment by eliasdorneles** [comment]
oh, it all started with my nitpicking, sorry. =/

I'd go with the original (minimal # of conversions).

**Comment by lopuhin** [comment]
Oh, sorry @redapple - did not check properly. I have no particular preference, but for me second still looks slightly better.

**Comment by lopuhin** [comment]
Ah, I see you already fixed this - thanks @redapple ! :)

**Pull request merged**
