### PR TITLE
[MRG+1] Print more dependencies versions in "scrapy version" verbose output

### PR DESCRIPTION
**Pull request by redapple**

### CODE REVIEW

**Comment by redapple** [comment]
In theory, scrapy requires w3lib>=1.15 so the try/except may not be needed.
(You never know what users may end up with though)

**Comment by kmike** [comment]
What do you think about adding optional dependencies? boto / botocore / Pillow?

**Comment by kmike** [comment]
I also think that's fine to have this feature in Scrapy 1.2.x

**Comment by redapple** [comment]
Good idea about adding the optional dependencies too. Another PR maybe?

**Comment by redapple** [comment]
> I also think that's fine to have this feature in Scrapy 1.2.x

Right, we can still do that. We haven't started 1.3.x

**Pull request merged**
