### PR TITLE
CrawlerProcess cleanup

### LINKED ISSUE #1279: to stop CrawlerProcess started with stop_after_crawl=False two Ctrl-Cs are required
When CrawlerProcess is started with `stop_after_crawl=True` (default) and user presses Ctrl-C the following happens:

1. Ctrl-C signal handler is changed to "unclean shutown" so that second Ctrl-C will definitely stop the reactor;
2. `self.stop` method is called which asks all crawlers to stop;
3. when all crawlers are stopped a Deferred returned from `self.join()` executes its callback. This callback is set to "stop reactor", so the reactor stops.

But with `crawler_process.start(stop_after_crawl=False)` there is no step (3) because `self.join` is not used. It means that to stop CrawlerProcess user have to send signal (press Ctrl-C) twice. The first Ctrl-C only asks all current crawlers to stop.

I think it is better to change it - a signal should mean "graceful shutdown" regardless of `stop_after_crawl` option.

### PR DESCRIPTION
**Pull request by kmike**
* removed unnecessary lambda (@Curita - is it unnecessary? why did you add it?)  
* fixed #1279;
* DNS setup is extracted to `_get_dns_resolver` method.

### CODE REVIEW

**Comment by dangra** [comment]
> DNS setup is extracted to _get_dns_resolver method.

is it a preparation to resolver classpath as setting?

**Comment by dangra** [comment]
> removed unnecessary lambda (@Curita - is it unnecessary? why did you add it?)

probably the result of multiples unordered merges.

**Comment by kmike** [comment]
> is it a preparation to resolver classpath as setting? 

No, it was just a cleanup to make code fit 80 columns :) My editor has a vertical line and barks at me when code doesn't fit.

**Comment by dangra** [comment]
> No, it was just a cleanup to make code fit 80 columns :) My editor has a vertical line and barks at me when code doesn't fit.

good :dog: deserves to be listen.

**Pull request merged**
