### PR TITLE
Remove deprecated class HtmlParserLinkExtractor

### PR DESCRIPTION
**Pull request by ashellunts**
Issue #4356

### CODE REVIEW

**Comment by wRAR** [comment]
Can you please also remove it from tests/ignores.txt?

**Comment by ashellunts** [comment]
> Can you please also remove it from tests/ignores.txt?

I have not found any other usage of mentions of HtmlParserLinkExtractor. Please let me know if something else should be removed.

**Comment by wRAR** [comment]
Have you looked at tests/ignores.txt?

**Comment by ashellunts** [comment]
> Have you looked at tests/ignores.txt?

I have done full text search in repository and have not found anything. Also checked .gitignore.

**Comment by wRAR** [comment]
If you look at tests/ignores.txt you will see it mentions scrapy/linkextractors/htmlparser.py.

**Comment by ashellunts** [comment]
Sorry, now I got it. First I read your comment as "please check tests and git ignore files".

**Pull request merged**
