### PR TITLE
[MRG+1] TST pin pytest-cov to 2.2.1; upgrade pytest

### PR DESCRIPTION
**Pull request by kmike**
Scrapy testing suite is failing now. I've tried to downgrage/upgrade several dependencies; this looks related to pytest-cov 2.3.0 release. pytest is upgraded just in case; just upgrading pytest didn't help.

### CODE REVIEW

**Comment by kmike** [comment]
Locally several tests fail for me with mysterious errors:

```
self = <tests.test_commands.ParseCommandTest testMethod=test_pipelines>
pp = <scrapy.utils.testproc.TestProcessProtocol instance at 0x104f15998>
cmd = ['/Users/kmike/svn/scrapy/.tox/py27/bin/python2.7', '-m', 'scrapy.cmdline', 'parse', '--spider', 'parse_spider', ...], check_code = True

    def _process_finished(self, pp, cmd, check_code):
        if pp.exitcode and check_code:
            msg = "process %s exit with code %d" % (cmd, pp.exitcode)
            msg += "\n>>> stdout <<<\n%s" % pp.out
            msg += "\n"
            msg += "\n>>> stderr <<<\n%s" % pp.err
>           raise RuntimeError(msg)
E           RuntimeError: process ['/Users/kmike/svn/scrapy/.tox/py27/bin/python2.7', '-m', 'scrapy.cmdline', 'parse', '--spider', 'parse_spider', '--pipelines', '-c', 'parse', 'http://localhost:50521/html'] exit with code 1
E           >>> stdout <<<
E           
E           
E           >>> stderr <<<
E           /Users/kmike/svn/scrapy/.tox/py27/bin/python2.7: No module named scrapy
```
 but they pass when executed without the rest of testing suite. This PR haven't addressed it.

**Comment by redapple** [comment]
+1 @kmike , I've also forced `pytest-cov<2.3` locally and got rid of `Coverage.py warning: No data was collected.` message I was seeing

**Comment by kmike** [comment]
@redapple can we merge it?

**Comment by kmike** [comment]
hehe you're faster :)

**Comment by eliasdorneles** [comment]
:+1:

**Pull request merged**
